### ISSUE TITLE
7 second pitch

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#113]
Set the 7 second pitch of the project

**Comment by M4rtine** [comment]
" Welcome to the First geolocalization database of CG Studio. This database belongs to you. it's up to you sharing, editing and reading it. "

**Comment by foutoucour** [comment]
Key words of the poject:
* community
* opensource (est ce que les utilisateurs sont vraiment interesse par ce point?)
* wiki
* data center
* job hunting
* free access
* platform

based on @M4rtine sentence:
* cgstudiomap is the premier open-data center of computer graphics' industry. Come  in and update, share, or simply read content.
* cgstudiomap is a free-access premier database of computer graphics companies. This open-data center belongs to you. Come in and start sharing, updating or simply reading it.

**Comment by M4rtine** [comment]
i think you make the good correction. But with more reflexion i think it's not working with the idea of Simon Sinek

" We believe that People should know more about any CG studio. "

**Comment by foutoucour** [comment]
This approach is way better. You are definitely right. The previous
sentence should be used later when our purpose is defined the way you did.

**Comment by foutoucour** [comment]
Other motto sentences:
- We believe that knowledge on CG Studios should be for everyone
- We dream about an industry easy to be accesses/understood/approached
- We believe you have the right to understand your world.

So far I prefer the sentence from David. It is more people centric.

**Comment by foutoucour** [comment]
" We believe that People should know more about any CG studio. We designed the premier open-data center of computer graphics' industry. Come in and update, share, or simply read content. "
it is!
thanks @M4rtine :)
