### ISSUE TITLE
Website_menus display a icon

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#115]
To light up the navbar of the front end, we want to be able to display a icon for the title of the website_menu

The new setup should allow the admin to: 
* use a boolean to display an icon or not
* user a boolean to display the text or not
* set up the class related to the <i> tag

**Comment by foutoucour** [comment]
Sorry @M4rtine but this won't be available for the first launch of the website. 
The design should have the text as the first draft.

**Comment by MangoJazz** [comment]
@M4rtine do you still want that?

**Comment by M4rtine** [comment]
not yet ;)

**Comment by M4rtine** [comment]
Avec la nouvelle façon de gérer les templates. On a plus facilement la main sur les icônes.
Je ne pense pas que cette issue soit encore d'actualité. ;)

**Comment by foutoucour** [comment]
tout a fait :)

ps @M4rtine dans ce cas mets la tache en review pour quelle soit mise en avant comme quoi tu attends une validation.
