### ISSUE TITLE
Blog post: How to use advanced search OR/AND

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#127]
Blog post that show where is the advanced search and how to make boolean operation as AND and OR

**Comment by juli1r** [comment]
I just edit the drive for this task and upload pictures to explain.

Please review :-)

https://drive.google.com/drive/folders/0BxO_vIgIHG3FfldGd0c0UVhWWm01VlpfY2U5bmlvV2pmNmdiZXZ2dUdRS0w4V1hEeHNKemc

**Comment by MangoJazz** [comment]
I like your pictures with the arrow. Could you do something like this for the post HOW to edit or create content?

Also I am not able to revise your doc :(

**Comment by MangoJazz** [comment]
Done chewby :)

Correction in the comment section & suggestion for the whole sentence in blue underneath.

**Comment by juli1r** [comment]
ok thanks :-)

I'll made the change for the arrow tonight or this weekend

**Comment by MangoJazz** [comment]
Hey Julien could you please place nice pictures like the ones you have for this post?

In this one: http://www.cgstudiomap.org/blog/blog-1/post/how-to-edit-create-content-7#scrollTop=0

**Comment by juli1r** [comment]
I don't have the access to see this page...

**Comment by foutoucour** [comment]
yes you do :p

**Comment by foutoucour** [comment]
@MangoJazz is talking about #138 issue (just to make the trail between the both issues)

**Comment by MangoJazz** [comment]
Done & published online.
Schedule on social media for Wednesday.
http://ow.ly/Q6hK6
