### ISSUE TITLE
Blog post: How to use basic search

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#128]

**Comment by juli1r** [comment]
Hi,

two documents have been upload on the drive to control and correction.

https://drive.google.com/drive/folders/0B8fU00hjqfdnfjFoV19EOHlFUEppYVh4Nm1uZUR3cFJyM1RjRi1aSWtYcFNxWjhCUlZCUnM

Let me know if you need more details on each field or not.

Good evening.

**Comment by foutoucour** [comment]
The ticket is merged with #127
