### ISSUE TITLE
Blog post: Different types of view

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#129]

**Comment by juli1r** [comment]
Hi,

here the link to check and review:

https://drive.google.com/drive/folders/0B8fU00hjqfdnfjFoV19EOHlFUEppYVh4Nm1uZUR3cFJyM1RjRi1aSWtYcFNxWjhCUlZCUnM

**Comment by foutoucour** [comment]
Awesome. Edith will take a look at it then I will publish it.

the blog is available now on the production

**Comment by foutoucour** [comment]
Edith did a review of the copy at: https://docs.google.com/document/d/1mLgyXDGJSY6HAmVeiBnCdNjvVvw2ATB71VVL4M5c-F4/edit

Need to push it to prod.

**Comment by foutoucour** [comment]
Published: http://cgstudiomap.org/blog/blog-1/post/how-to-cgstudiomaps-different-views-4
