### ISSUE TITLE
Dashboard map controls

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#135]
Mouse controls not working in my acount access. 
drag and zoom

**Comment by foutoucour** [comment]
Oh damn
I will bring the hand back. Unfortunately o can't just hide it :(

**Comment by foutoucour** [comment]
Controls are back in https://github.com/cgstudiomap/geospatial/commit/894cd6f606dc019f148ee6efae9052fe2a461c82

![7_20150530_001](https://cloud.githubusercontent.com/assets/547282/7897818/3fc7a3f4-06b9-11e5-931c-1bbc695bd829.png)

**Comment by foutoucour** [comment]
Push to production 8 June 2015
