### ISSUE TITLE
revise homepage map colors

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#137]
The yellow for contries with few company 8s really light.

Do you think it should be updated?

**Comment by M4rtine** [comment]
Yellow is only set for not implement the new color design in half way.
I know it is not the def color

Le lundi 25 mai 2015, Jordi Riera <notifications@github.com> a écrit :

> Assigned #137 <https://github.com/cgstudiomap/cgstudiomap/issues/137> to
> @M4rtine <https://github.com/M4rtine>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/137#event-313052599>.
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*
