### ISSUE TITLE
blog post: how to manage studios

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#138]
Write a blog post on how users can create, modify a studio.

This might need 2 posts, like regular user, then advanced (duplication for example)

**Comment by MangoJazz** [comment]
For review please 

http://cgstudiomap.org/blog/blog-1/post/how-to-edit-create-content-7

**Comment by foutoucour** [comment]
The text is good but I can see some way to improve it:
* use 2 columns like we did for previous posts. That should give so structure to the blocks. 
* I would be interested to see how it will do if all images have the same width.

Text wise, it is good to go.

**Comment by juli1r** [comment]
Hey I have upload some pictures and a doc in the drive. If someone can review :-)

https://drive.google.com/drive/folders/0B8fU00hjqfdnfjk2WXFPS3VZWEE1ZzA2Tk5iUmhId0xIYTZZakdLMzNsWU0wU2dNVmw2Rjg

**Comment by MangoJazz** [comment]
Nice Tx :)

@foutoucour just need to edit the blog post with the images and text.

**Comment by MangoJazz** [comment]
et voici ce que ça donne maintenant.

http://cgstudiomap.org/blog/blog-1/post/how-to-edit-content-7#scrollTop=2288

**Comment by juli1r** [comment]
Nice I prefer this version :-)

**Comment by foutoucour** [comment]
Published the 11th of July, 2015
