### ISSUE TITLE
Add more details in missing details page in res.partner

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#149]
For now, the missing details themselves guide the user. We want to also add some text to guide the user when he solves the details.

We would like to add:
* [ ] some text to explain that the user should remove the missing details if it solved. (the missing details bot will do it anyway some day but would be helpful if the user keep it up-to-date.)
* [ ] Find a way to ask the user, if he found the missing details, to update the card actually.

**Comment by MangoJazz** [comment]
deplucated
