### ISSUE TITLE
Organisation in Canada

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#158]
cgstudiomap has the plan to be an organization but we don't have the details on how to create it and what that means to be an organization in Canada.

cgstudiomap wants to be a non-profit association, aiming at helping it users. By organisation I want to mean this profile.

Needs to:
- [ ] finds the paper needed to set up the organization
- [ ] what are the requirements of an organization
- [ ] what are the restrictions linked to the status
- [ ] We need to know what kind of income an organization have? I am thinking about donations but their surely some others kind. 
- [ ] can we have members that are out of the Canada?
- [ ] what kind of contract do we need to officialize the work of a member of the association?

**Comment by juli1r** [comment]
After loosing time with some others website I have found this one with most of the information needed (obligations, papers, rights..).

The only thing I cannot find is if an association can have international member, I think it's possible but I can't find anything on that. May be someone can help on this? :-)

See the related drive document for the website, the "good" link is at the bottom.

**Comment by foutoucour** [comment]
@MangoJazz Check this: https://docs.google.com/document/d/1Q7svG7wJY6EdBA9R_vdCJfbdgkNwqlht3f7lKdAZir4/edit

**Comment by foutoucour** [comment]
related to #204

**Comment by MangoJazz** [comment]
I would like to hold on with the organization BP because I believe cg Studio Map could do bigger and better.
Thank you

**Comment by foutoucour** [comment]
won't do
On a besoin de savoir ce qu'on fait avant de s'astatuer comment.
