### ISSUE TITLE
Blog Post: Announcement of cgstudiomap coming back

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#159]
Create the text we will use to announce the opening of cgstudiomap to everyone.

This announcement is planned to the 15th of July at the same time the project turn to Beta.

**Comment by MangoJazz** [comment]
The wip can be found at: https://docs.google.com/document/d/1VeE_KwWYp1hiI6dse2i-UqwVBnDnwO3qXlOnTFSPHYc/edit

@foutoucour @M4rtine @juli1r 
Could someone add some pictures please? Also it might needs grammar correction from you.

**Comment by MangoJazz** [comment]
Please review :)
http://cgstudiomap.org/blog/blog-1/post/grand-coming-back-july-15th-5

**Comment by foutoucour** [comment]
I did some minor updates:
* added sign up button at the bottom
* added share buttons at the button too

Good to go for me. I program the publish to the next Wednesday
