### ISSUE TITLE
Translate wiki page cgstudiomap.com by numbers

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#160]
The wiki page https://github.com/cgstudiomap/cgstudiomap/wiki/cgstudiomap.com-by-numbers
is by lazyness/history in french mostly.

It will need to be translated. The aim of the page is to provide some details to press or people that want to know more about the project.

**Comment by MangoJazz** [comment]
Done, will be online on the blog and the press kit.
