### ISSUE TITLE
Blog post: opened beta

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#161]
Blog post announcing the opening!

The blog post should clearly communicate that cgstudiomap is now opened to everyone. Everyone can sign up.

**Comment by MangoJazz** [comment]
Please review
http://www.cgstudiomap.org/blog/blog-1/post/cgstudiomap-is-back-8#scrollTop=800

**Comment by foutoucour** [comment]
I will find you a picture for the cover.

As following your advice, I will try to find a little story to add to it to make it more personal. That will help us also to know why we are back

**Comment by foutoucour** [comment]
Scheduled publish for the 15th July

**Comment by MangoJazz** [comment]
il manque ton experience personnelle à ajouter STP

**Comment by foutoucour** [comment]
note from the founder added.
