### ISSUE TITLE
Front page text

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#168]
https://mail.google.com/mail/u/0/?ui=2&ik=4e9b3d2436&view=fimg&th=14e7ef33e8a85b3c&attid=0.1&disp=emb&realattid=14e708379006bad6f381&attbid=ANGjdJ8qN7W9grdq7SFruHLeC3hvyYGCT1uvfnAyZ60Mo6vnctxn6d1m-TVIctd4I1SChUTxEyPHJ3eiiHxyfjb7lLuLFnn5P726lm2a85-JyO_CJ1C5nw1jxOn8bm0&sz=s0-l75-ft&ats=1436648980180&rm=14e7ef33e8a85b3c&zw&atsh=1

**Comment by MangoJazz** [comment]
https://mail.google.com/mail/u/0/?ui=2&ik=4e9b3d2436&view=fimg&th=14e7ef33e8a85b3c&attid=0.2&disp=emb&realattid=14e7ef2c2b85ed295901&attbid=ANGjdJ-fjvOjB7N46ZXRNUIbW5ns83iLVZqz2EKFAx9J_1yDPnSGNI8vrInYmKXjQNoLWS4if7oEjuGSNzNVKBVJQ9exmQXA7hAKOao8EK-95wd70B8wo77abMnyhY8&sz=s0-l75-ft&ats=1436648980180&rm=14e7ef33e8a85b3c&zw&atsh=1

**Comment by foutoucour** [comment]
you cant copy an email url. It does not work for other users. Please copy the text you want us to read instead.

**Comment by MangoJazz** [comment]
and here you go sorry about that :)
https://docs.google.com/document/d/1BcED8a-V2lbzheed64rdx1boH2gL-Yo7DnqhgdPA5ag/edit

**Comment by foutoucour** [comment]
The text has been copied. I close the ticket and we will follow up on #87
