### ISSUE TITLE
Remove Zip as required field

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#170]
There is some countries, Chile in mind, which don't use zip code so the field cannot be mandatory.
It should be filled by the google geocode anyway if there is.

For that:
- Edit `res.partner.py` in `main_data` module to remove the requirement for the zip field.

**Comment by MangoJazz** [comment]
well spoted.

**Comment by foutoucour** [comment]
Fixed 
![6_20150714_001](https://cloud.githubusercontent.com/assets/547282/8687042/2c7e2100-2a5a-11e5-93e1-316ce74dbfeb.png)
