### ISSUE TITLE
Contacts to make some noise about the release of the beta

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#176]
contact:
* [x] 3d-station
* [x] 3dvf (http://www.3dvf.com/actualite-13855-cgstudiomap-rouvre-ses-portes.html)
* [x] cgsociety
* [x] 3dpro list (15th July)
* [ ] julien MPC
* [ ] oba/thomas weta
* [x] gus
* [ ] Francois
* [x] fxguide (mangoJazz)
* [x] cghub
* [x] Linkedin post: https://www.linkedin.com/pulse/article/new?trk=hp-share-poncho-pencil

**Comment by MangoJazz** [comment]
Je m'en occupe avec toi.

Le mardi 14 juillet 2015, Jordi Riera <notifications@github.com> a écrit :

> contact:
>
>    -  3d-station
>    -  3dvf
>    -  cgsociety
>    -  3dpro list
>    -  julien MPC
>    -  oba/thomas weta
>    -  gus
>    -  Francois
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/176>.
>


-- 


Edith Courtial
T: +1 438 875 7220

<http://ca.linkedin.com/in/edithcourtial/>

**Comment by M4rtine** [comment]
Contact
http://www.videocopilot.net

**Comment by foutoucour** [comment]
@MangoJazz could you take contact with fxguide: http://www.fxguide.com/contact/ ? it is a major website that write articles about the industry. We don't have any contact with them yet.

@M4rtine hey thanks. But are you sure they can advertise/write on us? They seems it is more a company that should be on our listing as software provider.

**Comment by M4rtine** [comment]
I have some contact it is only for increase users

Le mercredi 15 juillet 2015, Jordi Riera <notifications@github.com> a
écrit :

> @MangoJazz <https://github.com/MangoJazz> could you take contact with
> fxguide: http://www.fxguide.com/contact/ ? it is a major website that
> write articles about the industry. We don't have any contact with them yet.
>
> @M4rtine <https://github.com/M4rtine> hey thanks. But are you sure they
> can advertise/write on us? They seems it is more a company that should be
> on our listing as software provider.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/176#issuecomment-121669525>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by MangoJazz** [comment]
done for fxguide, I will give you the updates whenever.

**Comment by herronelou** [comment]
You might want to write a big BETA somewhere, because now using the site feels very un-finished, and it's not made clear anywhere that this is a BETA, except in this one GIT issue.

**Comment by M4rtine** [comment]
It's a good idea
Thanks

Le jeudi 16 juillet 2015, Erwan Leroy <notifications@github.com> a écrit :

> You might want to write a big BETA somewhere, because now using the site
> feels very un-finished, and it's not made clear anywhere that this is a
> BETA, except in this one GIT issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/176#issuecomment-121843469>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by foutoucour** [comment]
The issue about the tag beta will be addressed in #189. 
Please follow up the conversation about beta tag in the new issues to avoid to poluate this issues. 

Regards

**Comment by M4rtine** [comment]
cghub


Le jeudi 16 juillet 2015, Jordi Riera <notifications@github.com> a écrit :

> The issue about the tag beta will be addressed in #189
> <https://github.com/cgstudiomap/cgstudiomap/issues/189>.
> Please follow up the conversation about beta tag in the new issues to
> avoid to poluate this issues.
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/176#issuecomment-121950743>
> .
>


--

**Comment by foutoucour** [comment]
cghub has been added.
Do you have any contact with them by any chance?

**Comment by foutoucour** [comment]
Need to post an article on Linkedin. I should give us so visits: https://www.linkedin.com/pulse/article/new?trk=hp-share-poncho-pencil

**Comment by MangoJazz** [comment]
Contacted the one clicked above + Reddit
Here the post on linkedin: "Cgstudiomap is back!" by @EdithCourtial on @LinkedIn https://www.linkedin.com/pulse/cgstudiomap-back-edith-courtial

**Comment by MangoJazz** [comment]
Contacted all the following that wrote an article about cgstudiomap previously:
- Catsuka
- Dotmogo
- Square MTC (added on cgstudiomap)
- create3Dcharacters
- Motiongrapher
- CG Channel
- VFX World Map (yes I did!)

**Comment by foutoucour** [comment]
you also can use this list: https://docs.google.com/spreadsheets/d/1u7eO9YJfctKQoWXyKN-ViVzYunyc-qnpBaIXK9lHdjc/edit#gid=0

**Comment by foutoucour** [comment]
contacts have been done
