### ISSUE TITLE
anchor to scroll

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#179]
Some users don't scroll and think the homepage is only the page.

We need to create a button that scroll from the map to the first other part of the homepage.

For that:
- the template homepage should be updated to have an anchor to the next div

**Comment by M4rtine** [comment]
I see ;)
It's simple

Le mercredi 15 juillet 2015, Jordi Riera <notifications@github.com> a
écrit :

> Assigned #179 <https://github.com/cgstudiomap/cgstudiomap/issues/179> to
> @M4rtine <https://github.com/M4rtine>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/179#event-356416638>.
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by M4rtine** [comment]
Merge to #192
