### ISSUE TITLE
Error:The address cannot be geolocalized. Please enter a valid street address.

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#183]
Trying to add a studio in China, street address (written in english) cannot be geo-localized, won't let add the studio.
Need to be able to manually localize the place on the map like old CGStudioMap.

**Comment by foutoucour** [comment]
Sadly the current setup cannot allow to do it and it might need important development to do it.

It has been reported on the roadmap: https://trello.com/c/DmbqOsS4
