### ISSUE TITLE
User interface non-intuitive

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#185]
The current user interface isn't very user friendly.
I had to look around, clicking a a few "wrong buttons" trying to find a way to add a studio.
Adding the studio itself isn't intuitive either.
Why is the map into "dashboard"? What is the "reporting" tab for?

**Comment by foutoucour** [comment]
A new interface is being built, out of odoo, so we have a better control on the UX.

We will let you know when the new interface is fully operational.
