### ISSUE TITLE
Closing a search filter reloads the map

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#188]
When using the search bar in the top right corner, it works fine, but when clearing the bar in order to do a new search, it reloads the full world map, and freezes for a few seconds until the map is reloaded.

**Comment by foutoucour** [comment]
Thank you @herronelou for the report,

By reseting the search bar, you ask to display back all the 1800 studios. That's why the website is freezing. It actually reload the data to be accurate with changes that could have occured in meantime.

**Comment by foutoucour** [comment]
@herronelou We did an update of the code, it should be faster by now. Let me know if it is better for you.

**Comment by herronelou** [comment]
No, still the same.
It's alright for general use, but we were looking up a few studios in a row, and everytime you have to type one, wait to find it, clear it, wait to reload, type the new one, etc..
Maybe a possible optimization would be to only reload the ones on the current view instead of resetting to the full map? Or don't do anything until the user makes an action? If they start playing with the map reload the stuff, if they type a new word, wait until they search that word?
Other alternative, when doing a search on the map, just highlight the matches without unloading the other studios?
What was happening on the old website based on google was much smoother, when fully zoomed out it wouldn't display every single studio, just big dots saying "XXX studios".

**Comment by foutoucour** [comment]
This issue should be fixed by the new interface.

I will let you know when the new listings are up

**Comment by foutoucour** [comment]
New pages for the map and the listing have been deployed.

That should have resolved the issue mentioned here.
Feel free to open new issues if you face new unwanted experience.

Best,
Jordi
