### ISSUE TITLE
Visible BETA tag on the website

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#189]
Following a comment from @herronelou: 
> You might want to write a big BETA somewhere, because now using the site feels very un-finished, 
> and it's not made clear anywhere that this is a BETA, except in this one GIT issue._

A tag that inform about the Beta stage of the website should be displayed on the frontend and backend.

@M4rtine How would you do it?

**Comment by M4rtine** [comment]
Yes

Le jeudi 16 juillet 2015, Jordi Riera <notifications@github.com> a écrit :

> Assigned #189 <https://github.com/cgstudiomap/cgstudiomap/issues/189> to
> @M4rtine <https://github.com/M4rtine>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/189#event-357493683>.
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by foutoucour** [comment]
How do you think to do it? Update of the logo with a `Beta` on it for example?

**Comment by M4rtine** [comment]
A badge with the word 'beta'

Le jeudi 16 juillet 2015, Jordi Riera <notifications@github.com> a écrit :

> How do you think to do it? Update of the logo with a Beta on it for
> example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/189#issuecomment-121951409>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by foutoucour** [comment]
Ok sounds good

On Thu, Jul 16, 2015 at 9:14 AM David Mazeau <notifications@github.com>
wrote:

> A badge with the word 'beta'
>
> Le jeudi 16 juillet 2015, Jordi Riera <notifications@github.com> a écrit :
>
> > How do you think to do it? Update of the logo with a Beta on it for
> > example?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgstudiomap/cgstudiomap/issues/189#issuecomment-121951409
> >
> > .
> >
>
>
> --
>
> ____________________________
>
> *david.mazeau*
> *06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/189#issuecomment-121952421>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by MangoJazz** [comment]
A button with BETA in large and big letters

**Comment by M4rtine** [comment]
Merge to #192
