### ISSUE TITLE
[BUG] Companies can be created without being assigned to Media

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#190]
The current way to define a company has been part of Media industry family is from the context of the view.
2 companies have been created without being assigned to the Media industry.
And only companies from Media industry are displayed on the map.

It seems the context is not reliable and we need to find another way to setup the value.

We may just set a default value for the field and when we will want to add a company that should not be in the map (partner to cgstudiomap for example), we just remove the value.
It will require then, for admin, or internal sale team to have access to the field. It is not a big deal for now.

**Comment by M4rtine** [comment]
It 's a good idea.
I think "partner" is not the good word.
Idea of waiting to publish or pending or not listed
Or waiting approval

;)

Le jeudi 16 juillet 2015, Jordi Riera <notifications@github.com> a écrit :

> The current way to define a company has been part of Media industry family
> is from the context of the view.
> 2 companies have been created without being assigned to the Media industry.
> And only companies from Media industry are displayed on the map.
>
> It seems the context is not reliable and we need to find another way to
> setup the value.
>
> We may just set a default value for the field and when we will want to add
> a company that should not be in the map (partner to cgstudiomap for
> example), we just remove the value.
> It will require then, for admin, or internal sale team to have access to
> the field. It is not a big deal for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/190>.
>


--

**Comment by foutoucour** [comment]
Should be fixed with the new process of creating a company
