### ISSUE TITLE
homepage Design small correction

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#192]
- [x] bad select zone in top navbar
- [x] bottom arrow with anchor
- [x] top arrow with anchor
- [x] static top navbar fix
- [x] use regular, thin and light font
- [x] fontsize 
- [x] colors socials icons
- [x] layout footer
- [x] layout popup
- [x] full logo top of stats
- [x] logo colors img path XML
- [x] beta tag
- [x] clean not used lib or code
- [x] bootstrap + wrapwrap odoo bug
- [x] simplify for mobile version
- [x] list studios better grid

**Comment by M4rtine** [comment]
merge to #177

**Comment by M4rtine** [comment]
Et Voilà !
we must check the commented JS on the footer. If it work we must delete. @foutoucour

**Comment by foutoucour** [comment]
Please provide screen shots about the work you have done. It will help us to see the steps done

![cgstudiomap 2015-07-19 13-02-55](https://cloud.githubusercontent.com/assets/547282/8766863/84ffc918-2e16-11e5-88ef-ff09b08180a0.png)

Few comments:
* I can't find the SIGN-IN button in the top-navbar. How do I log in the website then?
* the anchor goes to the part "More", jumping a the part describing our mission. Could you change it it?

**Comment by M4rtine** [comment]
Sorry for screenshots i will make it for the next.

- SIGN IN button: I dont know why. I don't touch variables

- anchor : it's simple no problem




> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/192#issuecomment-122683137>
> .
>


--

**Comment by foutoucour** [comment]
Sorry my bad, I missed some piece of code.

68f14f9 implements it

![9_20150719_001](https://cloud.githubusercontent.com/assets/547282/8767630/86e7f5ce-2e30-11e5-80f7-a21f6e873273.png)

**Comment by M4rtine** [comment]
Is the" part describing our mission" begin to "cg studio map is... ?




--

**Comment by foutoucour** [comment]
At the part, "Because everyone should..." The anchor should just jump over
the map actually. Make sense?

On Mon, Jul 20, 2015 at 1:17 PM David Mazeau <notifications@github.com>
wrote:

> Is the" part describing our mission" begin to "cg studio map is... ?
>
>
>
>
> --
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/192#issuecomment-122957186>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
Yes ;)



--

**Comment by M4rtine** [comment]
Anchor is done and i add more Space un order to increase Space after thé scrolling down animation.

@foutoucour How the commented JS is working with the real database ?

**Comment by foutoucour** [comment]
I give it a try tonight but should be fine.

On Mon, Jul 20, 2015, 6:12 PM David Mazeau <notifications@github.com> wrote:

> Anchor is done and i add more Space un order to increase Space after thé
> scrolling down animation.
>
> @foutoucour <https://github.com/foutoucour> How the commented JS is
> working with the real database ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/192#issuecomment-123066117>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
ok i m waiting the update :D

**Comment by foutoucour** [comment]
It is online. Check it out.

**Comment by M4rtine** [comment]
There is 2 problem yet.
Only on mobile:
[ ] navbar is affect by body padding in others pages
[ ] stats has too many digits, it's not working fine in 1 row




--

**Comment by foutoucour** [comment]
I close the ticket as the tasks have been spread in different issues.
