### ISSUE TITLE
Simplify industries?

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#197]
As an user, when I look at the companies, I mostly want to see if they are doing, VFX, Games, Animation, Software or Other.
Maybe too many categories now? And some missing (VFX?)

**Comment by M4rtine** [comment]
@foutoucour cette proposition était en cours ou c'était fait ?

**Comment by foutoucour** [comment]
@M4rtine tout a fait!

![selection_014](https://cloud.githubusercontent.com/assets/547282/18257088/45478682-738c-11e6-9a68-dd8418131055.png)
