### ISSUE TITLE
Placeholder studio logo

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#198]
More sexy placeholder studio logo 
Because in the homepage studios with no logo is ugly

**Comment by foutoucour** [comment]
I change the behavior of the frontpage in #177 but I would like anyway to have a better placeholder.

**Comment by foutoucour** [comment]
Also, image is now mandatory.

**Comment by foutoucour** [comment]
This is really low priority

**Comment by foutoucour** [comment]
This would be interested for #252

**Comment by foutoucour** [comment]
It will be done in #339
