### ISSUE TITLE
Create survey

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#199]
Create a survey on SurveyMonkey to ask feedback on first experience of our users.
 Spread the survey using emails of our users and by social networks.

**Comment by foutoucour** [comment]
Survey scheduled for the Monday 27th July.

url for social network: https://www.surveymonkey.com/r/cgstudiomap_user_experience_feedback

**Comment by M4rtine** [comment]
Really nice system
Do you think is it possible to put the logo white with purple background,
name and catchphrase

If it possible say to me what resolution you need



--

**Comment by foutoucour** [comment]
We did this setup

![9_20150725_002](https://cloud.githubusercontent.com/assets/547282/8890667/6ea0ce40-32d7-11e5-8c49-1839e46ac3c0.png)

**Comment by MangoJazz** [comment]
scheduled for Monday
