### ISSUE TITLE
Guys behind Project

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#202]
Do you think is that possible to humanize this project ? 
In order to explain that Behind this idea it's not a company but some guy with XP in CG and motivated.

in about ? in footer ?

bootstrap example : 
" Designed and built with all the love in the world by @mdo and @fat.
Maintained by the core team with the help of our contributors.
Code licensed under MIT, documentation under CC BY 3.0. "

**Comment by foutoucour** [comment]
What about a section team to personify the project?

On Sun, Jul 19, 2015 at 6:42 AM David Mazeau <notifications@github.com>
wrote:

> Do you think is that possible to humanize this project ?
> In order to exlain that Behind this idea it's not a company but some guy
> with XP in CG and motivated.
>
> in about ? in footer ?
>
> bootstrap example :
> " Designed and built with all the love in the world by @mdo
> <https://github.com/mdo> and @fat <https://github.com/fat>.
> Maintained by the core team with the help of our contributors.
> Code licensed under MIT, documentation under CC BY 3.0. "
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/202>.
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by MangoJazz** [comment]
oh a team tab nice



Edith Courtial
T: +1 438 875 7220

<http://ca.linkedin.com/in/edithcourtial/>

**Comment by MangoJazz** [comment]
We could add something in the about section underneath the contact us part!
What do you think?

**Comment by foutoucour** [comment]
Ca va etre integre dans la page About.

Les details a propos des contributeurs seront tires de la BDD directement.

**Comment by MangoJazz** [comment]
voir #269 meme tache,
