### ISSUE TITLE
Homepage studios display

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#203]
It's not necessary to show all working domains. I think the first is good enough. It's more easy to make simple visual.

For example : 
now
Picmo Animation Studio
Carmarthen, United Kingdom 
Animation, Broadcast Media, Computer Games, Design, Entertainment, Online Media 

update
Picmo Animation Studio
Carmarthen, United Kingdom 
Animation

**Comment by foutoucour** [comment]
studios industries are wrapped into spans now. You should be able to play with them easily now.

![7_20150719_001](https://cloud.githubusercontent.com/assets/547282/8767693/c00c479a-2e32-11e5-8123-69bbdfd50c4e.png)

**Comment by foutoucour** [comment]
the label still need improvement I would say. What do you think, @M4rtine?

**Comment by M4rtine** [comment]
Yes italic mode is not a good idea
Minor correction and it should be fine.



--

**Comment by foutoucour** [comment]
I think it is better to remove all of the labels instead to put only one. Only one would mean false information on our first page. I don't really like the idea.

What do you think @MangoJazz ?

**Comment by MangoJazz** [comment]
I guess just taking the label off. Every user knows it is a map with CG
companies. They can just look into the profile to see what label.

Le mercredi 5 août 2015, Jordi Riera <notifications@github.com> a écrit :

> I think it is better to remove all of the labels instead to put only one.
> Only one would mean false information on our first page. I don't really
> like the idea.
>
> What do you think @MangoJazz <https://github.com/MangoJazz> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/203#issuecomment-128217368>
> .
>


-- 


Edith Courtial
T: +1 438 875 7220

<http://ca.linkedin.com/in/edithcourtial/>

**Comment by M4rtine** [comment]
i think it's good now
in this release #227 Partner homepage
