### ISSUE TITLE
Business Plan

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#204]
Write a business plan

**Comment by foutoucour** [comment]
We won't go for the classic business plan. We are too in dark to be able to plan that far and I don't want to spend too much time on something we might change the minute we finish it.

I would like to test business model canvas. It seems it will be better for our needs.
http://leanstack.com/app/

**Comment by foutoucour** [comment]
Won't do.

See https://leanstack.com/canvases/310824/snapshot/2017-01-02
