### ISSUE TITLE
realize a survey

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#207]
Think about questions like: (French)

pourquoi vous etes venu sur le site? 
Pourquoi reviendrez vous sur le site? 
Pour quels services vous seriez pret à payer?
Seriez-vous pret a faire des dons pour faire avancer la mission de cgstm? 
Preferiez-vous acheter des t-shirt, mugs?
Si vous etes un studio, ou que vous ouvriez un studio demain, qu’attendez vous de cgstm?
question ouverte, genre donnez votre avis
issue:

**Comment by M4rtine** [comment]
" Préfériez vous acheter des tee-shirt, mugs ? "

Le dimanche 19 juillet 2015, MangoJazz <notifications@github.com> a écrit :

> Think about questions like: (French)
>
> pourquoi vous etes venu sur le site?
> Pourquoi reviendrez vous sur le site?
> Pour quels services vous seriez pret à payer?
> Seriez-vous pret a faire des dons pour faire avancer la mission de cgstm?
> Preferiez-vous acheter des t-shirt, mugs?
> Si vous etes un studio, ou que vous ouvriez un studio demain, qu’attendez
> vous de cgstm?
> question ouverte, genre donnez votre avis
> issue:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/207>.
>


--

**Comment by M4rtine** [comment]
" Préfériez vous acheter des tee-shirt, mugs ? "
Il faudrait plus parler de goodies qui nous permettent de nous soutenir et
participer activer a la promotion


--

**Comment by MangoJazz** [comment]
merge #199
