### ISSUE TITLE
Press kit

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#208]
- Find out what is a press kit
- Write one down
- Build-up a kit

for referals, links direction, articles...

**Comment by M4rtine** [comment]
If you need help for any graphical stuff, ask me.
Don't worry

Le mardi 21 juillet 2015, MangoJazz <notifications@github.com> a écrit :

>
>    - Find out what is a press kit
>    - Write one down
>    - Build-up a kit
>
> for referals, links direction, articles...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/208>.
>


--

**Comment by MangoJazz** [comment]
ok thank you :). Come to Montreal with your family :)

**Comment by foutoucour** [comment]
won't do
