### ISSUE TITLE
Branded item

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#210]
Hey guys, we thought about giving away something for free to the 1000th user, what do you think?

Maybe we could prepare a logo and Jordi and I could order a mug or T-shirt for the 1000 user.

That could be fun?

**Comment by foutoucour** [comment]
Hey, 

Our 1000th user is Michael Cordova (https://www.linkedin.com/pub/michael-cordova/2/381/893). He is compositor at Laika and at ILM.
I made contact with him via Linkedin.

I would prefer we go to a t-shirt.

**Comment by M4rtine** [comment]
Good pick ;)

>

--

**Comment by MangoJazz** [comment]
@foutoucour any news from Michael?
Should we prepare a look for a T-Shirt?

**Comment by foutoucour** [comment]
Branded items have been added to trello: https://trello.com/b/H6VhqMMU/backlog

**Comment by foutoucour** [comment]
No answer from the winner :(
