### ISSUE TITLE
4 digits on stats on mobile

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#211]
When we are on mobile, the current design is pretty clunky and hard to read.

![3_20150722_001](https://cloud.githubusercontent.com/assets/547282/8840963/14a42982-30b6-11e5-848a-77e47d74fbef.png)

**Comment by M4rtine** [comment]
![211_4digits_mobile](https://cloud.githubusercontent.com/assets/6338568/8894253/da344942-33af-11e5-869a-0fd173fd4627.jpg)
