### ISSUE TITLE
Follow google speed to speed up the website

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#212]
Following the advises from google PageSpeed we should find ways to make the website even faster.

https://developers.google.com/speed/pagespeed/insights/?url=www.cgstudiomap.org

It seems pretty easy. I start to consider to move away from digital ocean :(

**Comment by M4rtine** [comment]
do you subscribe to "Google webmaster" in addition to analytics.
we can analyse, put robot and other stuff in order to put in white list oui website

some errors in JS, i can do that...

**Comment by M4rtine** [comment]
i think you don't need to load any ressources about pages we don't se yet.
for example css or JS to homepage which use in contact page

**Comment by M4rtine** [comment]
and digital ocean is not a production solution. For testing it was good.
perhaps we find a solution that could be have a CDN solution for the futur

**Comment by M4rtine** [comment]
Check mobil test speed for Google map
We have a better score

**Comment by foutoucour** [comment]
I agree with you @M4rtine we need to find a new hoster.
Any advice?

ping @juli1r

**Comment by M4rtine** [comment]
http://aws.amazon.com/fr/ec2/
lot of pro is here :D

**Comment by juli1r** [comment]
I'll check this but AWS seems fine :-)

**Comment by M4rtine** [comment]
or that 
https://www.rochen.com/web-hosting/
good multiples reviews

**Comment by foutoucour** [comment]
Rate has been improved for desktop to 97

**Comment by foutoucour** [comment]
still need to work on improving the speed on mobile.

**Comment by foutoucour** [comment]
We will switch to AWS #261

**Comment by MangoJazz** [comment]
les plus gros points on ete fait
