### ISSUE TITLE
Kanban view

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#215]
Is it normal that we cannot scroll down when we are in Kanban view?

If I clicked on show more studios, it open however I can"t scroll down more studios, the page stays static.

**Comment by M4rtine** [comment]
I think it's not normal and i know where the problem is

**Comment by MangoJazz** [comment]
ok, let me know when it is fixed I will try again :)
cheers

**Comment by foutoucour** [comment]
Scroll bar is back in the backend.
@M4rtine the fix is very dirty but works. I let you do it a better way later :)
