### ISSUE TITLE
cgstudiomap in "contact us"

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#216]
I can't seem to be able to change the name cgstudiomap in the contact us part, it is all break down.
Please see screen shot.
![screen shot 2015-07-23 at 11 19 10 pm](https://cloud.githubusercontent.com/assets/13125734/8866977/5972e022-3191-11e5-83f1-f1d08b293b76.png)

**Comment by MangoJazz** [comment]
same again at the front page in the middle of the page :(

It should be cgstudiomap, no break

**Comment by M4rtine** [comment]
I put "cg Studio Map" in the first logo version in order to prevent the too
big and massive effect.
I think it's more readable and we see words priority in speed reading



--

**Comment by MangoJazz** [comment]
I think we should all agree in one way to write it. If you think for design
ourpose it is better then lets agree this way.
Could we not put a capital c then?

**Comment by M4rtine** [comment]
i'll think about all this issues

**Comment by MangoJazz** [comment]
I have change the name on each blog to make it even.
