### ISSUE TITLE
Tab name

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#217]
Could we change "blog" for "News & about"?

Could we change " Dashboard" for " directory"?

**Comment by foutoucour** [comment]
@MangoJazz 
What do you think?

![9_20150725_001](https://cloud.githubusercontent.com/assets/547282/8890265/e2725632-32c7-11e5-961b-11235324b157.png)

**Comment by M4rtine** [comment]
Do you think 'about' section is not the same than news ?
What do you think to merge about and contact section in one ´about' section
And put 'News' alone?
It's more simple with a less number off menu section and one word each.
Do you understand me ?

Le samedi 25 juillet 2015, Jordi Riera <notifications@github.com> a écrit :

> @MangoJazz <https://github.com/MangoJazz>
> What do you think?
>
> [image: 9_20150725_001]
> <https://cloud.githubusercontent.com/assets/547282/8890265/e2725632-32c7-11e5-961b-11235324b157.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/217#issuecomment-124859069>
> .
>


--

**Comment by M4rtine** [comment]
Like that

![217_tabname_02](https://cloud.githubusercontent.com/assets/6338568/8894071/9fa47e2e-33a9-11e5-94b5-7c00349a4a9c.jpg)

**Comment by MangoJazz** [comment]
yes @M4rtine it looks better I think so too.
@foutoucour ?

**Comment by foutoucour** [comment]
updated in #218 

![4_20150726_001](https://cloud.githubusercontent.com/assets/547282/8896334/7a484332-33c6-11e5-84ef-c8420545bf28.png)
