### ISSUE TITLE
List partner and last studios in mobile

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#227]
Find why it's working sometimes and sometimes not.

* [x] Remove class <em> for label tag
* [x] and add colors
* [x] better Placeholder or studios with photos only

**Comment by M4rtine** [comment]
![227_list_studios](https://cloud.githubusercontent.com/assets/6338568/8905685/a031d0de-3468-11e5-8a99-067e69fca929.jpg)

**Comment by foutoucour** [comment]
Fixed so only partners with logo are promoted to the frontpage

![e_20150728_001](https://cloud.githubusercontent.com/assets/547282/8947365/26131c58-3568-11e5-8b1f-692c4ffe5058.png)

**Comment by M4rtine** [comment]
Big fix
Waiting pull request

![227_list_partner_00](https://cloud.githubusercontent.com/assets/6338568/9570174/7d754316-4f82-11e5-8192-d72298ba0897.jpg)
![227_list_partner_01](https://cloud.githubusercontent.com/assets/6338568/9570175/833f8a7c-4f82-11e5-98b6-fcfcea9822c0.jpg)
![227_list_partner_02](https://cloud.githubusercontent.com/assets/6338568/9570176/8a2263be-4f82-11e5-9348-67c3c581138d.jpg)

**Comment by M4rtine** [comment]
@foutoucour i believe this issue is solved. 
i let you close or explain me why it's open ?
