### ISSUE TITLE
Siggraph logo

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#237]
i can't upload a new file. Do you make it for me ?
Upload logo in
/main/local_modules/main_data/static/src/img/

in branch #236

LOGO is here but in white and transparent (bottom)

![s15_wlogo_l](https://cloud.githubusercontent.com/assets/6338568/9006430/6836acf0-3787-11e5-95e5-96dfc182ec4b.png)

**Comment by foutoucour** [comment]
doe in #238
