### ISSUE TITLE
List and rate job boards

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#239]
The survey shows that people are mainly interested in having a resource of job on the website.

Before to make the move, it would be interesting to know what are the main job board already out there, and to understand their business model.
Do they bill the job seeker? Do they bill the company? etc.

Job board that I know:
* Indeed
* glassdoor
* linkedin
* artjobconnection (http://www.artjobsconnection.com/)
* creative heads
* cgjobs (http://www.cgjobs.eu/)
* jobijoba (http://www.jobijoba.com/fr/)
* cgsociety (http://jobs.cgsociety.org/)

**Comment by MangoJazz** [comment]
How do they make money?

Business Model ($):

Online job posting
Talents tools & career advices
Resumes review & update
Business solutions advices, ROI
Online boutique
Advertising on demand
Referencing
Analytics reports on demand
Database full & complete
VIP Membership for jobseeker profile
Membership for employer profile

**Comment by foutoucour** [comment]
I like the online boutique, VIP membership and the reports.
