### ISSUE TITLE
Add studios/companies from the SIGGRAPH2015 list

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#240]
http://sis.siggraph.org/cgi-bin/procform?&SESS=usV4yYHRIXrcnXaAXkJoY4WFJn21id%2BSWjnTCVm6yfdJ7R/Ooa0H0e7HrQfRW45we/ndX84XP38szDrC8BRVic2ryM5v/qyYCJcYcwmJCsX9RKvx2pUG9H6T6KSqAH%2BF&preparsed=1

**Comment by M4rtine** [comment]
What do you say with this link ?

--

**Comment by MangoJazz** [comment]
Sorry, it is the link where I can find the companies coming to the Siggraph 2015. It is for me to add them in.
