### ISSUE TITLE
Page opening in a new window/tab

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#241]
Could you try to make a page opening in a new tab when clicking on a studio?

It was a recurrent request from the survey.

Tx

**Comment by M4rtine** [comment]
´´´ 
<a t-attf-href="/web#return_label=Website&amp;view_type=form&amp;model=#{partner._name}&amp;id=#{partner.id}&amp;action=#{action}" target="_blank">
´´´ 
Is it the right xml method?

**Comment by foutoucour** [comment]
problème résolut avec le passage en frontend
