### ISSUE TITLE
Missing DOCTYPE

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#243]
Ref to #242 

Perhaps it's not easy to add `<!DOCTYPE html>` in XML files

@foutoucour Do you say me what is the correct method to add this type of code ?

**Comment by foutoucour** [comment]
Done in #248

**Comment by foutoucour** [comment]
it was pretty easy actually. The issue came from the custom template we made for the homepage and the event.

The trick was to add the tag using `&lt;!DOCTYPE html&gt;` instead of `<!DOCTYPE html>`.

For other pages are generated with the tag by odoo (see the page about for example).
