### ISSUE TITLE
Blog post: Result of the survey

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#250]
Create a blog post that summaries the results of the survey.

Keep in mind that all the people that answered the surveys did sign-up of the website. That might be bias the result on some points.

**Comment by MangoJazz** [comment]
I don't think it is agood idea. These info are relevant to cgstudiomap not
the users.

Plus you need the infos for the business plan, not a blog page.

Le mercredi 5 août 2015, Jordi Riera <notifications@github.com> a écrit :

> Create a blog post that summaries the results of the survey.
>
> Keep in mind that all the people that answered the surveys did sign-up of
> the website. That might be bias the result on some points.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/250>.
>


-- 


Edith Courtial
T: +1 438 875 7220

<http://ca.linkedin.com/in/edithcourtial/>
