### ISSUE TITLE
Open website to public user

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#252]
Public User, the user used when a someone not logged browse the website, should be able to go to the portal and browse cards.

* The cards should be light and not display all the details of the company.
* Public User should not be able to create anything

**Comment by foutoucour** [comment]
Due to the internal system of login of odoo, public user can't have access to the backoffice. That mean we have to promote the card to the front office somehow.

**Comment by foutoucour** [comment]
hey @M4rtine 

I am working to get a solution to expose the information of companies to public user. 
I built 2 pages: a listing and a card.

![0_20150822_001](https://cloud.githubusercontent.com/assets/547282/9426332/7bb528c4-4907-11e5-9809-d7554bdbec0c.png)


![6_20150822_001](https://cloud.githubusercontent.com/assets/547282/9426333/80b1271a-4907-11e5-97dd-023d316b7bc8.png)

would you have time to take a look at it?
You will find the code in the branch 252-public_user

**Comment by foutoucour** [comment]
I will add features to get the user to login soon:
- in the listing, I will suggest to log in to have access to other style of listing (map, listing)
- in the card, I will suggest to log in for more details, most likely by exposing more fields and I would replace the value by "login to see the detail."

@juli1r @MangoJazz @M4rtine, what do you think?

**Comment by foutoucour** [comment]
The pages will help google to find us and will ease sharing of our pages on social networks

**Comment by M4rtine** [comment]
Ok but i can't work before the 30th :(
I will look better your job tomorow

Le dimanche 23 août 2015, Jordi Riera <notifications@github.com> a écrit :

> The pages will help google to find us and will ease sharing of our pages
> on social networks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/252#issuecomment-133766380>
> .
>


--

**Comment by foutoucour** [comment]
Ok let's wait for after you can work again on the project. I will make some improvements in the meanwhile. 

Let me know.

**Comment by foutoucour** [comment]
update of the pages:

![1_20150823_001](https://cloud.githubusercontent.com/assets/547282/9431375/c564446a-49dd-11e5-8057-fbfd5527426e.png)
![c_20150823_001](https://cloud.githubusercontent.com/assets/547282/9431376/c8302eb6-49dd-11e5-8bd3-8780da0de933.png)

needs to
* [ ] make the sign up sentence in directory conditional
* [ ] make a menu to expose the new pages


@M4rtine to have access to the pages go to /directory or /directory/company/3 (or any other company id)

**Comment by juli1r** [comment]
I love both ideas.

What fields do you plan to hide for the card?

**Comment by M4rtine** [comment]
thanks @foutoucour

**Comment by M4rtine** [comment]
i think it's time to get a better images resolution for the company logo.
i could increase this page and also the listing in homepage. it's the same issue for me.

**Comment by foutoucour** [comment]
Implemented isotope and bootstrap table to add a kanban page and a list page:

![a_20150907_001](https://cloud.githubusercontent.com/assets/547282/9724181/2c92c372-55a1-11e5-8699-2c4f34ade451.png)
![c_20150907_001](https://cloud.githubusercontent.com/assets/547282/9724182/2c97fe1e-55a1-11e5-80f1-4e17c2f6fe60.png)

@M4rtine forgive me for my skills in design :) Remind me what size of the image you would need for the logos?

**Comment by M4rtine** [comment]
Don't worry it is enough for me ;)
Size logo must be more than the seeing use.

I think the Twitter size preset is a good start.


--

**Comment by foutoucour** [comment]
@M4rtine be careful, I rebased the branch. You should pull the code before to work on it.

**Comment by M4rtine** [comment]
Here is the new fresh 2016 design.
Iconography is not definitive and soon it will be a new design issue (only for icons)

HERE animated prototypes :
https://marvelapp.com/6jj17a

![cgsm-webdesign-2015-03](https://cloud.githubusercontent.com/assets/6338568/11454007/edb104e2-961f-11e5-8255-7ca468a9a06d.jpg)

![cgsm-webdesign-2015-08](https://cloud.githubusercontent.com/assets/6338568/11454018/0b0b914c-9620-11e5-9036-7fa3ebbbbc79.jpg)

![cgsm-webdesign-2015-04](https://cloud.githubusercontent.com/assets/6338568/11454009/edb4764a-961f-11e5-82d1-e52c6625d387.jpg)

![cgsm-webdesign-2015-05](https://cloud.githubusercontent.com/assets/6338568/11454008/edb4200a-961f-11e5-866a-27efe84b57f5.jpg)

![cgsm-webdesign-2015-06](https://cloud.githubusercontent.com/assets/6338568/11454010/edbb7d46-961f-11e5-8c26-7c70b8a0f842.jpg)

![cgsm-webdesign-2015-07](https://cloud.githubusercontent.com/assets/6338568/11454011/edbef8c2-961f-11e5-8ea2-a9505d114305.jpg)

**Comment by foutoucour** [comment]
The work done so far will be released by disabled.

This will avoid us to have a long living branch that is behind our living code base. It doesn't change anything but please report any strange behavior that would experience.

The next steps will be split to smaller issues to ease the follow up and the workload management.
