### ISSUE TITLE
Image for twitter posts

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#254]
Need to update the image referenced in `<meta name="twitter:image" content="http://graphics8.nytimes.com/images/2012/02/19/us/19whitney-span/19whitney-span-articleLarge.jpg"/>`

check this tweet: twitter: https://twitter.com/dipmedia/status/636300733831
Currently we have a picture about Whitney Houston :)

The picture is referenced in:
* frontend/templates/homepage.xml
* frontend/templates/events.xml
* frontend/templates/web_layout.xml

**Comment by M4rtine** [comment]
Withney Houston is a better logo ^^

Le jeudi 27 août 2015, Jordi Riera <notifications@github.com> a écrit :

> Assigned #254 <https://github.com/cgstudiomap/cgstudiomap/issues/254> to
> @M4rtine <https://github.com/M4rtine>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/254#event-393450651>.
>


--

**Comment by M4rtine** [comment]
my bad this  picture is the twitter code example

**Comment by M4rtine** [comment]
Pul request #263

**Comment by foutoucour** [comment]
released
