### ISSUE TITLE
Homepage: design of the page when user logged 

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#258]

**Comment by M4rtine** [comment]
Templates ZONING 

Let me know if it is bright

![templating_backoffice_login](https://cloud.githubusercontent.com/assets/6338568/11258299/3693ddd0-8e58-11e5-91a0-9cb5edbbf77a.jpg)
![templating_backoffice_directory1](https://cloud.githubusercontent.com/assets/6338568/11258303/3d14da24-8e58-11e5-88c4-7e8fa7a459fa.jpg)
![templating_backoffice_directory2](https://cloud.githubusercontent.com/assets/6338568/11258307/42b814d2-8e58-11e5-9094-91dde334c86a.jpg)

**Comment by foutoucour** [comment]
I think you wanted to post on #252, no?

The template we are talking about here is to have a different homepage for when the user is logged. The homepage for the logged user should focus on describing what happened on the website (update of card, new software, new movie etc..) instead of describing the project itself.

The user already logged, so he knows us ;)
Do you want me to transfer the image?
