### ISSUE TITLE
Homepage: different page for user logged

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#260]
The survey revealed 2 trends: people want find a job and companies want to be found.

With what we have we can already try to give more exposure to companies.
For that, we will make a new homepage for user that are already logged, inspired from linkedin first page.

The page will be a endless page with the updates about creation and edition of companies. The aim is make it easy for user to see the last updates on the website. It will also create traction of users as they will want to see the last updates.
We also want as side effect to attract companies and force them to be active on the website.

As usual 2 tasks for the new page:
- [ ] development: #259
- [ ] design: #258

**Comment by MangoJazz** [comment]
@foutoucour cette tache n'a plus lieu? Elle devrait etre fermée, car on a tous la meme page inscrit ou non.

**Comment by foutoucour** [comment]
won't do
