### ISSUE TITLE
Shout to twitter when a new company is created

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#262]
Send a tweet each time a new company is created on the website.

The tweet should have:
* [ ] link to the public page of the company
* [ ] mention of the twitter account if informed
* [ ] hashtags
* [ ] the tweet should be sent 3 times in the day with 8h of delay, so the tweet will be seen in each timezones

**Comment by MangoJazz** [comment]
Pour l'instant je le fais moi-meme, il n'y a pas tant de compagnies que ça pour creer un robot. C'est mon avis. Au moins je personnalise chaque tweet.

**Comment by foutoucour** [comment]
Won't do. Le bot slack est suffisant pour le moment
