### ISSUE TITLE
Check business model of online directory

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#264]
- Yellow page
- Yelp
- White page

**Comment by MangoJazz** [comment]
Yelp
Yellow Pages

Business Model ($)

Free registration
Social network accounts created by Y (monthly payments)
Web site created by Y (monthly payments)
Professional video (1 payment)
Professional photos (1 payment)
Position prioritized on Y (monthly payments)
SEO (monthly payments)
Advertising targeted (monthly payments)
Analytic reports (1 payment)
Designed Account Manager (monthly payments)

**Comment by foutoucour** [comment]
Designed Account Manager is a great lead for me.
