### ISSUE TITLE
Geo Charts responsive

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#268]
i found a tip for make responsive geo charts.

http://codepen.io/chrisgosling/pen/jLefu

Do you think is it easy ?

**Comment by foutoucour** [comment]
Salut,

Non ca semble facile a mettre en place.

On Tue, Sep 15, 2015 at 6:15 AM David Mazeau <notifications@github.com>
wrote:

> Assigned #268 <https://github.com/cgstudiomap/cgstudiomap/issues/268> to
> @foutoucour <https://github.com/foutoucour>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/268#event-409627154>.
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
Cool

**Comment by foutoucour** [comment]
It is way more complicated that expected. Will see that later on.

**Comment by M4rtine** [comment]
i think with our new methods (own templates and bootstrap) we have a better result.

**Comment by M4rtine** [comment]
Google say Responsive geochart is not possible because its not 1st idea. But there is a solution with reDraw option when the screen size change.
It's work perfectly.
Done

**Comment by foutoucour** [comment]
J'ai l'impression que c'est bugge sur ipad. tu peux essayer?

Dans mon cas ca bug si:
- charger la page en mode paysage
- scroller dans la page
- revenir en haut de la page 
- "trop" scroller ce qui va recharger la page il me semble.

La carte disparait alors

**Comment by M4rtine** [comment]
ouaip je l'ai aussi. Pas de solution pour le moment.
Il considère le mouvement du scroll en touché comme un resize. Je vais chercher

**Comment by foutoucour** [comment]
@M4rtine, tu as resolu cette tache dans une autre je pense non?

**Comment by M4rtine** [comment]
le responsive oui mais pas le touch quand on scroll

**Comment by M4rtine** [comment]
Je close et j'écris mieux l'issue en BackLog
