### ISSUE TITLE
Canadian studios enhancement

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#270]
To go over all canadian studios to add missing parts

**Comment by MangoJazz** [comment]
- Montreal ok

**Comment by MangoJazz** [comment]
Toronto ok

**Comment by MangoJazz** [comment]
Vancouver ok

**Comment by MangoJazz** [comment]
yeah tout le Canada est passé au peigne fin :).
Je m'attaque à la France

**Comment by foutoucour** [comment]
:clap:
