### ISSUE TITLE
Business plan: open data

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#271]
Related to #204 

I would like cgstudiomap to be an open data for the industry. But we need, to stay in long term, to be able to get some money of it. I am not talking about getting rich but at least to have some returns for our efforts.

@MangoJazz: Please take a look at what are the business plan related to open data platform.

Here some article interesting:
* https://en.wikipedia.org/wiki/Open_data
* https://en.wikipedia.org/wiki/Application_programming_interface
* https://en.wikipedia.org/wiki/Open_source
* https://en.wikipedia.org/wiki/Free_software

**Comment by MangoJazz** [comment]
Done on cgstudiomap drive.
