### ISSUE TITLE
Tweet Tweet Tweet

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#274]
Let's make some noises :)

**Comment by M4rtine** [comment]
oh yeah baby ^^

**Comment by MangoJazz** [comment]
2 inscrits de plus avec le tweet de ce matin. c'est bon ça motive :-)

Edith Courtial
T: +1 438 875 7220

<http://ca.linkedin.com/in/edithcourtial/>

2015-10-16 9:52 GMT-04:00 Jordi Riera <notifications@github.com>:

**Comment by MangoJazz** [comment]
711 followers on twitter :)
1 article about the old version reviewed/ updated on the web
1 article found from August 2015 about us
2691 users in cg Studio Map

We need to get lot of traffic.

**Comment by M4rtine** [comment]
https://twitter.com/davidmazeau/status/663317677826514944

**Comment by M4rtine** [comment]
If goodies make money, first, we can pay Twitter to make a sponsors ?

**Comment by MangoJazz** [comment]
oh wow it is a very good idea.
Noted ;)

Edith Courtial
T: +1 438 875 7220

<http://ca.linkedin.com/in/edithcourtial/>

2015-11-08 6:40 GMT-05:00 David Mazeau <notifications@github.com>:

**Comment by MangoJazz** [comment]
1 tweet with our website link, 5 new followers on twitters & 5 new happy users.
So I believe we should continue with Twitter interaction.

**Comment by MangoJazz** [comment]
I will close this issue, it is an ongoing thing.
