### ISSUE TITLE
Goodies

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#286]
(width - height)
- Phone Case 1300px - 2000px
- T-Shirts / V-Necks / Tank Tops / Long Sleeve Biker Tanks / Hoodies 3300px - 5100px (PNG with alpha transparency)
- Wall Clock 6500px - 6500px
- Mug 4600px - 2000px
- Laptop & iPad Skins / iPad mini Cases / Laptop Sleeves 4600px - 3000px
- Wall Tapestries / Throw Blankets 6500px - 5525px (horizontal view)
- Travel Mugs 2697px - 1518px

**Comment by M4rtine** [comment]
Here an example of tests i make ;)
https://society6.com/m4rtine

**Comment by MangoJazz** [comment]
Mug, shirt and phone case looks good.

**Comment by M4rtine** [comment]
Agreed ! i made a template for all so it's allready done ;)

**Comment by MangoJazz** [comment]
Cool could we see the template with cg Studio Map?
I only see with a red logo.

**Comment by M4rtine** [comment]
of course i do with CG Studio Map but this link is my works so the "Red Logo" is not a logo. It's a minimalist art of the computer of "2001: A space Odyssey"

We must create an official account with a paypal account too.

**Comment by foutoucour** [comment]
I will do it this week end: see #287

**Comment by M4rtine** [comment]
perfect

**Comment by foutoucour** [comment]
Account created.

**Comment by M4rtine** [comment]
we can't have products not published. So to prevent mistakes I will do the same like my personal society6 page.
we must think about many catch sentence with more personal impact. For example "I am a contributor" "I'm in" 
or it's a bad idea and we only put "where cg is"

what do you think ?

**Comment by M4rtine** [comment]
we can have more choice about clothes because I have think the logo in many way.
black background, white background

I make mug with white background, it's more readable but I must re-think the design for all the way round.

**Comment by M4rtine** [comment]
phone case is the best choice with many colors and the logo in middle bottom

**Comment by MangoJazz** [comment]
I would say just the logo and the name would be good.
If you really want a sentence then it should be the same everywhere
"Where cg is"



Edith




2015-11-07 14:34 GMT-05:00 David Mazeau <notifications@github.com>:

**Comment by M4rtine** [comment]
Frame Art : 
![20151107-cgsm-logo-frame](https://cloud.githubusercontent.com/assets/6338568/11020802/3d806a52-862c-11e5-86d2-eaf63089de70.jpg)

**Comment by M4rtine** [comment]
T-SHIRT (and others...) with transparency for many colors in background : 
![20151107-cgsm-logo-teeshirt](https://cloud.githubusercontent.com/assets/6338568/11020848/d073f2ce-862d-11e5-9684-539c359a27c2.jpg)

**Comment by M4rtine** [comment]
Mug and Travel Mug : 
![20151107-cgsm-logo-mug](https://cloud.githubusercontent.com/assets/6338568/11020855/06cecfce-862e-11e5-8fc4-3b92a706a6c1.jpg)

**Comment by M4rtine** [comment]
Phone Case : 
![20151107-cgsm-logo-phonecase](https://cloud.githubusercontent.com/assets/6338568/11020892/7b908784-862f-11e5-880c-bbe15c35850e.jpg)

**Comment by M4rtine** [comment]
waiting for your opinion

**Comment by foutoucour** [comment]
Love it. Specially the phone case with 3 tones, purple, white and black.
What is the frame art for?

On Sun, Nov 8, 2015 at 9:46 AM David Mazeau <notifications@github.com>
wrote:

> waiting for your opinion
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/286#issuecomment-154830778>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by MangoJazz** [comment]
Love the phone case and the mug.

T-Shirt: I would add the purple because just grey and white is too sad to
vehicul the image.

Frame art: ? poster / tableau / ou la base?

Edith

2015-11-08 18:44 GMT-05:00 Jordi Riera <notifications@github.com>:

**Comment by M4rtine** [comment]
Frame art is poster and all print. Society6 unlock other products with that.

T-shirt and cloths are colorfull. Only logo is white 
We must choose colors together

**Comment by MangoJazz** [comment]
Okay thanks

I will buy a mug and a phone case for me for sure ;)

**Comment by M4rtine** [comment]
Mug :
 https://society6.com/product/cg-studio-map_mug
![25585679_9241543-mugs11f_l](https://cloud.githubusercontent.com/assets/6338568/11165688/a4f699ec-8b16-11e5-8eca-dfaae98bc1b2.jpg)

**Comment by M4rtine** [comment]
SmartPhone Case :
 https://society6.com/product/cg-studio-map_iphone-case

![smartphone_case](https://cloud.githubusercontent.com/assets/6338568/11165721/0d4aba68-8b18-11e5-9119-a4e6b3f58aa5.jpg)

**Comment by foutoucour** [comment]
Great work.

@MangoJazz will work on promoting them. I will buy the mug, the hoodie and a t-shirt and make some photos of them once here.
