### ISSUE TITLE
Jobs website links

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#288]
Hey guys,

Let me know what you think about this.

If cg Studio Map is where cg is, then wouldn't be great to have a page where we would have links to (good) websites that posts jobs opening in cg?
It will create some traffic to our website no?

**Comment by M4rtine** [comment]
It's a good idea but I think we can see larger. 
A cg resources pages simply.

**Comment by MangoJazz** [comment]
yes resources with links you mean? It is what we want in the end with the
moto "where cg is".

Or a page that we (as cg studio map team) we would update constantly with
posts, news, jobs...? Because this is too much intense work!

Edith Courtial
T: +1 438 875 7220

<http://ca.linkedin.com/in/edithcourtial/>

2015-11-08 6:12 GMT-05:00 David Mazeau <notifications@github.com>:

**Comment by MangoJazz** [comment]
A cg ressources page then it will be.

Let's discuss this next meeting. @foutoucour could you please add it to the meeting memo?
