### ISSUE TITLE
Own this business button

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#289]
Could we add a button a"own this business" button on each profile.
![screen shot 2015-11-07 at 5 33 18 pm](https://cloud.githubusercontent.com/assets/13125734/11017703/d047bbfe-8575-11e5-8d01-001bffb1d788.png)

That way when the button disappear, we know that that business itself took ownership of his card, and it will be accurate for sure.

**Comment by M4rtine** [comment]
Sound good.
How do we verify that?

**Comment by M4rtine** [comment]
Do you think this option is in business model ?

**Comment by MangoJazz** [comment]
Jordi said that unfortunately it would go against the community since if the business own his card, no one from the public would be able to update, edit or revise a card.
It is a good point, sorry it was a bad idea :(.
