### ISSUE TITLE
Stars review

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#290]
I like the option to leave a review for each business, since our users are 80% job hunters, it could guide them where to go or where not to go.
![4stars](https://cloud.githubusercontent.com/assets/13125734/11017710/36b0807e-8576-11e5-921c-a322cd25663c.jpg)

Would that be something worth talking about?

**Comment by M4rtine** [comment]
I don't think it s a good idea. Community is around the data the information not around judgment.
Besides we know how community react when he has the choice.

**Comment by MangoJazz** [comment]
I am afraid I am not following your point.

Rating, reviews and comments are great information for someone looking for
a studio to work there. We all want to know the opinion or experience of
the other before trying something new.
As a community, cg Studio Map already allows the public to edit, add,
revise...our info/cards/studios in cg Studio Map. So they already have the
choice to do good or bad with the website. So far only one guy used the
site to add his CV in each studios. Nearly 3000 happy users and only 1 bad
user profit from the website weakness.


I think we should discuss more the right & wrong about this "rating"option.

What do you say?

Edith Courtial
T: +1 438 875 7220

<http://ca.linkedin.com/in/edithcourtial/>

2015-11-08 2:36 GMT-05:00 David Mazeau <notifications@github.com>:

**Comment by M4rtine** [comment]
I understand your point of view and I 'll like to discuss about that.

**Comment by foutoucour** [comment]
Meeting to talk about the project philosophy scheduled the 21st November.

On Mon, Nov 9, 2015, 5:05 AM David Mazeau <notifications@github.com> wrote:

> I understand your point of view and I 'll like to discuss about that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/290#issuecomment-155017534>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by MangoJazz** [comment]
good talk on saturday. I am closing this request.
Thank you for your thoughts :)
We will go the other way as you mentioned.
