### ISSUE TITLE
2015 Graphical Identity

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#292]
![cgsm-graphic-identity-2015-01](https://cloud.githubusercontent.com/assets/6338568/11020877/b3836e64-862e-11e5-94db-1aea2c39d7ce.jpg)
![cgsm-graphic-identity-2015-02](https://cloud.githubusercontent.com/assets/6338568/11020878/b73b5738-862e-11e5-9af4-4ede66d1b907.jpg)
![cgsm-graphic-identity-2015-03](https://cloud.githubusercontent.com/assets/6338568/11020879/bb028df0-862e-11e5-9819-0851c15468f3.jpg)
![cgsm-graphic-identity-2015-04](https://cloud.githubusercontent.com/assets/6338568/11020880/bea940e8-862e-11e5-90e5-7fd7687e33d4.jpg)

**Comment by foutoucour** [comment]
The numbers in counter might be too small if it is to be used on the map.
will see in the context tho.

On Sun, Nov 8, 2015 at 9:38 AM David Mazeau <notifications@github.com>
wrote:

> [image: cgsm-graphic-identity-2015-01]
> <https://cloud.githubusercontent.com/assets/6338568/11020877/b3836e64-862e-11e5-94db-1aea2c39d7ce.jpg>
> [image: cgsm-graphic-identity-2015-02]
> <https://cloud.githubusercontent.com/assets/6338568/11020878/b73b5738-862e-11e5-9af4-4ede66d1b907.jpg>
> [image: cgsm-graphic-identity-2015-03]
> <https://cloud.githubusercontent.com/assets/6338568/11020879/bb028df0-862e-11e5-9819-0851c15468f3.jpg>
> [image: cgsm-graphic-identity-2015-04]
> <https://cloud.githubusercontent.com/assets/6338568/11020880/bea940e8-862e-11e5-90e5-7fd7687e33d4.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/292>.
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
agreed

**Comment by M4rtine** [comment]
For numbers in map we choose a simple but efficient method.
A circle and a number like that.

- more readable
- more upgradable
- working timeless
![292-issue-numbers-studios](https://cloud.githubusercontent.com/assets/6338568/11527402/0d19995c-98e1-11e5-8760-09bd6baffe4b.jpg)

**Comment by M4rtine** [comment]
Pattern Background :

![cgsm-graphic-identity-2015-pattern](https://cloud.githubusercontent.com/assets/6338568/11527936/157dd6fa-98e4-11e5-8b5c-fa9694dad3e3.jpg)
