### ISSUE TITLE
Update of the address of companies

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#300]
Some of the companies of the listing were implemented before the validation against google for the address details.

need to run a script on the database to trigger google. To trigger the check of google, we just need to update one of this fields: street, zip, city, country_id
To avoid to screw the data, we just add a space to the zip. Google will fix the zip code during the validation.

script to run in python-odoo:
```javascript
import datetime
pp = session.registry('res.partner')
today = datetime.date.today()
yesterday = (today - datetime.timedelta(2)).strftime('%Y-%m-%d')

pps = pp.search(session.cr, 1, [('city', '!=', False), ('is_company', '=', True), ('write_date', '<', yesterday)], order='write_date')
for p in pps:
    p = pp.browse(session.cr, 1, p)
    print p, p.name, p.city
    try:
        p.write({'zip': '{0} '.format(p.zip)})
    except:
        print p, p.name, '--> NOT UPDATED'
        pass
```

To run the script, the instance has to be shut down to avoid to have the database blocked by another transaction.

TODO:
* [x] Run script to update locations.
* [x] set state to readonly (#306)
* [x] fix the error about several states found during location validation. (#306)
* [x] Write a script to remove duplicated state
* [x] check the companies that weren't updated

**Comment by foutoucour** [comment]
Related to this.
Strangely, currently we have several time a state with the same code/name. That make the location validation raises an error. To fix that, we limit the search of state to 1 in the process of location validation.
Additionally state is set to read only in the company's view for portal users.

**Comment by foutoucour** [comment]
* [ ] Write a script to remove duplicated state

**Comment by foutoucour** [comment]
All the companies were updated.
Only the following companies could not have been updated:
 ids = [1300, 1453, 2903, 3335, 3672, 5291]

Need to check them to solve why the update didn't work.

**Comment by MangoJazz** [comment]
Ids checked & verified

1300: address + email wrong - now updated
1453: address + email wrong - now updated
2903: For some reasons the postal code is not recognized (Beirut)
3335: For some reasons the postal code is not recognized (Algeria)
3672: All good
5291: All good

It doesn't seem like there is a pattern or a commune point between those
studios, I am not able to tell you why the update didn't work. Now that
there has been a change in their card, could you try a new update and let
us know?

Thanks




2015-11-22 13:57 GMT-05:00 Jordi Riera <notifications@github.com>:
