### ISSUE TITLE
Templating imbrication

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#301]
1st Proposal  :
![templating](https://cloud.githubusercontent.com/assets/6338568/11164580/0f3906ae-8af5-11e5-828e-d0c7cb16bde0.jpg)

![structure_files](https://cloud.githubusercontent.com/assets/6338568/11164662/0025b43a-8af7-11e5-97dd-fad3c72325a7.jpg)

* [ ] build frontend_base with HEAD BODY ENGINE CLOSE features #318
* [ ] build frontend_homepage with new skeleton. #319

**Comment by foutoucour** [comment]
Odoo works with modules and we should try to follow the philosophy to avoid to have headaches later.

I would suggest to gather template families into modules.
`frontend` will be the key work for module about the front-office and back-office.
* `frontend_base` will be the module with the skeleton of our page.
* `frontend_homepage`
* `frontend_listing` (listing under map, list forms)
* `frontend_company_form` (module about the company form), 
* `frontend_company_form_edit` (backoffice of the company form)

Each module would have specific CSS, JS etc for each page.

What do you think? 
We need to avoid to overcomplicated the structure that would slow us, but also to keep module little and easy to understand what they are for.

Jordi

**Comment by foutoucour** [comment]
* [ ] build frontend_base with HEAD BODY ENGINE CLOSE features
* [ ] build frontend_homepage with new skeleton.

**Comment by foutoucour** [comment]
The principle for the skeleton has been implemented.

There are 4 series of template grouped in files in module frontend_base:
* [template_body](https://github.com/cgstudiomap/cgstudiomap/blob/develop/main/local_modules/frontend_base/templates/template_body.xml): with basic templates to build the body of the page
* [template_engine](https://github.com/cgstudiomap/cgstudiomap/blob/develop/main/local_modules/frontend_base/templates/template_engine.xml): with basic templates to build the engine of the page
* [template_head](https://github.com/cgstudiomap/cgstudiomap/blob/develop/main/local_modules/frontend_base/templates/template_head.xml): with templates to build the head of the page
* [template_html](https://github.com/cgstudiomap/cgstudiomap/blob/develop/main/local_modules/frontend_base/templates/template_html.xml): just 2 templates to build the DOCTYPE and the html tag.

The [homepage](https://github.com/cgstudiomap/cgstudiomap/blob/develop/main/local_modules/frontend/templates/homepage.xml) has been updated with the new sub templates.

let me know what do you think.

**Comment by foutoucour** [comment]
Une page wiki a ete mise en place pour expliquer la philosophie et comment utiliser les templates: https://github.com/cgstudiomap/cgstudiomap/wiki/template-guide
