### ISSUE TITLE
update home page

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#307]
'support us'
- [x] could you please take off this sentence: Together, let’s create a MOVEMENT!
- [x] could you please add as well the link to the shop: Support the project here!

thanks

**Comment by foutoucour** [comment]
![7_20151116_001](https://cloud.githubusercontent.com/assets/547282/11198792/c1b35392-8c95-11e5-8921-dd8f3c1e9f17.png)

Fixed in #308
