### ISSUE TITLE
Text pour l'Eblast user

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#310]
Elabst pour annoncer le public beta aux utilisateurs avec questions ouvertes afin de nous diriger vers les prochaines features.

**Comment by MangoJazz** [comment]
One eblast wishes 2016 is ready for users & one for businesses. 
We would need to check them all of us, and we would need to add  a nice design/image.

**Comment by MangoJazz** [comment]
Eblast Users - Annonce cg Studio Map public
il est pret à partir, il faut surement y ajouter notre logo.
En parler au prochain meeting.

Par la suite j'enverrai un autre email demandant de participer au beta testing.

**Comment by foutoucour** [comment]
Liens vers la template mailchimp stp

**Comment by MangoJazz** [comment]
@foutoucour 
Il me semble que David voulait creer une template dans laquelle je rajouterais du texte. 
Mais la voici sous google doc:
https://docs.google.com/document/d/1HCaxfBe7XCO3jePmJnojVAoRjD_1fy2BbBZqFfMNP40/edit

**Comment by MangoJazz** [comment]
A revoir lorsque ce sera pret.

**Comment by M4rtine** [comment]
Je suis perdu c'est pour Mailchimp ca ?
Si oui c nickel j'ai juste corriger des détails de formatage visuel
directement dans Mailchimp

Sinon je regarderai ce soir


--

**Comment by MangoJazz** [comment]
oui c'est une ancienne tâche. C'est pour la release, la grosse release. J'utiliserai la template que tu as crée. Merci, par contre avec celle que je viens d'envoyer, tout le texte reste en gras, je ne peux rien y changer dans la template. Peux-tu regarder cela?

**Comment by M4rtine** [comment]
Normalement hier soir je l'ai corrigé
Sinon pour l'enlever il faut sélectionner le texte problématique et tu clic
sur "supprimer le formatage"

Le copié-collé depuis Word doit être compliqué


--

**Comment by MangoJazz** [comment]
@foutoucour  Reouvre la tache SVp c'est pour la semaine prochaine.
