### ISSUE TITLE
linkedin company error

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#316]
bug validation account linkedin

case example : 
PixelMob 
ID:1973
https://www.linkedin.com/company/pixelmob

**Comment by MangoJazz** [comment]
Hello,

I have just added the LinkedIn link, it is saved.
PixelMob
ID:1973
http://www.cgstudiomap.org/web?#id=1973&view_type=form&model=res.partner&menu_id=353&action=418

Thank you,



2015-11-23 11:18 GMT-05:00 David Mazeau <notifications@github.com>:

**Comment by M4rtine** [comment]
Do you know the reason of this error ? Because we put the same link
Just a server LAG ?

**Comment by MangoJazz** [comment]
I don't know sorry :(.

I have reported it to Jordi few times. It happen a lot with social networks
links.
