### ISSUE TITLE
logo organization/website

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#32]
Set up the new logo of the organization/website.
The logo will be used as a communication tool for emails, social network accounts but also as the logo/favicon on the website.

Following the guide lines from the picture, the logo should be:
* symbolic
* minimalist
* no letter or name
Example of logo we want to follow the philosophy would be twitter, github

Refer to the picture for more details.

![fullsizerender](https://cloud.githubusercontent.com/assets/547282/7182148/82537554-e41d-11e4-95bb-9e0e07460e86.jpg)

**Comment by M4rtine** [comment]
For responsive height
https://github.com/ChimpStudios/AmCharts/tree/master/AmChartsWeb/ammap/plugins/responsive

**Comment by foutoucour** [comment]
Study about fonts:

![Uploading cgsm-graphic-identity-wip-01.jpg . . .]()

**Comment by foutoucour** [comment]
We are now considering 1st (pretty classic but do the job) or the 3rd (a bit more sexy but still pro)

**Comment by foutoucour** [comment]
Study about colors on the map:
![cgsm-graphic-identity-wip-05](https://cloud.githubusercontent.com/assets/547282/7311278/30019bd2-ea08-11e4-8083-5f222a7865f7.jpg)

Explanations about Colors:
* CG: GUI Elements on top of map, main color for front-end, color of the logo
* Map: color of the map + reports about the map
* Studio: Color of the back end, reports about studios

**Comment by foutoucour** [comment]
Study about the logo
![cgsm-graphic-identity-wip-02](https://cloud.githubusercontent.com/assets/547282/7311306/c18bbca4-ea08-11e4-9cfe-a65091be0007.jpg)

**Comment by foutoucour** [comment]
![cgsm-graphic-identity-wip-03 1](https://cloud.githubusercontent.com/assets/547282/7311316/e57d7b48-ea08-11e4-9ffe-f1b73bbc84e2.jpg)

**Comment by foutoucour** [comment]
![cgsm-graphic-identity-wip-04](https://cloud.githubusercontent.com/assets/547282/7311317/f14e34a8-ea08-11e4-872a-892c0dcada62.jpg)

**Comment by M4rtine** [comment]
i think the 3rd is the best.
"cg" un lowercase
and icon logo un purple and catchphrase ni blue. (logo is more apparent.)

**Comment by M4rtine** [comment]
cg in lowercase show what is important : Studio Map

**Comment by foutoucour** [comment]
Logo wise, I prefer the first attempt. I find the second harder to read actually.

The logo will be in purple right?

**Comment by M4rtine** [comment]
The First had more impact
![cgsm-graphic-identity-wip-06](https://cloud.githubusercontent.com/assets/6338568/7343878/fc1690f4-ecc6-11e4-996e-9202b7388c01.jpg)
