### ISSUE TITLE
Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#328]
Your page has 5 blocking CSS resources. This causes a delay in rendering your page.
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.
Optimize CSS Delivery of the following:

    http://www.cgstudiomap.org/…tic/lib/fontawesome/css/font-awesome.css
    http://www.cgstudiomap.org/…shared_web_theme/static/src/css/base.css
    http://www.cgstudiomap.org/website/static/src/css/website.css
    http://www.cgstudiomap.org/…ite_mail/static/src/css/website_mail.css
    http://www.cgstudiomap.org/…ite_blog/static/src/css/website_blog.css

**Comment by M4rtine** [comment]
we will not use font-awesome.css and all font files and js

**Comment by M4rtine** [comment]
What do you think about using a compressor css/js 
like the django compressor
https://pypi.python.org/pypi/django_compressor

**Comment by foutoucour** [comment]
It seems we still need the font-awesome.css for the current version.
I will let it for now and see after the integration of the new homepage.

For the compressor, I think odoo got something native. I investigate.

**Comment by foutoucour** [comment]
Found it! t-call-assets allows to compress the js and css files!

**Comment by foutoucour** [comment]
Implemented. Not real change tho :( good for now
