### ISSUE TITLE
decoupage de la page homepage

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#333]
Il me faudrait un decoupage en module de la page home.

Ca me permettrai de voir comment tu penses tes pages et donc comment je dois organiser mon code.

Est ce que tu pourrais faire une sorte de surlignage des zones qui seraient des modules et me dire aussi lesquels te semblent vont être réutiliser dans d'autres pages.

Il me faudrait ca pour Vendredi soir. Est ce possible?

**Comment by M4rtine** [comment]
navbar
map
zone compteurs studios
zone compteur users
zone de texte
list studios
bloc signup pre footer
footer

je viens de rentrer avec 44 messages non lus :(

>

--

**Comment by foutoucour** [comment]
Présent dans frontend_base
* [ ] navbar: `frontend_base.navbar` appelée dans `frontend_base.body`
* [ ] footer: `frontend_base.footer`
* [ ] zone compteur studios: `frontend_base.company_counter`
* [ ] zone compteur users: `frontend_base.user_counter`

Présent das frontend_homepage:
* [ ] map:
* [ ] zone de textes: promotional_text_box
* [ ] list studios: partner_box
* [ ] bloc sign up pre footer: `frontend_homepage.signup_button`
