### ISSUE TITLE
Évaluation le retour sur investissement des couts de la carte de voeux

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#340]
Avant de commencer a travailler sur la carte de voeux, il faudrait voir combien ca va couter de la faire.

Les dépenses que je vois pour la carte de voeux:
* évaluer le nombre de studios ciblés
* temps pour le design de la carte ($20 de l'heure)
* temps de création des textes ($20 de l'heure)
* frais d'impression (vistaprint?)
* frais d'envoi

Je veux compter les nombres d'heures travaillées, car ces heures seraient des heures non travaillées sur d'autres taches.

**Comment by foutoucour** [comment]
@M4rtine à combien d'heure tu estimes la creation de la carte de voeux?

**Comment by M4rtine** [comment]
3h travailler + 1h de modifs aller-retour client généralement


____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*


2015-12-06 21:20 GMT+01:00 Jordi Riera <notifications@github.com>:

**Comment by MangoJazz** [comment]
Cout estimé environ (pas exacte pour les frais d'envois en France depuis
vistaprint): *295$*

- évaluer le nombre de studios ciblés:
3h00 x 20 = 60$
Mise à jour des adresses et fiches des studios ciblés
Bordeaux: 11
Angoueme: 7
Montreal: 29

- temps pour le design de la carte ($20 de l'heure): 4h x 20 = 80$

- temps de création des textes ($20 de l'heure): *Qui le fait finalement?
C'est en français non corpo, il va falloir une idée de départ de ce qu'on
appelle non corpo. 1h00 20$*

- frais d'impression (vistaprint?): 40$ montreal + 20 $ France =50 $

- frais d'envoi depuis vistaprint: 20$+20$ = 40 $

- Frais d'envoi aux studios:
Montreal: 0,85$ x 29 = 24,65$
Angouleme + Bordeaux = 0,99$ x 18 = 17,82$

Edith

​----------------​


2015-12-06 15:20 GMT-05:00 Jordi Riera <notifications@github.com>:

**Comment by M4rtine** [comment]
Je suis sacrément pris par la HomePage mais ça va faire un gros boulot pour
les autres templates. Mais je pense aux cartes dés que j'en vois la fin.

Vous avez créé quoi comme structure 'cg studio map' ?





Le mercredi 9 décembre 2015, MangoJazz <notifications@github.com> a écrit :

> Cout estimé environ (pas exacte pour les frais d'envois en France depuis
> vistaprint): *295$*
>
> - évaluer le nombre de studios ciblés:
> 3h00 x 20 = 60$
> Mise à jour des adresses et fiches des studios ciblés
> Bordeaux: 11
> Angoueme: 7
> Montreal: 29
>
> - temps pour le design de la carte ($20 de l'heure): 4h x 20 = 80$
>
> - temps de création des textes ($20 de l'heure): *Qui le fait finalement?
> C'est en français non corpo, il va falloir une idée de départ de ce qu'on
> appelle non corpo. 1h00 20$*
>
> - frais d'impression (vistaprint?): 40$ montreal + 20 $ France =50 $
>
> - frais d'envoi depuis vistaprint: 20$+20$ = 40 $
>
> - Frais d'envoi aux studios:
> Montreal: 0,85$ x 29 = 24,65$
> Angouleme + Bordeaux = 0,99$ x 18 = 17,82$
>
> Edith
>
> ​----------------​
>
>
> 2015-12-06 15:20 GMT-05:00 Jordi Riera <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
>
> > @M4rtine <https://github.com/M4rtine> à combien d'heure tu estimes la
> > creation de la carte de voeux?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-162344487
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-163084876>
> .
>


--

**Comment by M4rtine** [comment]
Ah et aussi avec Vista peint tu peux commander un truc mais avoir la
livraison différente
Par exemple chez moi et je peux faire le relais France





Le mercredi 9 décembre 2015, David Mazeau <d.mazeau@gmail.com> a écrit :

> Je suis sacrément pris par la HomePage mais ça va faire un gros boulot
> pour les autres templates. Mais je pense aux cartes dés que j'en vois la
> fin.
>
> Vous avez créé quoi comme structure 'cg studio map' ?
>
>
>
>
>
> Le mercredi 9 décembre 2015, MangoJazz <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :
>
>> Cout estimé environ (pas exacte pour les frais d'envois en France depuis
>> vistaprint): *295$*
>>
>> - évaluer le nombre de studios ciblés:
>> 3h00 x 20 = 60$
>> Mise à jour des adresses et fiches des studios ciblés
>> Bordeaux: 11
>> Angoueme: 7
>> Montreal: 29
>>
>> - temps pour le design de la carte ($20 de l'heure): 4h x 20 = 80$
>>
>> - temps de création des textes ($20 de l'heure): *Qui le fait finalement?
>> C'est en français non corpo, il va falloir une idée de départ de ce qu'on
>> appelle non corpo. 1h00 20$*
>>
>> - frais d'impression (vistaprint?): 40$ montreal + 20 $ France =50 $
>>
>> - frais d'envoi depuis vistaprint: 20$+20$ = 40 $
>>
>> - Frais d'envoi aux studios:
>> Montreal: 0,85$ x 29 = 24,65$
>> Angouleme + Bordeaux = 0,99$ x 18 = 17,82$
>>
>> Edith
>>
>> ​----------------​
>>
>>
>> 2015-12-06 15:20 GMT-05:00 Jordi Riera <notifications@github.com>:
>>
>> > @M4rtine <https://github.com/M4rtine> à combien d'heure tu estimes la
>> > creation de la carte de voeux?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-162344487
>> >
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-163084876>
>> .
>>
>
>
> --
>
>

--

**Comment by foutoucour** [comment]
Je ne pense pas que ca soit une priorite. Je prefere qu'on travaille sur
les pages restantes. Il y a beaucoup de travail a faire
le listing n'est toujours pas designer.

Le retour sur investissement semble vraiment bas pour l'effort a produire.

On Wed, Dec 9, 2015 at 2:05 PM David Mazeau <notifications@github.com>
wrote:

> Ah et aussi avec Vista peint tu peux commander un truc mais avoir la
> livraison différente
> Par exemple chez moi et je peux faire le relais France
>
>
>
>
>
> Le mercredi 9 décembre 2015, David Mazeau <d.mazeau@gmail.com> a écrit :
>
> > Je suis sacrément pris par la HomePage mais ça va faire un gros boulot
> > pour les autres templates. Mais je pense aux cartes dés que j'en vois la
> > fin.
> >
> > Vous avez créé quoi comme structure 'cg studio map' ?
> >
> >
> >
> >
> >
> > Le mercredi 9 décembre 2015, MangoJazz <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :
> >
> >> Cout estimé environ (pas exacte pour les frais d'envois en France depuis
> >> vistaprint): *295$*
> >>
> >> - évaluer le nombre de studios ciblés:
> >> 3h00 x 20 = 60$
> >> Mise à jour des adresses et fiches des studios ciblés
> >> Bordeaux: 11
> >> Angoueme: 7
> >> Montreal: 29
> >>
> >> - temps pour le design de la carte ($20 de l'heure): 4h x 20 = 80$
> >>
> >> - temps de création des textes ($20 de l'heure): *Qui le fait
> finalement?
> >> C'est en français non corpo, il va falloir une idée de départ de ce
> qu'on
> >> appelle non corpo. 1h00 20$*
> >>
> >> - frais d'impression (vistaprint?): 40$ montreal + 20 $ France =50 $
> >>
> >> - frais d'envoi depuis vistaprint: 20$+20$ = 40 $
> >>
> >> - Frais d'envoi aux studios:
> >> Montreal: 0,85$ x 29 = 24,65$
> >> Angouleme + Bordeaux = 0,99$ x 18 = 17,82$
> >>
> >> Edith
> >>
> >> ----------------
> >>
> >>
> >> 2015-12-06 15:20 GMT-05:00 Jordi Riera <notifications@github.com>:
> >>
> >> > @M4rtine <https://github.com/M4rtine> à combien d'heure tu estimes la
> >> > creation de la carte de voeux?
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> >>
> https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-162344487
> >> >
> >> > .
> >> >
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-163084876
> >
> >> .
> >>
> >
> >
> > --
> >
> >
>
> --
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-163359201>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
Yep

Le mercredi 9 décembre 2015, Jordi Riera <notifications@github.com> a
écrit :

> Je ne pense pas que ca soit une priorite. Je prefere qu'on travaille sur
> les pages restantes. Il y a beaucoup de travail a faire
> le listing n'est toujours pas designer.
>
> Le retour sur investissement semble vraiment bas pour l'effort a produire.
>
> On Wed, Dec 9, 2015 at 2:05 PM David Mazeau <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Ah et aussi avec Vista peint tu peux commander un truc mais avoir la
> > livraison différente
> > Par exemple chez moi et je peux faire le relais France
> >
> >
> >
> >
> >
> > Le mercredi 9 décembre 2015, David Mazeau <d.mazeau@gmail.com
> <javascript:_e(%7B%7D,'cvml','d.mazeau@gmail.com');>> a écrit :
> >
> > > Je suis sacrément pris par la HomePage mais ça va faire un gros boulot
> > > pour les autres templates. Mais je pense aux cartes dés que j'en vois
> la
> > > fin.
> > >
> > > Vous avez créé quoi comme structure 'cg studio map' ?
> > >
> > >
> > >
> > >
> > >
> > > Le mercredi 9 décembre 2015, MangoJazz <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> a écrit :
> > >
> > >> Cout estimé environ (pas exacte pour les frais d'envois en France
> depuis
> > >> vistaprint): *295$*
> > >>
> > >> - évaluer le nombre de studios ciblés:
> > >> 3h00 x 20 = 60$
> > >> Mise à jour des adresses et fiches des studios ciblés
> > >> Bordeaux: 11
> > >> Angoueme: 7
> > >> Montreal: 29
> > >>
> > >> - temps pour le design de la carte ($20 de l'heure): 4h x 20 = 80$
> > >>
> > >> - temps de création des textes ($20 de l'heure): *Qui le fait
> > finalement?
> > >> C'est en français non corpo, il va falloir une idée de départ de ce
> > qu'on
> > >> appelle non corpo. 1h00 20$*
> > >>
> > >> - frais d'impression (vistaprint?): 40$ montreal + 20 $ France =50 $
> > >>
> > >> - frais d'envoi depuis vistaprint: 20$+20$ = 40 $
> > >>
> > >> - Frais d'envoi aux studios:
> > >> Montreal: 0,85$ x 29 = 24,65$
> > >> Angouleme + Bordeaux = 0,99$ x 18 = 17,82$
> > >>
> > >> Edith
> > >>
> > >> ----------------
> > >>
> > >>
> > >> 2015-12-06 15:20 GMT-05:00 Jordi Riera <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> > >>
> > >> > @M4rtine <https://github.com/M4rtine> à combien d'heure tu estimes
> la
> > >> > creation de la carte de voeux?
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> > <
> > >>
> >
> https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-162344487
> > >> >
> > >> > .
> > >> >
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> >
> https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-163084876
> > >
> > >> .
> > >>
> > >
> > >
> > > --
> > >
> > >
> >
> > --
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-163359201
> >
> > .
> >
> --
> ---
> - Jordi Riera, Connecting Softwares and people.
> Founder at www.cgstudiomap.org, Because everyone should be familiar with
> the cg industry
>
> www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/340#issuecomment-163363127>
> .
>


--

**Comment by MangoJazz** [comment]
Structure?

On n'a rien crée pour la carte papier pour le moment, Jordi voulait avoir
une idée du coup avant.

Mais sinon dans les 3 doc que je t'avais envoyé, il n'y a rien qu'on puisse
garder?
Pour le non corpo, comme on avait discuté il me faudrait une idée car je
n'ai aucune experience en non corpo.

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2015-12-09 13:44 GMT-05:00 David Mazeau <notifications@github.com>:

**Comment by MangoJazz** [comment]
On oublies finalement?

**Comment by foutoucour** [comment]
On oublie.

On part sur une carte de voeux electronique tres simple (voir #352)
