### ISSUE TITLE
Enlever le ? à la catch phrase sur society6

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#342]
Notre catch phrase est `where cg is`, pas de ponctuation.

Il faudrait corriger les items sur society6.

**Comment by M4rtine** [comment]
ok je viens de tout corriger. désolé ;)

**Comment by foutoucour** [comment]
:+1:

Thx

On Mon, Dec 7, 2015 at 10:46 AM David Mazeau <notifications@github.com>
wrote:

> ok je viens de tout corriger. désolé ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/342#issuecomment-162563006>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by MangoJazz** [comment]
Merci beaucoup
