### ISSUE TITLE
Implementation du snazzymaps

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#346]
La carte qui sera utilise pour la page map sera customise en utilisant snazzymap.

Il faut implementer cette customisation et utilise ce theme dans un premier temps:
https://snazzymaps.com/style/13113/custom-applesque-theme

Il serait bien d'implementer la solution de maniere qu'un designer puisse faire la maintenance tout seul.

**Comment by M4rtine** [comment]
snazzu ^^


____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by foutoucour** [comment]
fixed :p

**Comment by foutoucour** [comment]
Le nouveau style a été implementé.

A noté qu'il manque le nom des rues.
Je te passe la main @M4rtine pour voir comment rajouté ca.


![uploads/15ad7e78-4573-425d-a4b8-88901f935fd9/b_20151220_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F15ad7e78-4573-425d-a4b8-88901f935fd9%2Fb_20151220_001.png)

![uploads/b6c02345-9ae8-4968-b799-0541cfe8e478/7_20151220_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb6c02345-9ae8-4968-b799-0541cfe8e478%2F7_20151220_001.png)

**Comment by M4rtine** [comment]
Pas de problème

>

--

**Comment by M4rtine** [comment]
1st release done
Quelques détails restent encore à faire dans une issue plus global sur tous les petits détails.

Merge #360


![uploads/b2920231-38d6-455c-849c-4dd857f35fc1/cgsm-#346-snazzymaps.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb2920231-38d6-455c-849c-4dd857f35fc1%2Fcgsm-%23346-snazzymaps.jpg)
