### ISSUE TITLE
Menus section in left column

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#35]
Add a section in the left column called Menus. Create links to in the section:
* Home
* Dashboard
* Contact Us
* Preferences
* Log out

**Comment by M4rtine** [comment]
Simplify : 
* Dashboard
* Account :
  * Preferences
  * Log out

Home is in the logo icon

**Comment by foutoucour** [comment]
Add a `report an issue` entry for the first version.

**Comment by foutoucour** [comment]
Not anymore up to date.
