### ISSUE TITLE
French studios enhancement

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#351]
Mettre à jour tous les studios de France, logo, adresse, courriel

**Comment by M4rtine** [comment]
J'en fais ce soir ;)


____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*


2015-12-12 17:40 GMT+01:00 MangoJazz <notifications@github.com>:

**Comment by MangoJazz** [comment]
il y en a tellement qui ont fermés leurs portes :(

**Comment by M4rtine** [comment]
Ouaip normal la crise financière à fais des ravages sur les studios faibles

Le samedi 12 décembre 2015, MangoJazz <notifications@github.com> a écrit :

> il y en a tellement qui ont fermés leurs portes :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/351#issuecomment-164197057>
> .
>


--

**Comment by M4rtine** [comment]
Mise à jour logos et socials et phone si nécessaire

18 studios en France = 38 min
- 16 actifs
- 2 fermés


Pour estimer le temps de travail ;)



Le dimanche 13 décembre 2015, David Mazeau <d.mazeau@gmail.com> a écrit :

> Ouaip normal la crise financière à fais des ravages sur les studios faibles
>
> Le samedi 12 décembre 2015, MangoJazz <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :
>
>> il y en a tellement qui ont fermés leurs portes :(
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cgstudiomap/cgstudiomap/issues/351#issuecomment-164197057>
>> .
>>
>
>
> --
>
>

--

**Comment by MangoJazz** [comment]
Salut,

Wow tu es bien plus rapide que moi.

Il y a enormement de studios qui ont changé d'adresses. Est-ce que tu
verifie en même temps aussi?

**Comment by M4rtine** [comment]
aujourd'hui 18h40 heure française il en reste 78 à faire ;)

J'en ai fais 34 dans la journée
- 26 actif
- 2 nouveaux noms
- 6 fermés


____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by MangoJazz** [comment]
Et l'adresse? As tu vu mon message??

**Comment by M4rtine** [comment]
Je ne m'occupe que de ceux qui n'ont pas de logo et quand c'est le cas je rajoute (twitter, facebook, phone souvent) et je check l'adresse 
mais c'était rare qu'elle soit changé pour ceux que j'ai fais.

**Comment by MangoJazz** [comment]
ok cool, merci.

Depuis hier je fais la France aussi, et pour un grand nombre ils ont
déménagé, c'est pour ça que je demandais.

bonne fin de soirée.

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2015-12-13 14:00 GMT-05:00 David Mazeau <notifications@github.com>:

**Comment by MangoJazz** [comment]
FINIS POUR LA FRANCE OURAHHHH

Merci David pour ton aide.
