### ISSUE TITLE
Electronic Wish card to companies 2015

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#352]
Faire une carte de voeux via email aux compagnies dans le but:
- Nettoyer la base de données
- Voir le retour

**Comment by MangoJazz** [comment]
texte pret, envoyée à David pour le design

**Comment by MangoJazz** [comment]
Template créée dans mail chimp, attente image pour créer la campagne

**Comment by M4rtine** [comment]
Ok, donc il faut que tu me rajoutes en tant qu' "author" sur le compte
cgstudiomap.

Pendant ce temps tu peux déjà créé la campagne et faire paramètrer le
compte techniquement par @foutoucour

Car les templates sont personelles et je ne les verrais que dans la
campagne


--

**Comment by MangoJazz** [comment]
Tu es déjà en author avec ton adresse mail. Est-ce différent ?

Mais tu vas pouvoir changer le design de la template si je créée une
campagne?

On regarde le tout ce soir.

Merci

**Comment by foutoucour** [comment]
La tache, trop grosse, est séparée en plusieurs plus petites taches. Ca permettra de voir l'avancement de la milestone.
