### ISSUE TITLE
Social Link error is back

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#355]
J'ai recroisé l'erreur de lien quand on colle le lien twitter, facebook ou linkedin.
Je crois avoir compris. Ca ne se passe que quand la dernière lettre est en majuscule et suivi d'un /

exemple : 
https://twitter.com/Studio3D/ = ERROR
https://twitter.com/Studio3D  = GOOD
https://twitter.com/Studio3d/ = GOOD

**Comment by foutoucour** [comment]
Fixed in #356
