### ISSUE TITLE
Design de la page DIRECTORY

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#360]
Travail de design sur les pages /directory/list et /directory/map pour qu'elles soient au plus proche du prototype: https://marvelapp.com/6jj17a

![uploads/44306320-39e3-4c52-8427-ca91db86cbfd/edb4200a-961f-11e5-866a-27efe84b57f5.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F44306320-39e3-4c52-8427-ca91db86cbfd%2Fedb4200a-961f-11e5-866a-27efe84b57f5.jpg)

![uploads/ab115c4b-8bb1-4e98-84f9-fc483350f29c/edb4764a-961f-11e5-82d1-e52c6625d387.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fab115c4b-8bb1-4e98-84f9-fc483350f29c%2Fedb4764a-961f-11e5-82d1-e52c6625d387.jpg)

**Comment by foutoucour** [comment]
@M4rtine dis moi, quand on clic sur directory, on va sur la map ou sur la list?

**Comment by M4rtine** [comment]
Sur la map ;)

>

--

**Comment by M4rtine** [comment]
[WIP]


![uploads/d6b0d853-2d3d-4fbe-b325-c7106f9c0cf5/cgsm-#360-list02.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd6b0d853-2d3d-4fbe-b325-c7106f9c0cf5%2Fcgsm-%23360-list02.jpg)

**Comment by M4rtine** [comment]
![uploads/ee6ec81a-653e-45e6-a092-1528d1c1dbfe/cgsm-#360-nav.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fee6ec81a-653e-45e6-a092-1528d1c1dbfe%2Fcgsm-%23360-nav.jpg)

**Comment by M4rtine** [comment]
![uploads/814f6f53-d4b8-495a-881d-0549f7937150/cgsm-#360-list.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F814f6f53-d4b8-495a-881d-0549f7937150%2Fcgsm-%23360-list.jpg)
