### ISSUE TITLE
Bug design homepage mobile

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#361]
On a regarde le site sur nos portables et ipad et on a vu des soucis:

* Google Nexus6 pas de soucis
* Samsumg S5, les cubes des compteurs ne sont pas alignes, comme s'il y avait pas assez de place
* ipad en mode paysage: titre dans la navbar qui n'apparaissent pas (surement qu'ils sont en dessous). Le menu est bon en mode portrait.

**Comment by M4rtine** [comment]
Ok merci
Je vais voir ca
Est ce que tu aurais les résolutions de ces devices s'il te plaît ;)




--

**Comment by MangoJazz** [comment]
SAMSUNG S5 - 1920 x 1080
NEXUS 6 - 2560x1440
IPAD 3 - 2048 x 1536

**Comment by M4rtine** [comment]
merci @MangoJazz 
Ok donc ce n'est pas du mobile mais plutôt les hautes résolution voir même Retina.

**Comment by foutoucour** [comment]
J'ai vu le probleme sur un nexus 5 aussi

**Comment by M4rtine** [comment]
Pull Request #369

**Comment by foutoucour** [comment]
Le problème sur la navbar est reglé. Le code a ete mergé.
Mais il y a toujours un bug sur le footer

![uploads/9b541230-a3a9-4168-8538-a904a0dcb89a/7_20151217_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9b541230-a3a9-4168-8538-a904a0dcb89a%2F7_20151217_001.png)

**Comment by M4rtine** [comment]
Oui je l'ai vu je l'ai corrigé avec le frontend listing





--

**Comment by foutoucour** [comment]
Je viens de regarder avec la branche #360, le scrolling a disparu, et le footer est tout casse :(


![uploads/6d375112-8c36-428d-ab7b-85a5b69f3775/3_20151227_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6d375112-8c36-428d-ab7b-85a5b69f3775%2F3_20151227_001.png)


Essaie de faire une branche par issues a corriger. Ca nous permettra par exemple ici de pouvoir mettre en ligne le nouveau footer sans mettre en ligne le reste.

J

**Comment by M4rtine** [comment]
>
> Nan je me suis relu et je voulais dire je vais le faire donc rien n'est
> fais la en ligne
>
La solution je l'ai en local fonctionnel


--

**Comment by foutoucour** [comment]
#427 regle le probleme de scroll. Un probleme dans une css de frontend_listing

**Comment by foutoucour** [comment]
@m4rtine il faut encore regler le probleme de footer

**Comment by M4rtine** [comment]
Merge & Fix #360
