### ISSUE TITLE
Simple About Page

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#363]

**Comment by M4rtine** [comment]
J'ai poussé une version pour que tu puisses travailler et si tu pouvais masquer le footer 
#

**Comment by M4rtine** [comment]
@foutoucour #676 à faire ;)

**Comment by M4rtine** [comment]
@foutoucour où ça en est les trucs à faire dans cette page ? parce que en local chez moi je vois bien le module frontend_about. J'ai pu travailler l'image du résumé mais pour ce qui est du contenu des blocs avec nos têtes et descriptif je vois rien en local.
Mais je vois bien que y'a un code.
Est ce que y'a une histoire de base de données ?

**Comment by M4rtine** [comment]
@foutoucour @MangoJazz 
Qu'est ce que vous en pensez ?


![uploads/575c0c12-4a05-4691-ad20-dcad559f541d/cgsm-#363-about-page.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F575c0c12-4a05-4691-ad20-dcad559f541d%2Fcgsm-%23363-about-page.jpg)

**Comment by MangoJazz** [comment]
Salut,

- Les titres sont excellents et très bien trouvés.
- Avoir Ajouté Jazz est une superbe idée. Faut trouver une place pour Mawé
:).
- Les lunettes 3D c'est vraiment génial.

- Peux tu mettre les lunettes au coding alchimist et enlever les miennes?

- Tu avais parlé de téléphone pour mon avatar et d'ordi pour celui de
Jordi. Est-ce faisable?

- La phrase "we make CG..." le temps ne fonctionne pas. Peux tu mettre :
who is behing CG Studio Map.

Merci,

Edith

**Comment by M4rtine** [comment]
Ouai en fait j'avais imaginé d'autres choses avant et pi hier soir g eu la révélation. Il vaut mieux dessiner des têtes caricatures 8bit. Comme ça on nous voit sans nous voir. On humanise le projet. Le côté 8 bit ou pixel art fais référence à notre génération. Je suis plus confiant dans ce style graphique pour dessiner aussi.

Maly ce n'est pas la peine, jazz est le prétexte pour expliquer que ya qq1 qui surveille jour et nuit ;)

Le reste pas de problème je corrige ;)

**Comment by M4rtine** [comment]
En attente #680
