### ISSUE TITLE
Presentation de la page Studio en mode edition

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#365]
Faire une presentation en prototype ou en template de la fiche studio quand l'utilisateur a clique sur Edit

**Comment by M4rtine** [comment]
Beaucoup de détails en fait :(

![uploads/9cdd464a-912d-43b9-801a-25a35f62f20e/cgsm-webdesign-2016-01-edition.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9cdd464a-912d-43b9-801a-25a35f62f20e%2Fcgsm-webdesign-2016-01-edition.jpg)

**Comment by foutoucour** [comment]
ouais c'est plus complexe que prevu la chose.

**Comment by foutoucour** [comment]
Ok on garde ca sous le coude. Jeudi on se concentre sur la page non editee. Je peux faire un lien vers le back dans un premier temps ok?

**Comment by M4rtine** [comment]
Pas de problème ;)
Ça reste  une version vers laquelle on peut tendre bien sûr après faut voir
ce qui est réalisable en dev

Pour le design ce sera quand même plus simple que les autres pages
Ya pas d'inconnu et pas mal de choses sont déjà faites


--
