### ISSUE TITLE
BUG menu navbar

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#367]
Les menus dans la navbar ne se placent pas correctement souvent. Ils sont souvent en dessous.

Tu saurais pourquoi?

**Comment by MangoJazz** [comment]
screen shot de mon PC



Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2015-12-16 21:16 GMT-05:00 Jordi Riera <notifications@github.com>:

**Comment by MangoJazz** [comment]
en bas aussi
screenshot attached

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2015-12-16 21:17 GMT-05:00 Edith Courtial <edith.courtial@gmail.com>:

**Comment by M4rtine** [comment]
Y'a pas d'image mais c'est la même issue

**Comment by M4rtine** [comment]
Fix #361
