### ISSUE TITLE
Dupplicate studio BUG

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#368]
Lorsque je veux dupliquer un studio parce qu'il y a d'autres succursales une page apparait (screenshot). C'est la première fois que ça m'arrive.

![uploads/79ba174c-0438-4b8d-80b4-0b615157d0f5/Screen Shot 2015-12-16 at 9.42.00 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F79ba174c-0438-4b8d-80b4-0b615157d0f5%2FScreen+Shot+2015-12-16+at+9.42.00+PM.png)

**Comment by MangoJazz** [comment]
en fait la fenetre apparait aussi lorsque je veux creer un studio :(

**Comment by foutoucour** [comment]
le problème venait d'un `strip()` implementé sans vérifier que la variable était une string.
