### ISSUE TITLE
Remettre Sentry

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#371]
Sentry, meme s'il va couter un petit peu d'argent va permettre de detecter les bugs très rapidement et surtout de les résoudre facilement.

En plus, avec cette grosse mise à jour il va être vraiment important de savoir ce qu'il se passe sur le server.

**Comment by MangoJazz** [comment]
c'est quoi le cout?

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2015-12-17 19:18 GMT-05:00 Jordi Riera <notifications@github.com>:

**Comment by foutoucour** [comment]
$29/mois soit $380 par an

On Thu, Dec 17, 2015 at 7:36 PM MangoJazz <notifications@github.com> wrote:

> c'est quoi le cout?
>
> Edith Courtial
>
> *cg Studio Map <http://www.cgstudiomap.org/>*
> Dedicated contributor / Contributrice dévouée
>
>
> 2015-12-17 19:18 GMT-05:00 Jordi Riera <notifications@github.com>:
>
> > Sentry, meme s'il va couter un petit peu d'argent va permettre de
> detecter
> > les bugs très rapidement et surtout de les résoudre facilement.
> >
> > En plus, avec cette grosse mise à jour il va être vraiment important de
> > savoir ce qu'il se passe sur le server.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cgstudiomap/cgstudiomap/issues/371>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/371#issuecomment-165624719>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
J'ai beaucoup vu Sentry dans les derniers projets de backoffice et des
apps. C'est bien.
Mais par contre la manière dont les dev l'utilisais c'était gratuite

>

--

**Comment by foutoucour** [comment]
Tu pourrais voir comment ils faisaient?

On Fri, Dec 18, 2015 at 1:49 AM David Mazeau <notifications@github.com>
wrote:

> J'ai beaucoup vu Sentry dans les derniers projets de backoffice et des
> apps. C'est bien.
> Mais par contre la manière dont les dev l'utilisais c'était gratuite
>
> >
>
> --
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/371#issuecomment-165692479>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
Je suis dessus ;)

**Comment by foutoucour** [comment]
Mathieu nous permet d'utiliser son server pour sentry. Ca va nous permettre d'economiser sur ca.

Il faut donc changer la cle dns sentry dans `etc/odoo_server.cfg`

**Comment by foutoucour** [comment]
test

**Comment by foutoucour** [comment]
La version de sentry sur le serveur de Matthieu n'est pas assez recente pour notre instance Odoo.

A voir avec lui si une mise à jour est envisageable.

**Comment by MangoJazz** [comment]
@foutoucour: faudrait relancer Mathieu.
