### ISSUE TITLE
Xmas card for users

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#372]
La carte doit etre un peu differente pour les utilisateurs

**Comment by MangoJazz** [comment]
envoyée à David et Jordi pour review et ajouter Design.

Devrait etre envoyée avant le 24 Décembre.

**Comment by MangoJazz** [comment]
Template créée dans mail chimp, attente image pour créer la campagne

**Comment by foutoucour** [comment]
La carte de noel a été annulée en faveur d'une e-carte de bonne année
