### ISSUE TITLE
Visible number Studios Load

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#380]
Pour améliorer la gestion des données via Bootstrap-Table il faut lui laisser gérer la pagination.
La hauteur du tableau sera Responsive (en fonction de la hauteur des explorateurs)

https://github.com/cgstudiomap/cgstudiomap/blob/360-design-directory-listing/main/local_modules/frontend_listing/controllers/listing.py
ligne 157

**Comment by M4rtine** [comment]
partner_per_page = 100 
enlever le call à la templates pager

**Comment by M4rtine** [comment]
Done
Merge in #360

**Comment by M4rtine** [comment]
@foutoucour :( tout cassé

**Comment by foutoucour** [comment]
je regarde ca

**Comment by foutoucour** [comment]
c'est regle. Un probleme avec l'intégration de sentry mais ca ne devrait pas etre un probleme dans le futur.

**Comment by foutoucour** [comment]
je travaille la pagination pour que ca soit bootstrap table qui la gere et pas odoo

**Comment by foutoucour** [comment]
Integration faite.

![uploads/2fc5dc50-8990-4e79-b470-27ab268de5fe/e_20160103_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2fc5dc50-8990-4e79-b470-27ab268de5fe%2Fe_20160103_001.png)

Le tableau est maintenant totalement sous bootstrap table à part la recherche qui est géré en backend par odoo.
Le remplissage du tableau est fait en ajax pour reduire le temps de chargement de la page. Le temps de chargement percu reste assez élevé, donc un loader a étét implementé (vour #418)

**Comment by foutoucour** [comment]
@M4rtine il faudrait que tu me dises ce que tu en penses.

**Comment by foutoucour** [comment]
@M4rtine ping

**Comment by M4rtine** [comment]
Je vais devoir faire une couche dessus mais tout roule ;)



>

--
