### ISSUE TITLE
TEMPLATES ordres BLOCS

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#387]
Revoir le squelette des templates #360
Ordres à corriger : 
- frontend_base

---- frontend_head :

-------- \* après link canonical il faut mettre les meta twitter
-------- \* les FAVICONS à la suite des meta
-------- \* les CSS et JS du head doivent être en dernier (avant la fin de head)

---- frontend_engine :

-------- \* le GOOGLE ANALYTICS doit être à la fin fin (fin de balise body)
-------- \* le script chargement des pays après api google
-------- \* le div wrapwrap et le div scrollne doivent pas être aprés les scripts mais tout au dessus
- frontend_listing

---- frontend_body :
-------- \* le switch n'est pas dans le body

**Comment by foutoucour** [comment]
hey @M4rtine 

Quels sont els avantages a revoir l'ordre?

J

**Comment by M4rtine** [comment]
Dans certains cas ca permettra d'éviter de sur-patché des erreurs que l'on
ne comprends pas

Des décalages, des interprétations de code pas dans le bon ordre et aussi
de l'optimisation pour la vitesse.

J'ai fais une issue pour ca parce que je pense les inclusions ne font pas
ce que tu voulais que ca fasse quand tu l'as écris
J'ai l'impression que tout est inclue a l'inverse



--

**Comment by foutoucour** [comment]
won't do
