### ISSUE TITLE
Problemes de design en backoffice admin

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#400]
Avec l'update du design du backoffice Admin,

quelques glitchs se sont glisses:

Les pop up n'ont plus de backgroud:
![uploads/4c47f843-5bdb-411a-ab83-585d9e99d9d9/Screenshot-8.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4c47f843-5bdb-411a-ab83-585d9e99d9d9%2FScreenshot-8.png)

Le discard a cote du bouton save est invisible:

![uploads/1bb1eca4-e392-49b3-953e-ef083a455e28/Screenshot-11.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1bb1eca4-e392-49b3-953e-ef083a455e28%2FScreenshot-11.png)

![uploads/4cc7b898-629d-468e-9950-65eef02d3584/Screenshot-12.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4cc7b898-629d-468e-9950-65eef02d3584%2FScreenshot-12.png)

Le fil d'ariane (Open for B...) n'a plus assez de place pour s'afficher totalement. Il est sense montre Open for Business > NOM COMPANIE

Merci a toi!
Jordi

**Comment by foutoucour** [comment]
voir #404

**Comment by M4rtine** [comment]
L'issue 404 ca fais peur comme nom



--

**Comment by foutoucour** [comment]
Le probleme est résolu en enlevant le theme sur le back office.
voir #400

**Comment by M4rtine** [comment]
je ne sais pas :(

**Comment by foutoucour** [comment]
On laisse ca pour apres l'arrivee de toutes les features
