### ISSUE TITLE
Design eblast user pour l'ouvertue user public

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#405]
En suivant le travail fait sur #310, faire le design de l'eblast user.

Le design doit nous permettre dans le long terme de ne pas a avoir a faire appel a un designer pour faire un nouvel eblast

**Comment by MangoJazz** [comment]
suite à nos conversations du samedi, David a crée une template sur mailchimp à utiliser pour chaque envoi.
je ferme donc la tache.
