### ISSUE TITLE
Design de l'e-carte compagnie

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#406]
Faire la template dans laquelle le texte fait dans #352 sera importé.

La carte se voudra festive et corporate.

**Comment by MangoJazz** [comment]
https://us12.admin.mailchimp.com/campaigns/wizard/neapolitan?id=98289

**Comment by M4rtine** [comment]
A Tester

![uploads/d65b9095-c2c2-4350-890c-6ba15e0f906d/cgsm-mailchimp-2016.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd65b9095-c2c2-4350-890c-6ba15e0f906d%2Fcgsm-mailchimp-2016.jpg)

**Comment by MangoJazz** [comment]
super, l'envoi est prévu pour demain 8h00. Merci beaucoup. Avec Jordi on a tiré la nouvelle liste et crée la campagne.
