### ISSUE TITLE
Twitter message VS Vimeo

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#410]
Le message de la fenetre qui apparait quand le compte Twitter n'est pas bon apparait aussi quand le compte Vimeo n'est pas bon mais avec le texte de Twitter.

![uploads/aae849f3-8200-43b0-8a8d-e5b6e29b5799/Screen Shot 2015-12-29 at 3.55.51 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faae849f3-8200-43b0-8a8d-e5b6e29b5799%2FScreen+Shot+2015-12-29+at+3.55.51+PM.png)

**Comment by foutoucour** [comment]
Problème résolu, mais je sais pas trop quand :( 


![uploads/10a5a718-f58a-491e-9394-470007cab61d/2_20160131_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F10a5a718-f58a-491e-9394-470007cab61d%2F2_20160131_001.png)
