### ISSUE TITLE
Design du loader gif

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#421]
Dans la tache #418, un gif de loading a été implémenté.

Il faudrait voir si tu veux le customiser par rapport à la charte du site.

**Comment by foutoucour** [comment]
Je pense que le loader que j'ai mis peut suffire pour une premier jet, donc je mettrai la tache en low priotity pour le moment.

**Comment by M4rtine** [comment]
Plus de code moins d'image = mieux pour Retina display
J'ai mis un truc basique centré et coloré.

@foutoucour il faudra faire un système qui montre un tableau vide pendant le chargement au lieu d'un applat

**Comment by foutoucour** [comment]
Super!

Le remplissage de la page sera fait dans #445
