### ISSUE TITLE
Design info window

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#422]
Les informations ont  été implementés dans les info windows de la carte.

![uploads/27ef07b5-1802-4dd6-b6fd-245ce51713da/3_20160103_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F27ef07b5-1802-4dd6-b6fd-245ce51713da%2F3_20160103_001.png)

Il faudrait maintenant revoir le design de l'info window.

Le code de l'info window est généré dans https://github.com/cgstudiomap/cgstudiomap/blob/360-design-directory-listing/main/local_modules/frontend_base/models/res_partner.py#L136

**Comment by M4rtine** [comment]
Merge #360

**Comment by M4rtine** [comment]
![uploads/ccf141af-3500-41dc-a78d-14db45fba5f5/cgsm-#422-infowidows.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fccf141af-3500-41dc-a78d-14db45fba5f5%2Fcgsm-%23422-infowidows.jpg)

**Comment by foutoucour** [comment]
Sympas l'info windows!

Il a des soucis quand il y a beaucoup d'industries par contre.
Peut etre prevoir plus de place.

**Comment by foutoucour** [comment]
problème toujours présent

**Comment by M4rtine** [comment]
normal il est toujours dans à faire ;)

**Comment by M4rtine** [comment]
le problème vient de la class des label tags manquantes
ça sera corrigé ici
#478
