### ISSUE TITLE
Design du marker de la carte

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#423]
Le mecanisme pour mettre un marker custom a été mis en place dans #418 ceci pour les markers individuels mais aussi pour les markers de groupes

![uploads/806e6a9e-794a-4d50-98fc-762a9b41496d/3_20160103_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F806e6a9e-794a-4d50-98fc-762a9b41496d%2F3_20160103_001.png)

Il faudrait maintenant, en suivant le prototype, mettre en place le marker personnalisé pour cgstudiomap:

![uploads/30864bb2-c4d1-4612-a0eb-1c4383c58915/edb4764a-961f-11e5-82d1-e52c6625d387.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F30864bb2-c4d1-4612-a0eb-1c4383c58915%2Fedb4764a-961f-11e5-82d1-e52c6625d387.jpg)

dans https://github.com/cgstudiomap/cgstudiomap/blob/360-design-directory-listing/main/local_modules/frontend_listing/static/src/js/google_map.js
* ligne 28 est l'icone pour les markers individuels
* ligne 42 pour les markers des groupes

**Comment by M4rtine** [comment]
Merge #360

![uploads/6adff741-dd8f-4a70-9273-d0933679a18b/cgsm-#423-markers.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6adff741-dd8f-4a70-9273-d0933679a18b%2Fcgsm-%23423-markers.jpg)

**Comment by foutoucour** [comment]
Super pour la carte.

Par contre le footer est le meme que celui de la liste. Est ce normal?

**Comment by M4rtine** [comment]
Nan je suis dessus pour le moment tu cliques n'importe où dans le fond
sombre du footer pour simuler comment il sera sur la map.
Je l'ai mis en condition en fonction de click pour aller plus vite


>

--
