### ISSUE TITLE
Implementer le bouton `add a studio`

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#424]
En suivant le prototype,

![uploads/ae265c22-d40d-4692-8a2
1-3eadc8a50608/edb4764a-961f-11e5-82d1-e52c6625d387.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fae265c22-d40d-4692-8a21-3eadc8a50608%2Fedb4764a-961f-11e5-82d1-e52c6625d387.jpg)

Il apparait un bouton `Add a studio` dans la barre de sous menu du listing.

Ce bouton doit être un lien direct vers la page permettant de rajouter un nouveau studio.

L'implémentation de ce bouton doit permettre sa mise en ligne même si les nouvelles pages des studios ne sont pas en production.

**Comment by foutoucour** [comment]
Le bouton add a studio ne pourra implementer qu'une fois que la nouvelle page de compagnie ne sera implementer.

**Comment by M4rtine** [comment]
@foutoucour #360 frontend_listing
ligne : 141

```
<a class="btn btn-cgsm-add center-block" href="#" role="button">ADD Studio <i class="fa fa-step-forward fa-fw fa-rotate-90"/> </a>
```

**Comment by foutoucour** [comment]
Le probleme est que l'url a mettre dans href pour aller directement sur la page en backoffice en mode create ne marche pas

ca sera possible qu'une fois que la page de creation de studio sera en front.

**Comment by foutoucour** [comment]
Ca demande que la nouvelle page de creation de studio soit finie.

**Comment by M4rtine** [comment]
@foutoucour
ça sera comme ça avec la nouvelle font d'icones.
```
<a class="btn btn-cgsm-add center-block" href="#" role="button">ADD Studio <span class="fontCGSMicons">upload</span></a>
```
