### ISSUE TITLE
Design Footer

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#430]
Change icons method for better responsive way
- Homepage Footer = Full credits text + icons
- Directory Listing Footer = minimalist
- Directory Map Footer = minimalist + transparent BG

**Comment by M4rtine** [comment]
Merge & Fix #360

**Comment by foutoucour** [comment]
Tu peux mettre des Screenshot pour verifier que j'ai le bon resultat une fois le code puller?

**Comment by M4rtine** [comment]
@foutoucour 
![uploads/24864257-b399-49fe-8875-64acb3ecc50c/cgsm-#430-footer.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F24864257-b399-49fe-8875-64acb3ecc50c%2Fcgsm-%23430-footer.jpg)
