### ISSUE TITLE
Erreur403 - utilisateurs non-enregistrés

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#434]
Les utilisateurs non logé  :
- un message d'accés 'Forbidden' sur les pages Homepage, Directory (map)
- la page se charge mais pas de data de la table
- les pages About, Sign in et Contact se charge normalement

**Comment by foutoucour** [comment]
Message d'erreur:
```
AccessError: ('AccessError', u'Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Portal\n\t- Phone CallerID\n\t- Sales/Manager\n\t- Sales/See Own Leads\n\t- Sales/See Own Leads\n\t- Sales/Manager\n\t- Portal\n\t- Public\n\t- Portal\n\t- Contact Creation\n\t- Human Resources/Employee\n\t- Portal\n\t- Sales/Manager\n\t- Accounting & Finance/Financial Manager\n\n(Document model: res.partner)')
```

**Comment by foutoucour** [comment]
Modification dans res_partner_industry pour permettre acces aux utilisateurs no logges.

@M4rtine Ferme si le probleme est bien regle dans ton instance aussi.

**Comment by M4rtine** [comment]
👍🏻
>
>

--
