### ISSUE TITLE
Toggle Footer DIRECTORY

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#440]
Désactiver le background du Footer quand on est dans MAP

**Comment by M4rtine** [comment]
@foutoucour 
J'aurais besoin de savoir comment je peux détecter que je suis dans la page map. Ou alors en entrant dans la page map .

J'ai mis pour le moment le changement de BG par rapport au clic
\main\local_modules\shared_web_theme\static\src\js
ligne 12

        $(".footer").click(function () {
            $(".footer").toggleClass("changeBG");
        });

**Comment by foutoucour** [comment]
@M4rtine le systeme pour avoir des footers differents est mis en place. 

La liste et la carte ont chacun un footer le meme footer mais avec des id spécifiques pour chaque page: `footer_list` et `footer_map`


![uploads/0683849d-20a2-4c69-b9ba-e87452f76bae/7_20160111_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0683849d-20a2-4c69-b9ba-e87452f76bae%2F7_20160111_001.png)

J'ai rapidement mis un `background: none` sur `footer_map` pour tester.

A toi de jouer now ;)

**Comment by M4rtine** [comment]
;)

**Comment by foutoucour** [comment]
Par contre, avec ma maniere, j'ai remarque je pouvias pas utiliser les `+` et `-`. Il sont visible mais sous le bg :(

**Comment by M4rtine** [comment]
Ok je vois comment faire

**Comment by M4rtine** [comment]
J'ai cleaner certains controleurs et j'ai déplacé ceux concernés


![uploads/6b46b30a-bb65-43b0-b11f-2ae1a006731e/cgsm-#440-uicontrols.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6b46b30a-bb65-43b0-b11f-2ae1a006731e%2Fcgsm-%23440-uicontrols.jpg)
