### ISSUE TITLE
En tant que Web-Designer je voudrais corriger la taille des barres de recherches qui ne sont pas en pleine largeur seulement sous FIREFOX.

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#448]
La largeur de la barre de recherche ne se comporte pas bien dans firefox

**Comment by MangoJazz** [comment]
fixed

**Comment by M4rtine** [comment]
@mangojazz tu as fix ce problème ?



--

**Comment by MangoJazz** [comment]
Non jordi ma dit que toi oui

**Comment by foutoucour** [comment]
won't do.

Nouveau design de la barre de recherche
