### ISSUE TITLE
Faire une search sur click sur geochart

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#465]
Lorsque l'utilisateur click sur un pays, il est redirigé vers la page de map avec la recherche sur le pays cliqué.

**Comment by foutoucour** [comment]
Qu'est ce que tu en penses @M4rtine ?

**Comment by M4rtine** [comment]
Oui c'est une bonne idée

--

**Comment by foutoucour** [comment]
suivre http://stackoverflow.com/questions/14692641/geochart-trigger-a-function-on-select
