### ISSUE TITLE
Design of backoffice map

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#48]
see https://snazzymaps.com/style/6736/outspoken

**Comment by M4rtine** [comment]
https://snazzymaps.com/style/19955/flat-colors
simple and clear

**Comment by M4rtine** [comment]
this one is interesting for customizing with our colors 
https://snazzymaps.com/style/13289/ajt-mapstyle-1

**Comment by foutoucour** [comment]
Love them.

How long to you think it will take to customize the second one?

On Sat, Apr 25, 2015 at 6:14 AM, David Mazeau <notifications@github.com>
wrote:

> this one is interesting for customizing with our colors
> https://snazzymaps.com/style/13289/ajt-mapstyle-1
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96174105>
> .
>



-- 
- Jordi Riera, Connecting Softwares and people.
+1 438 930 3718
www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
show me the js where the api Google is loading.

**Comment by foutoucour** [comment]
I think we will move away from google map in fact.

It is really slow and bugged.
We can switch to openStreetMap or to mapBox (https://www.mapbox.com/) what
do you think?

On Sat, Apr 25, 2015 at 11:42 AM, David Mazeau <notifications@github.com>
wrote:

> show me the js where the api Google is loading.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96229219>
> .
>



-- 
- Jordi Riera, Connecting Softwares and people.
+1 438 930 3718
www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
Mapbox us toi expensive and not a good solution
I have allready try

Le samedi 25 avril 2015, Jordi Riera <notifications@github.com> a écrit :

> I think we will move away from google map in fact.
>
> It is really slow and bugged.
> We can switch to openStreetMap or to mapBox (https://www.mapbox.com/) what
> do you think?
>
> On Sat, Apr 25, 2015 at 11:42 AM, David Mazeau <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > show me the js where the api Google is loading.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96229219
> >
> > .
> >
>
>
>
> --
> - Jordi Riera, Connecting Softwares and people.
> +1 438 930 3718
> www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96232463>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by foutoucour** [comment]
Ok then.

So openstreetmap it is. Need to find a way to make it sexy. It is not for
now :(

On Sat, Apr 25, 2015 at 12:16 PM, David Mazeau <notifications@github.com>
wrote:

> Mapbox us toi expensive and not a good solution
> I have allready try
>
> Le samedi 25 avril 2015, Jordi Riera <notifications@github.com> a écrit :
>
> > I think we will move away from google map in fact.
> >
> > It is really slow and bugged.
> > We can switch to openStreetMap or to mapBox (https://www.mapbox.com/)
> what
> > do you think?
> >
> > On Sat, Apr 25, 2015 at 11:42 AM, David Mazeau <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > show me the js where the api Google is loading.
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96229219
> > >
> > > .
> > >
> >
> >
> >
> > --
> > - Jordi Riera, Connecting Softwares and people.
> > +1 438 930 3718
> > www.linkedin.com/in/jordirieracg/ <
> http://ca.linkedin.com/in/jordirieracg/
> > >
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96232463
> >
> > .
> >
>
>
> --
>
> ____________________________
>
> *david.mazeau*
> *06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96233097>
> .
>



-- 
- Jordi Riera, Connecting Softwares and people.
+1 438 930 3718
www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
http://maps.stamen.com/#terrain/12/37.7706/-122.3782
Idea for custom
But i think in dashboard the design is less important than home page

Le samedi 25 avril 2015, Jordi Riera <notifications@github.com> a écrit :

> Ok then.
>
> So openstreetmap it is. Need to find a way to make it sexy. It is not for
> now :(
>
> On Sat, Apr 25, 2015 at 12:16 PM, David Mazeau <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Mapbox us toi expensive and not a good solution
> > I have allready try
> >
> > Le samedi 25 avril 2015, Jordi Riera <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :
> >
> > > I think we will move away from google map in fact.
> > >
> > > It is really slow and bugged.
> > > We can switch to openStreetMap or to mapBox (https://www.mapbox.com/)
> > what
> > > do you think?
> > >
> > > On Sat, Apr 25, 2015 at 11:42 AM, David Mazeau <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > >
> > > > show me the js where the api Google is loading.
> > > >
> > > > --
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96229219
> > > >
> > > > .
> > > >
> > >
> > >
> > >
> > > --
> > > - Jordi Riera, Connecting Softwares and people.
> > > +1 438 930 3718
> > > www.linkedin.com/in/jordirieracg/ <
> > http://ca.linkedin.com/in/jordirieracg/
> > > >
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96232463
> > >
> > > .
> > >
> >
> >
> > --
> >
> > ____________________________
> >
> > *david.mazeau*
> > *06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96233097
> >
> > .
> >
>
>
>
> --
> - Jordi Riera, Connecting Softwares and people.
> +1 438 930 3718
> www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/48#issuecomment-96239485>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by M4rtine** [comment]
i found a way to customize openstreetmap with a css approach 
it's cool and openstreetmap is Closer that cg studio map idea

**Comment by foutoucour** [comment]
The look of the map has been update to mapQuest Open (http://www.openstreetmap.org/#map=14/45.5293/-73.6036&layers=Q)

![screen shot 2015-04-28 at 12 02 19 pm](https://cloud.githubusercontent.com/assets/547282/7374181/b029b0d0-ed9e-11e4-9eb2-365e25643610.png)

@M4rtine Can you let me know if it is good enough for you?

**Comment by M4rtine** [comment]
http://openlayers.org
i don't know if it help
