### ISSUE TITLE
Rajouter Ubisoft Quebec

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#490]
Il semble qu'il nous manque Ubisoft Quebec City.

Tu peux trouver les infos en suivant cette page:
https://www.google.ca/search?q=ubisoft+quebec+city&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a&channel=fflb&gfe_rd=cr&ei=OUeeVtuLJcyC8Qf95ohI

**Comment by MangoJazz** [comment]
fait aussi merci
