### ISSUE TITLE
Rajouter Frima Quebec city

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#491]
Il semble qu'il nous manque Frima de Quebec City.

Merci de le rajouter quand tu as le temps :)

https://www.google.ca/search?q=frima+quebec+city&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a&channel=sb&gfe_rd=cr&ei=2EeeVtu8LcyC8Qf95ohI

**Comment by MangoJazz** [comment]
fait, merci

Par contre c'est vraiment difficil de rajouter un studio, Ca m'a pris 5 minutes avant de trouver mon dashboard.
