### ISSUE TITLE
Directory Nav update

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#492]
Equilibrage des couleurs par rapport à l'usage et aussi au design de la page edition.

Tendre vers ça : 

![uploads/11918a9b-b380-4e12-bc00-de85356f3d86/cgsm-webdesign-2016-01-directory-list.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F11918a9b-b380-4e12-bc00-de85356f3d86%2Fcgsm-webdesign-2016-01-directory-list.jpg)

**Comment by MangoJazz** [comment]
le lien ne fonctionne pas.

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2016-01-19 18:31 GMT-05:00 David Mazeau <notifications@github.com>:

**Comment by M4rtine** [comment]
ça sera ça pour le moment.


![uploads/e1b38bbf-9dbf-4baa-a5a9-c22e241a63ed/cgsm-#492-navDirectory.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe1b38bbf-9dbf-4baa-a5a9-c22e241a63ed%2Fcgsm-%23492-navDirectory.jpg)
