### ISSUE TITLE
Email quand un lead est crée

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#511]
Pour le moment, il est difficile de suivre les personnes qui nous contacte à travers le formulaire `contact us` car il n'y a aucune notification n'est lancée.

Pour aider le suivi, un nouveau module va être créer: `email_new_lead`
L'email sera envoyé a tous les `Sales Manager` afin de permettre une administration plus facile que si l'email était envoyé qu'a un email donné

**Comment by MangoJazz** [comment]
Pour le moment l'email semble être set-up:  info@cgstudiomap.org

sauf que cette adresse ne va nullepart.
Peut-on la lier à cgstudiomap@gmail.com?

**Comment by MangoJazz** [comment]
voir #649
