### ISSUE TITLE
Design-Studio

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#514]
Intégrer le design de la page studio pour tous les utilisateurs.

**Comment by M4rtine** [comment]
@foutoucour 
Tu pourrais me donner les syntaxes des tailles des images
pour le moment dans frontend_base y'a ça
t-att-src="website.image_url(partner, 'image_small')

Mais comme maintenant je gère la taille des images en CSS il faudrait que j'ai une taille plus grande.
Pour les écrans retina ça sera mieux aussi.
Je remplace 'image_small' par quoi ?

**Comment by foutoucour** [comment]
j'ai pas d'instance ouverte, tu peux essayer:
- `image` (1024x1024 max)
- `image_medium` (128x128 max)

Normalement tu peux aussi specifier une taille en faisant `website.image_url(partner, 'image_medium', size='80x80')`

Dis moi si ca marche pour toi.

Jordi

**Comment by M4rtine** [comment]
merci

**Comment by M4rtine** [comment]
Ok ça marche par contre certaines images ne sont pas bien traités.
Par exemple une image en png transparente envoyé en 64x64 le serveur fais le 128x128 juste en agrandissant le canvas mais sans mettre une couleur.
du coup on a pas l'impression qui retaille l'image.

ex :
/website/image/res.partner/535_a7d9726/image_medium/128x128

**Comment by M4rtine** [comment]
2eme question peut on relancer un batch de tous les logos mais avec une meilleure compression des jpg ?

**Comment by foutoucour** [comment]
tous ne sont pas des jpg, ca parait compliquer pour le moment,

pourquoi?

On Mon, Jan 25, 2016 at 8:47 AM David Mazeau <notifications@github.com>
wrote:

> 2eme question peut on relancer un batch de tous les logos mais avec une
> meilleure compression des jpg ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/514#issuecomment-174513858>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
je vais trouver une solution ;)

**Comment by M4rtine** [comment]
J'ai trouvé des solutions je t'expliquerai la version def

--

**Comment by M4rtine** [comment]
@foutoucour question formatage

si je veux écrire ceci : 
```
<a href="tel://1-555-555-5555">+1 (555) 555-5555</a>
```
J'ai tenté ça mais ça marche po :(
```
<a t-att-href="tel://'partner.phone'"><t t-esc="partner.phone" /></a>
```

**Comment by foutoucour** [comment]
essaie
<a t-att-href="tel://{0}".format(partner.phone)>

ou
<a t-att-href='"tel://{0}".format(partner.phone)'> (le tout entre simple
guillemet)

On Thu, Jan 28, 2016 at 6:38 AM David Mazeau <notifications@github.com>
wrote:

> @foutoucour <https://github.com/foutoucour> question formatage
>
> si je veux écrire ceci :
>
> <a href="tel://1-555-555-5555">+1 (555) 555-5555</a>
>
> J'ai tenté ça mais ça marche po :(
>
> <a t-att-href="tel://'partner.phone'"><t t-esc="partner.phone" /></a>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/514#issuecomment-176138006>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
nickel ça marche

**Comment by M4rtine** [comment]
@foutoucour Pourquoi le module de Recherche ne marche pas avec ce code ?
"'NoneType' object is not callable" while evaluating
'keep(url, search=0, company_status=company_status)'


```
<form t-att-action="keep(url, search=0, company_status=company_status)" method="get" t-att-class="search_class">
<div class="input-group navSearch">
<input type="text" name="search" class="search-query form-control" placeholder="Search..." t-att-value="search" />
<input type="hidden" name='company_status' t-att-value='company_status' />
<span class="input-group-btn">
<a class="btn btn-lg a-submit"><span class="fontCGSMicons">search</span></a>
</span>
</div>
</form>
```

**Comment by M4rtine** [comment]
tu penseras à me répondre ;)
@foutoucour

**Comment by foutoucour** [comment]
Il manque une référence pour que `keep`marche dans la template.

On aime beaucoup la fiche. Très simpas.

On a eut du mal a trouver le bouton `edit` par contre. 
Tu pourrais trouver un meilleur endroit?
