### ISSUE TITLE
En tant que WebDesigner, je voudrai optimiser le temps de chargement du site en mettant dynamiquement sur chaque images du site des options de hauteur et de largeur (image dimensions attributes)

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#520]
> Specify image dimensions
> Specifying a width and height for all images allows for faster rendering by eliminating the need for unnecessary reflows and repaints.

reference : 
https://gtmetrix.com/specify-image-dimensions.html

Il faudrait avoir un truc du genre :
```
<img src="logo.jpg" alt="studio name" height="42" width="42">
```

**Comment by foutoucour** [comment]
Est ce que c'est toujours d'actualité ce point? 
Si oui, qu'elle est la priorité stp.

**Comment by M4rtine** [comment]
C'est de l'optimisation pour le temps de chargement du site. C'est pas prioritaire mais il faut le faire pour la mise en ligne public de la page studio. Il y aura des images.

Quand on spécifie pas la taille c'est l'explorateur qui lance une vérif pour chaque image de quelle taille est l'image et a quelle taille elle doit être.

C'est prioritaire mais pas pour nous seulement pour les utilisateurs. 
Tu peux imaginer une solution globale qui gère toutes les images du site.

**Comment by M4rtine** [comment]
En attente des templates finalisées

**Comment by M4rtine** [comment]
en fait c'est bon sur ce point ;)
