### ISSUE TITLE
Probleme ajout studio

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#521]
Si quelqu'un arrive à comprendre:
Le studio Stargate à Malte n'arrive pas à se geolocaliser, il renvoit le studio à New York ou en plein mileiu de l'océan. Meme Google map ne le trouve pas pourtant l'adresse est bien indiquée sur le site:
http://www.stargatestudios.net/malta-studio/

J'ai tout essayé mais ça ne veut rien savoir:
2 Piazzetta Aparts, Triq l-Arzella
Bahar ic-Caghaq, NXR 5192, MALTA

Je l'ai désactivé pour le moment avant de casser mon clavier n cinq.
Merci de me laisser savoir si vous y arrivez!

**Comment by M4rtine** [comment]
Google map ne le trouve pas non-plus
il doit y avoir trop de détails mal écris.

**Comment by M4rtine** [comment]
En fait sur le site de "Stargate Studio" ils ont un bug pour les caractère de la langue maltaise. Le site internet interprète mal et rajoute des TIRETS.

**Comment by foutoucour** [comment]
Il faudrait que tu contactes stargate studios pour qu'on ait la bonne adresse. Ca permettra aussi de se faire connaitre aupres du studio

**Comment by M4rtine** [comment]
Carrément

**Comment by MangoJazz** [comment]
@MangoJazz à contacter

**Comment by MangoJazz** [comment]
fait :) je me mets un rappel pour faire un suivi
