### ISSUE TITLE
Le mot Homepage incorrect

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#522]
Le mot homepage est écrit sans 'e' lorsqu'on fait une recherche sur google:
CG Studio Map | Hompage

**Comment by foutoucour** [comment]
J'ai mis a jour le titre.

Ca sera mis en ligne a la prochaine mise en production

![uploads/a403180b-7819-4575-a720-fcf3d443068f/8_20160125_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa403180b-7819-4575-a720-fcf3d443068f%2F8_20160125_001.png)
