### ISSUE TITLE
Erreur lors de la mise à jour du champ "facebook" sur une fiche de studio

### ISSUE THREAD

**Issue by juli1r** [cgstudiomap/cgstudiomap#524]
Se rendre sur une fiche de studio et copier "https://www.facebook.com/?_rdr=p" ou tout autre lien facebook.

S'en suit le message d'erreur ci-dessous:
-------
ValidateError

Error while validating constraint

_validate_social_network_url() takes exactly 4 arguments (3 given)
---------

C'est arrivé sur une fiche de studio d'italie, je ne pense pas que le pays joue un rôle sur cette erreur cela dit.

Bon courage.
![uploads/1e30b9e6-6121-487c-8a46-460488f593b8/Open For Business - Odoo 2016-01-26 20-21-47.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1e30b9e6-6121-487c-8a46-460488f593b8%2FOpen+For+Business+-+Odoo+2016-01-26+20-21-47.png)

**Comment by M4rtine** [comment]
Ce n'est pas que Facebook c'est la totalité de l'onglet 
" Additional Social Networks"
