### ISSUE TITLE
Page list/map: En tant qu'utilisateur, je voudrais pouvoir utiliser le bouton search (loupe) pour lancer mes recherches

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#528]
Le bouton search dans les pages map et listing ne fonctionnent plus alors que la recherche se lance sur `enter`.

Trouver pourquoi et faire une PR contre `develop` pour mettre a en ligne

**Comment by foutoucour** [comment]
Le bug venait que le js qui s'applique a `a-submit` etait dans les js d'odoo et pas nos js.

**Comment by M4rtine** [comment]
ah bin cool
