### ISSUE TITLE
Fiche Studio: En tant qu'utilisateur non loggué, je voudrais facilement voir si un studio est fermé ou pas, et ceci dans les pages studio (fait), list et carte.

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#529]
Il faut trouver une facon de montrer qu'un studio est actuellement ferme.

L'information doit etre disponible sur plusieurs pages:
* [ ] sur la page de liste, on a la possibilite de filtrer les studios par leurs status. Il faudrait donc arriver a differencier les studios fermes et ouvert.
* [ ] Pareil pour la carte
* [x] Sur la fiche studio montrer que le studio est ferme.

**Comment by M4rtine** [comment]
Je suis dessus ;)


![uploads/f98f35ac-b5cb-46c9-a773-48a19fb76ac8/#529_studio-closed.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff98f35ac-b5cb-46c9-a773-48a19fb76ac8%2F%23529_studio-closed.jpg)

**Comment by M4rtine** [comment]
@foutoucour 
Rajoutes moi s'il te plait au moins 1 studio qui est fermé dans ma database.
merci

**Comment by foutoucour** [comment]
J'ai ferme deux studios dans ta base de donnee :p

il suffit de cliquer sur le bouton set as closed dans le back office :)

**Comment by M4rtine** [comment]
punaise je suis nul :D

**Comment by M4rtine** [comment]
J'attend le pull request #590

**Comment by M4rtine** [comment]
@foutoucour 
Quand je click sur "Edit" y'a cette erreur :(

Error message:
"'dict' object has no attribute 'state'" while evaluating
"partner.state == 'closed'"

**Comment by foutoucour** [comment]
je regarde

**Comment by foutoucour** [comment]
solved

**Comment by M4rtine** [comment]
@foutoucour sur le listing et la map, je ne sais pas quel est la méthode de condition, vu que l'on charge le logo du listing dans le fichier listing.py
et l'info windows de la map est en js.

**Comment by M4rtine** [comment]
![uploads/465adcaf-63ac-4e16-8e0e-8a2976657e33/cgsm-#529-wip-closed.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F465adcaf-63ac-4e16-8e0e-8a2976657e33%2Fcgsm-%23529-wip-closed.jpg)

**Comment by M4rtine** [comment]
Nan mais en fait je viens d'y penser mais est ce que c'est vraiment utile de voir une icone sur les studios fermés depuis la map et le listing ?

Dans le futur quand y'aura à côté de "closed" popular, last ou d'autres filtres on ne fera pas de code par dessus les logos en fonction de leur états.

@foutoucour 
Est ce que symbolisé "closed" dans la fiche studio est suffisant ?
