### ISSUE TITLE
Map_info on backoffice

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#53]
The map_info is the pop up that display details about the company on the map view:
![screen shot 2015-04-24 at 12 09 27 pm](https://cloud.githubusercontent.com/assets/547282/7323190/d2ee915c-ea7a-11e4-925d-d82b7c7bff4d.png)

It displays information we don't necessary needs at this point, like the id, and it is not a given order.

Replace it with a pop up inspired by
![cgsm-graphic-identity-wip-05](https://cloud.githubusercontent.com/assets/547282/7323219/f6ae30de-ea7a-11e4-8da8-3ae3db958ffa.jpg)

**Comment by foutoucour** [comment]
Fixed by #54 
![screen shot 2015-04-24 at 5 16 34 pm](https://cloud.githubusercontent.com/assets/547282/7328720/c4b09574-eaa5-11e4-97ec-c1d9a7f571e2.png)

**Comment by foutoucour** [comment]
ping @M4rtine : Need to do the design of the pop up now :)

**Comment by foutoucour** [comment]
Design of the map_info overlay for the milestone 0.1

![screen shot 2015-05-06 at 1 44 14 pm](https://cloud.githubusercontent.com/assets/547282/7499495/0b20df1a-f3f6-11e4-97c4-4864cbb42560.png)

**Comment by M4rtine** [comment]
Nickel
Comme v01 ;)

Le mercredi 6 mai 2015, Jordi Riera <notifications@github.com> a écrit :

> Design of the map_info overlay for the milestone 0.1
>
> [image: screen shot 2015-05-06 at 1 44 14 pm]
> <https://cloud.githubusercontent.com/assets/547282/7499495/0b20df1a-f3f6-11e4-97c4-4864cbb42560.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/53#issuecomment-99550112>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*
