### ISSUE TITLE
Fiche studio: En tant qu'utilisateur non logue, je souhaite pouvoir flaguer des fiches

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#530]
Pour faciliter la purge de la base de donnee, permettre a des utilisateurs de flaguer une fiche.

Deux flags sont mis en place pour le moment:
* [ ] studio fermé
* [ ] mauvaise information

Pour ca, dans un permier temps, implementer les fields dans res.partner qui permettra de garder l'information sur le studio.
Ajouter les champs:
* [ ] flagged_closed. champs boolean
* [ ] flagged_missing_details: champs boolean.

Dans un deuxieme temps, mettre en place les conditions dans les templates.

**Comment by M4rtine** [comment]
Ready #644
