### ISSUE TITLE
En tant qu'utilisateur, je voudrais que les liens vers les réseaux sociaux, présent dans le footer, s'ouvrent dans une nouvelle fenetre

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#533]
Ce type de comportement a l'air classique et attendu par l'utilisateur.

@M4rtine Est ce que ca te pose probleme?

**Comment by M4rtine** [comment]
@foutoucour
Pas de problème. C'est une très bonne remarque

**Comment by M4rtine** [comment]
@foutoucour
J'ai appliqué une méthode plus flexible pour l'avenir.
En JS je rajoute l'attribut automatiquement sur les classes que je vise. Si on rajoute des icones ou si on veut appliquer cette méthode ailleurs pas la peine de remplir les templates de lignes en trop.

```
$(".socials a").attr('target', '_blank');
```

ici tous les liens (a) dans la classe (socials) auront cette propriété. Quand je changerait les icones je n'aurais pas à m'en préoccupé.
