### ISSUE TITLE
En tant qu'utilisateur, je voudrais pouvoir réorganiser la liste par colonne.

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#534]
Il faudrait permettre en cliquant sur le header d'une colonne du listing de réorganiser l'ordre du listing.

**Comment by M4rtine** [comment]
Je check pour savoir pourquoi ca ne le fais pas.

**Comment by M4rtine** [comment]
Ok c'est bon. Avec la méthode de création des colonnes différentes de celle que j'avais fais en local il fallait simplement mettre l'option dans le .js

```
columns: [{ field: 'location', title: 'Location',sortable: true }],
```
