### ISSUE TITLE
En tant qu'utilisateur, je vois le div de la geochart passer par dessus le reste de la page.

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#539]
voir les screen shot suivant.

![uploads/166908a8-1d3a-4a4c-9b18-4ef02127b063/b_20160131_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F166908a8-1d3a-4a4c-9b18-4ef02127b063%2Fb_20160131_001.png)

![uploads/7d56b0b6-4b5b-46ef-bd01-ccc2ecb614cb/4_20160131_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7d56b0b6-4b5b-46ef-bd01-ccc2ecb614cb%2F4_20160131_001.png)

On voit que la finland et le brazil deborde.

**Comment by M4rtine** [comment]
ah ah
quel idée d'avoir d'autres pays disponible ^^

**Comment by M4rtine** [comment]
![uploads/ab9542cc-4450-43f2-a5f7-f3d0304c0cb0/cgsm-#539-bug-zindex.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fab9542cc-4450-43f2-a5f7-f3d0304c0cb0%2Fcgsm-%23539-bug-zindex.jpg)

**Comment by foutoucour** [comment]
:+1:
