### ISSUE TITLE
Docker for odoo 

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#57]
https://www.docker.com/whatisdocker/

https://registry.hub.docker.com/u/library/odoo/

**Comment by foutoucour** [comment]
Yeah, I need to build a docker to ease the install.

As I am using a home made script to install all the dependencies, we can't
use these dockers out of the box :(

On Sat, Apr 25, 2015 at 6:49 AM, David Mazeau <notifications@github.com>
wrote:

> https://www.docker.com/whatisdocker/
>
> https://registry.hub.docker.com/u/library/odoo/
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/57>.
>



-- 
- Jordi Riera, Connecting Softwares and people.
+1 438 930 3718
www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>
