### ISSUE TITLE
En tant qu'utilisateur, je souhaite voir une section à propos de

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#577]
Préparer une section about voir avec David pour le design des images ensuite.
- Mini history about the cie
- Who is behind the project
- What cg Studio Map is

**Comment by MangoJazz** [comment]
l'idée de @M4rtine de mettre des images illustrant chaque personne, est bien.

**Comment by foutoucour** [comment]
est ce http://cgstudiomap.org/aboutus suffit?

**Comment by M4rtine** [comment]
oui c'est bon. au pire on a le cadre si il fault rajouter des explications
on le fera au fure et a mesure. si ya des questions qui reviennent.

>

--
