### ISSUE TITLE
En tant que Designer, je voudrais mettre en page la page Save qui est affichée après qu'un utilisateur aie mise à jour un studio

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#582]
La page, mise en place dans #580,  a été désigner à l'arrache et aurait surement besoin de ton aide pour la rendre plus simpas.

Je voudrais que la page montre qu'on est conscient que l'utilisateur vient de nous rendre service, a fait une bonne action.

![uploads/fe3da07e-47b9-45b9-9d12-7df7f0536f11/c_20160204_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffe3da07e-47b9-45b9-9d12-7df7f0536f11%2Fc_20160204_001.png)

**Comment by foutoucour** [comment]
En attente des commentaire de @MangoJazz dans #583

**Comment by MangoJazz** [comment]
voila ce que je mettrais voir #583 avec le beau design de David.
COMPANY SUCCESSFULLY UPDATED
THANK YOU FOR YOUR CONTRIBUTION

pour mettre `jour d'autres studios voir #586 (pop-up window)

**Comment by M4rtine** [comment]
J'ai fais plus simple ;)


![uploads/ef043d52-94f3-454a-9e71-7ace5a25bbc3/cgsm-#582-savepage.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fef043d52-94f3-454a-9e71-7ace5a25bbc3%2Fcgsm-%23582-savepage.jpg)

**Comment by foutoucour** [comment]
@MangoJazz qu'est ce que tu en penses?

**Comment by foutoucour** [comment]
Revision mineure du texte.

![0_20160214_001](https://cloud.githubusercontent.com/assets/547282/13038001/798a2b70-d35a-11e5-8445-b73fa3c40dcf.png)

Tres sympas l'ambiance!

**Comment by foutoucour** [comment]
@M4rtine fait attention quand tu modifies le texte, il y avait des fautes d'anglais :( c'est pour ca que je demande a @MangoJazz d'intervenir dans nos textes.
