### ISSUE TITLE
En tant que Chargé de la clientèle,  je voudrais revoir le message mis sur la page de remerciement pour l'édition d'un studio

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#583]
Un nouvelle page a été mis en place dans #580.
Elle a pour but de remercier lorsqu'un utilisateur met à jour un studio.

Le texte actuel est:
```
Thank you!
The company 160over90 details have been successfully updated! Thank you for your contribution.
You can go back to the page of the company or look for more companies to update!
```

Il faudrait voir comment l'améliorer pour rendre le message très positif et que la personne se sente glorifier.

Voila comment est la page sans design.
![uploads/d4274422-1c16-4ddb-ab5a-a2df656ce0b5/c_20160204_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd4274422-1c16-4ddb-ab5a-a2df656ce0b5%2Fc_20160204_001.png)

**Comment by MangoJazz** [comment]
Je pensais à un texte cour:
COMPANY SUCCESSFULLY UPDATED
THANK YOU FOR YOUR CONTRIBUTION

{la carte avec le curseur qui envoie vers la fiche}
Une fois sur la fiche une pop-up invitant à editer d'autres fiches voir issue

**Comment by MangoJazz** [comment]
@foutoucour @M4rtine qu"en pensez-vous?

**Comment by foutoucour** [comment]
Ca me va tout a fait!
