### ISSUE TITLE
Pop-up Window - Mise à jour studio

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#586]
Lorsqu'un utilisateur met à jour un studio, il a un thank you voir tache #583, puis la map avec curseur les envoie vers la fiche mise à jour. Afin de motiver les utilisateurs à continuer à mettre à jour les fiches une fois qu'ils ont commencés, une fenetre devrait apparaitre leur disant:
CONTINUE YOUR GREAT WORK BY UPDATING THE NEXT STUDIO.

**Comment by M4rtine** [comment]
@MangoJazz Je ne pense pas qu'éditer plusieurs fiches l'une après l'autre est un comportement classique de nos utilisateurs.
C'est plutôt les contributeurs proches des modérateurs.
Je pense que ça se résume à de la consultation unique ou vérifier si son studio est bien référencé.
