### ISSUE TITLE
Eblast user pre release - Fev 2016

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#588]
Je pensais faire un eblast aux utilisateurs pour les tenir en haleine du travail qu'on fait et peut-etre annoncer un peu ce qu'il va se passer.

**Comment by M4rtine** [comment]
oui c'est bien

**Comment by MangoJazz** [comment]
@M4rtine je vais parler du nouveau design de la carte et ajouter une photo, veux-tu que je parle d'autre chose pour le moment?

@foutoucour que veux-tu mettre en avant de ton travail deja en ligne?

pour ce qui est à venir je pensais avoir une photo de la future fiche studio.
Pour le advanced find, je pense qu'il est encore trop tot pour en parler.

merci pour vos retours

**Comment by M4rtine** [comment]
Parler du fait que la carte est plus interactive et réactive
Aussi ca peut être bien de parler de stats de studios de manière ludique
sous forme de question
Par exemple : le saviez vous ?
Et le shop

>
>

--

**Comment by MangoJazz** [comment]
@M4rtine le cout des anecdotes c'est pas mal, pour eviter de trop en mettre, peut-etre choisir un studio par envoi?

**Comment by foutoucour** [comment]
Screen shot de la nouvelle page studio:

![uploads/6344ebcb-a008-476c-8066-48b3474baa24/c_20160209_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6344ebcb-a008-476c-8066-48b3474baa24%2Fc_20160209_001.png)

**Comment by foutoucour** [comment]
Image pour illustrer le nettoyage de la base de donnees:


![uploads/7746c824-05a0-424a-87d1-1e542ed8595d/broom-header.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7746c824-05a0-424a-87d1-1e542ed8595d%2Fbroom-header.png)

**Comment by MangoJazz** [comment]
En attente de review et commentaires par @foutoucour et @M4rtine . merci

**Comment by MangoJazz** [comment]
scheduled for tomorrow 12pm.

**Comment by M4rtine** [comment]
@MangoJazz J'ai corrigé des détails graphiques mineurs

**Comment by M4rtine** [comment]
@MangoJazz tu peux remettre ton "scheduled for tomorrow 12pm"
je ne sais pas faire :(

**Comment by MangoJazz** [comment]
c'est fait.
