### ISSUE TITLE
En tant que Chargé du Marketing, j'ai besoin de savoir le coup qu'engendrerai l'ajout de nos utilisateurs dans Mailchimp

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#595]
MailChimp permet d'avoir 2000 emails gratuitement, après ca, les emails supplémentaires sont payant.

Il faudrait évaluer le coup qu'engendrerai l'ajout des emails des utilisateurs dans le mailchimp.
Nous avons deja 1600 slots utilisés par les compagnies. Nous comptons 3170 utilisateur au 9 Février.

Le coût nous permettra de voir la strategie pour les eblast user

**Comment by MangoJazz** [comment]
Pour cet envoi, nous avons payé à la carte 130$ pour 6000 emails, donc il nous en reste en banque.
Par mois cela couterait 45$, cependant je ne pense pas qu'on souhaite envoyer une infolettre tous les mois. A en discuter ensemble.
