### ISSUE TITLE
BUG MERGE edit studio page

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#604]

**Comment by M4rtine** [comment]
@foutoucour le merge ne s'est vraiment pas bien passé :(

**Comment by foutoucour** [comment]
comment ca?

**Comment by M4rtine** [comment]
il manque plein de trucs que j'avais fais

**Comment by foutoucour** [comment]
comme quoi?

**Comment by M4rtine** [comment]
je corrige ça me gave :(

**Comment by M4rtine** [comment]
Fix


![uploads/ccd655af-b6c9-42a4-9742-995b55100b19/cgsm-#604-bug-01.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fccd655af-b6c9-42a4-9742-995b55100b19%2Fcgsm-%23604-bug-01.jpg)


![uploads/7b1058a6-55a9-48af-b296-d11b0f7453fd/cgsm-#604-bug-02.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7b1058a6-55a9-48af-b296-d11b0f7453fd%2Fcgsm-%23604-bug-02.jpg)


![uploads/5d6c2639-9b14-48a9-9489-06152f232ff3/cgsm-#604-bug-03.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5d6c2639-9b14-48a9-9489-06152f232ff3%2Fcgsm-%23604-bug-03.jpg)
