### ISSUE TITLE
En tant qu'Utilisateur Enregistré, je voudrais accéder au nouveau design de la fiche du studio quand je clic sur "MORE" dans la page Directory/Map. Actuellement le lien va vers le dashboard.

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#613]

**Comment by foutoucour** [comment]
Ca sera fait automatiquement lorsque les détours pour que les beta testeurs puissent aller vers le nouveau design.

**Comment by foutoucour** [comment]
ouais la phrase veut rien dire, mais pour faire court, ca se reglera tout seul :)
