### ISSUE TITLE
En tant que Manager, je voudrais écrire les textes explicatifs de chaque onglets des fiches studios.

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#615]
Dans la page Edit d'un studio. C'est le bloc tout à droite en dessous de la catégories en orange

@MangoJazz pour le moment c'est du faux texte et c'est pas génial de laisser ça.

**Comment by MangoJazz** [comment]
C'est la section about du studio c'est ca?

**Comment by M4rtine** [comment]
Dans la page edit de chaque studio ;)

--

**Comment by MangoJazz** [comment]
oui oui j'ai vu, mais cela correspond bien à la section about des studios
c'est ca?

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2016-02-18 7:17 GMT-05:00 David Mazeau <notifications@github.com>:

**Comment by MangoJazz** [comment]
@M4rtine pourrais-tu me donner un lien d'un site qui le fait STP? merci

**Comment by M4rtine** [comment]
@MangoJazz je vais faire mieux.

COMMON details : 
- studio name : phrase simple pour dire que la langue utiliser pour l'écriture est l'anglais
- state : explication courte de closed et open
- logo : taille d'image préconisé 600x600 pixels (ratio 1:1) pas en dessous de 360pixels

LOCATION details : 
- exemple d'adresse écrite et voir les erreurs a ne pas mettre (je sais pas trop ça c'est toi qui sait ce que tu as vu sur les fiches)

LINKS details : 
- Site : example d'adresse web. L'adresse doit être la 1ère page d'accueil du site.
- Mail : phrase expliquant que l'adresse mail doit etre une adresse de contact direct (pas de mail de production , d'accords commerciaux et de mails de supervisieurs de spécialités)

SOCIALS details : 
- examples de lien social par reseaux social.

CALLS details :
- phrase expliquant le formatage des numéros de telephone et aussi rappeller que le site gere automatiquement les codes internationaux (+33,+44 +01 ...)

INDUSTRIES details : 
- phrase expliquant la logique global des TAGs industries (ex: remplissez la catégorie qui correspond au domaine d'activité du studio). Le choix de multiples tags est autoriser.

@foutoucour est ce que c'est correct ?

**Comment by foutoucour** [comment]
@M4rtine ca me parait très bien.
Pour faciliter la chose, j'ai mis en place un systeme pour que les textes puissent être modifiés à partir du dashboard. Donc on a pas a se prendre la tête pour que les textes soient parfait. Et on pourra même faire passer de la comm par ces champs.
J'essaierai de faire cette pratique plus souvent pour rendre le site plus facile â mettre a jour.
voir #658 pour des screenshots.

@MangoJazz prepare tes textes, on les mettra une fois que le site est en ligne.
et vu que le texte peut etre avoir des balises html, david pourra meme aider pour la mise en page :)

Pas mal non? :)

**Comment by M4rtine** [comment]
Super ;)



--

**Comment by MangoJazz** [comment]
les textes sont fait, ne reste plus qu'à mettre en ligne.

**Comment by MangoJazz** [comment]
En ligne

**Comment by M4rtine** [comment]
Merci ;)

--
