### ISSUE TITLE
En tant qu'utilisateur j'aimerais pouvoir trouver facilement le bouton fermer le studio

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#619]
je n'ai pas trouvé le bouton j'ai du demander à David qui m'a expliqué par la suite. Ce n'est pas flagrant, et je ne pense pas qu'un utilisateur va nous demander ou se trouve le bouton mais plutot nous envoyer un email pour qu'on le ferme. Dans la premiere version, Jordi a reçu des emails désagréables de users disant que la base de données n'etaient pas à jour. Donc si on montre facilement aux users qu'ils peuvent le faire eux-meme, ce sera plus simple pour tout le monde.

**Comment by M4rtine** [comment]
Corrigeons les bugs de ce qui est développé d'abord.
Les commentaires sur un ton négatif ne sont pas constructifs par définition. Plus les utilisateurs seront nombreux plus il faudra se confronter à ca.
Le truc bien là-dedans c'est que la communauté grandit

**Comment by MangoJazz** [comment]
@M4rtine il n'y a rien de negatif dans le ton que j'ai utilisé, surement de la frustration. 
La tache est en back log, donc rien d'urgent.

Soyons realistes ici, il y a deja tres peu d'utilisateurs qui mettent a jour la base de donnees presentement, alors rendons les taches simples. Et pour les emails recus ds la premiere version de CGSM, c'est bien vrai, Jordi repondait aux emails des utilisateurs, et ce n'etait pas souvent agreable. Mon point ici, est que si on montre aux utilisateurs qu'ils peuvent le faire eux-meme sans avoir a expliquer, on aura gagner. 
Comme le bouton "EDIT" par exemple: il fonctionne parfaitement, les gens commencent a l'utiliser.

Mais c'est certain que cette tache peut attendre.

**Comment by M4rtine** [comment]
@MangoJazz je parlais du ton négatif des gens qui râlent pas de toi. On a le même but 
Pas de problème dans ce que tu dis.

**Comment by MangoJazz** [comment]
ok cool, desolee j'avais mal compris. merci

**Comment by M4rtine** [comment]
même logique visuel que le bouton FLAG #644

**Comment by M4rtine** [comment]
![uploads/52a1c5d1-fbb4-4968-a074-e19bacbcc7a2/cgsm-#619-navEdit.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F52a1c5d1-fbb4-4968-a074-e19bacbcc7a2%2Fcgsm-%23619-navEdit.jpg)

**Comment by M4rtine** [comment]
Fix in #644

**Comment by MangoJazz** [comment]
Est-ce que le bouton "closed" permet de fermer le studio ou simplement de voir si le studio est fermé?

**Comment by M4rtine** [comment]
Le 'bouton' c'est toujours pour faire une action.

L'état ´closed est traité dans #529


--

**Comment by MangoJazz** [comment]
@M4rtine merci d'avoir travaillé sur cette tache.

Par contre, comme le bouton est une action, il faut enlever le "d" de close. En effet écrit comme tel, c'est une action déjà passée, le studio serait donc déjà fermé.
Merci

**Comment by M4rtine** [comment]
Ah oui ok je comprends la question ;)



--
