### ISSUE TITLE
Bug: fermeture d'un studio demandant adresse, studio sauvegarder sans informations.

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#620]
Reporté par Julien pour la fiche:
http://cgstudiomap.org/web#id=3434&view_type=form&model=res.partner&action=418

**Comment by MangoJazz** [comment]
voici un screen shot et le lien:
http://www.cgstudiomap.org/web#id=3434&view_type=form&model=res.partner&menu_id=353&action=418


![uploads/c430c8cc-9521-4b35-bb56-f2ceb771fbf6/Screen Shot 2016-02-20 at 3.22.08 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc430c8cc-9521-4b35-bb56-f2ceb771fbf6%2FScreen+Shot+2016-02-20+at+3.22.08+PM.png)

**Comment by foutoucour** [comment]
J'ai ferme le studio (mis non actif)

Le studio a été crée avant que les champs soient obligatoire.

Pour le fermer, j'ai mis une adresse fictive puis j'ai fermé le studio.
