### ISSUE TITLE
En tant qu'utilisateur j'aimerais voir le nom du studio quand je clique sur la map.

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#638]
Le nom du studio dans l'espace violet est en font transparent ou autre, mais il ne se voit plus. Il faut selectionner le texte pour le voir.

![uploads/322ed880-7e5b-4a14-ac21-d639ddff9eeb/Capture.PNG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F322ed880-7e5b-4a14-ac21-d639ddff9eeb%2FCapture.PNG)

![uploads/30db5a13-f000-40a5-b9f7-29a6f1d8f8d4/pipeline.PNG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F30db5a13-f000-40a5-b9f7-29a6f1d8f8d4%2Fpipeline.PNG)

**Comment by M4rtine** [comment]
ça ne le fait pas pour tous les studios. Je cherche


![uploads/ca7ecb80-5d45-4ae7-87de-c8953ce2f364/cgsm-#638-infowindows-bug.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fca7ecb80-5d45-4ae7-87de-c8953ce2f364%2Fcgsm-%23638-infowindows-bug.jpg)

**Comment by M4rtine** [comment]
En fait j'ai trouvé. Si vous mettez un mot dans la barre de recherche (exemple : canada, france, ou pipeline) les noms des studios qui étaient invisible sont bien visible.
donc ce problème n'apparait seulement quand la barre de recherche est vide.

@foutoucour je n'ai pas la moindre idée pourquoi y'a ce comportement :(

**Comment by foutoucour** [comment]
@M4rtine salut, j'ai fait 2 3 tests et j'ai l'impression que ça vient de la couleur de liens déjà visités. Tu penses pouvoir regarder ca ?

**Comment by M4rtine** [comment]
Oui si c'est bien ça c'est super simple. Est ce que le nom du studio est
devenu un lien où c'était déjà comme ça avant ?

**Comment by MangoJazz** [comment]
A mon avis c'est devenu un lien pour fixer le problème d'envoi vers une
page error lorsque on cliquait sur le nom du studio au lieu de more.

**Comment by M4rtine** [comment]
Parfait alors ça doit être ça. Je corrige ça ce soir heure française ;)

**Comment by M4rtine** [comment]
Done ;)
