### ISSUE TITLE
En tant qu'utilisateur je souhaiterais voir le logo quand je suis en mode liste.

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#642]
Le studio Kologanda a été ajouté et mis à jour hier. Le logo apparait bien dans la fiche pourtant en mode liste il n'est pas là.

![uploads/72afeae4-6fdd-4a43-b3cb-2cf54a388053/Screen Shot 2016-02-23 at 10.20.24 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F72afeae4-6fdd-4a43-b3cb-2cf54a388053%2FScreen+Shot+2016-02-23+at+10.20.24+PM.png)

![uploads/1db33565-2c63-4ed9-a86b-8b3b04b86bae/Screen Shot 2016-02-23 at 10.20.35 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1db33565-2c63-4ed9-a86b-8b3b04b86bae%2FScreen+Shot+2016-02-23+at+10.20.35+PM.png)

**Comment by M4rtine** [comment]
Le cache ?

**Comment by M4rtine** [comment]
Nan en fait c'est ton cache d'explorateur.

![issue 642-no](https://cloud.githubusercontent.com/assets/6338568/13284984/302b9cfc-daf8-11e5-98c0-aec43bae41a7.jpg)

**Comment by MangoJazz** [comment]
Je ne comprends pas. C'est possible d'expliquer  à une non technique? :)
merci

**Comment by M4rtine** [comment]
Ton explorateur internet stock en mémoire les sites pour naviguer plus vite
quand tu y retourneras. Le problème c'est que ce cache à des priorités de
lecture de fichiers et le type de fichier qui charge le listing n'est pas
en haut en priorité. Il faut soit se connecter en connection privée, soit
appuyer 2 fois sur actualiser, soit CTRL+F5 soit dans les paramètres de
Chrome (Firefox ou autre ) de ne pas mettre de cache ou de mettre le cache
à 0Mo comme ca il charge bien à chaque fois

--

**Comment by MangoJazz** [comment]
ok parce qu'avec Jordi on a fait refresh 3 fois, j'ai même fermé ma fenetre
et reouvert le site ensuite.

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2016-02-24 8:34 GMT-05:00 David Mazeau <notifications@github.com>:
