### ISSUE TITLE
En tant que Web-Designer je dois mettre en place le bouton 'FLAG' qui permettra aux utilisateurs non-enregistrés d'alerter les modérateurs d'un changement du studio

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#644]

**Comment by M4rtine** [comment]
![uploads/176d9450-5334-4d26-bff9-88ae528175ec/cgsm-#644-navEdit.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F176d9450-5334-4d26-bff9-88ae528175ec%2Fcgsm-%23644-navEdit.jpg)

**Comment by MangoJazz** [comment]
J'aime bien c'est un message simple et un bouton efficace.
