### ISSUE TITLE
En tant qu'Utilisateur Bêta, je voudrais pouvoir lire plus facilement le choix des industries.

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#646]

**Comment by foutoucour** [comment]
Hey,

Est ce que tu pourrais détailler un peu plus la tâche j'ai du mal a savoir ce qu'il y aurait a faire. Merci1

**Comment by M4rtine** [comment]
C'est trop brouillons les checkboxs que j'ai fais c pas lisible




--

**Comment by M4rtine** [comment]
@foutoucour c'est juste du design pas de code.

**Comment by M4rtine** [comment]
![uploads/61df7f3f-798c-4729-a6f9-a33ac57b81d2/cgsm-#646-bug-ind-checkbox.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F61df7f3f-798c-4729-a6f9-a33ac57b81d2%2Fcgsm-%23646-bug-ind-checkbox.jpg)
