### ISSUE TITLE
En tant qu'admin, j'aimerais recevoir une notification lorsque une demande se fait sur odoo par le formulaire contact.

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#649]
En effet les demandes restent sur odoo, je regarde une fois par semaine, mais pour etre plus proactive, ce serait bien de recevoir une notification. Meme principe que pour les studios mis à jour. Merci

**Comment by MangoJazz** [comment]
peux-tu te pencher dessus @foutoucour ?

**Comment by MangoJazz** [comment]
meme tache que #511

**Comment by foutoucour** [comment]
Plus d'actualité
