### ISSUE TITLE
En tant qu'utilisateur quand je clique sur le lien du site d'un studio, j'aimerais que le lien s'ouvre dans une autre page.

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#660]
Sur la nouvelle page studio, quand on clique sur le lien du site du studio, la page s'ouvre sur la meme page. Ce serait bien de l'ouvrir dans un autre onglet, afin de rester sur CG Studio Map.

![uploads/e1eaadfd-50ad-462f-a26d-7d103416d143/Screen Shot 2016-03-06 at 7.02.12 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe1eaadfd-50ad-462f-a26d-7d103416d143%2FScreen+Shot+2016-03-06+at+7.02.12+PM.png)

**Comment by M4rtine** [comment]
Déjà fait ça sur develop je le vois.

c'est pull request #674
