### ISSUE TITLE
Retravailler la phrase d'accroche sur la home page 

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#662]
Elle ne parle pas beaucoup, travailler dessus un peu plus pour que ce soit plus simple et clair.

![uploads/2d3ac010-a32c-44b9-a394-42b3c8df8754/Screen Shot 2016-03-06 at 7.14.49 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2d3ac010-a32c-44b9-a394-42b3c8df8754%2FScreen+Shot+2016-03-06+at+7.14.49+PM.png)

**Comment by MangoJazz** [comment]
@foutoucour @M4rtine 
Un petit texte d'intro à la place de la phrase?
BECAUSE EVERYONE SHOULD BE FAMILIAR WITH THE CG INDUSTRY
CG Studio Map is the premier open-data center of the computer graphic industry. Come in: update, share or simply read the content.

-----------
What is computer graphics?
Computer graphics (CG) are graphical elements created using a computer. 

You probably heard about 3D animated feature film, visual effects (VFX) and video game but there are many more areas where CG may be found: print design, web design or interactive mediums such as digital signage. This is why CG Studio Map has decided to gather them all in one place! 

We are the premier open-data center of the computer graphic industry where everyone can update, share or simply read the content.

**Comment by M4rtine** [comment]
Perso c'est le 2nd chapitre qui me dérange. C'est long et pas homogène. 

"You probably heard about 3D animated feature film, visual effects (VFX) and video game but there are many more areas where CG may be found: print design, web design or interactive mediums such as digital signage. This is why CG Studio Map has decided to gather them all in one place!"

3D animated feature film = computer-animated film
si on parle de visual effects on ne met pas VFX ou alors on met le tag pour tous les autres
video game = games

sur wikipedia ils mettent ça
"animation, movies, advertising, video games, and graphic design"
https://en.wikipedia.org/wiki/Computer_graphics

En fait plus c'est long le texte moins c'est lu et plus c'est dur de le rendre lisible.
Je n'ai pas la solution du wording ou de la synthése des phrases. Je vous partage mon avis.

Je design le texte tel qui l'a été écris.

**Comment by foutoucour** [comment]
On fait un essaie avec ce wording. Ca date de Mars. On a perdu le momentum sur ce tache. On mets en ligne et on voit si ca a un impact positif ou pas.

Et on ameliore au fur et a mesure :)

**Comment by M4rtine** [comment]
Je n'ai pas été clair. Je voulais dire exactement ça.
On essaye comme ça pas de soucis mes commentaires étaient pour l'améliorer
dans un futur proche

**Comment by MangoJazz** [comment]
Salut,

Dsl j'arrive à peine, pas de soucis je m'occupe de revoir la phrase :).

**Comment by foutoucour** [comment]
Je ferme cette issue comme son but etait de mettre a jour la catch phrase. Ce qui est fait.

J'ouvre une nouvelle pour la revision des termes utilises.
