### ISSUE TITLE
En tant qu'utilisateur, je voudrais avoir acces a de nouveaux filtres dans la page directory

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#687]
Il faudrait rajouter les filters:
- derniers studios modifies: `pp.search(session.cr, 1, [('create_date', '!=', False), ('active', '=', True), ('is_company', '=', True)], order='write_date desc', limit=10)`
- derniers studios ajoutes: `pp.search(session.cr, 1, [('create_date', '!=', False), ('active', '=', True), ('is_company', '=', True)], order='create_date desc', limit=10)`
- Les studios les plus populaires.

Les filtres doivent etre compatible avec les recherches faites par les utilisateurs.

**Comment by foutoucour** [comment]
@M4rtine a combien tu vois la limite pour les derniers studios? 10, 20, 50? Je prefererai le mettre en hardcodé pour le moment.

**Comment by foutoucour** [comment]
bloquée par #688

**Comment by M4rtine** [comment]
Limites ?

**Comment by foutoucour** [comment]
Dans le cas de la carte, il faut une facon visuelle de voir les derniers ajoutes, derniers crees. Autrement l'utilisateur va cliquer sur le filtre et ne verra aucune difference.

Ou est ce qu'on montre ce filtre que pour la liste?

**Comment by M4rtine** [comment]
Ah oui pardon, les 20 derniers sur la carte me paraît bien
En plus ca chargera plus vite




Le lundi 6 juin 2016, Jordi Riera <notifications@github.com> a écrit :

> Dans le cas de la carte, il faut une facon visuelle de voir les derniers
> ajoutes, derniers crees. Autrement l'utilisateur va cliquer sur le filtre
> et ne verra aucune difference.
>
> Ou est ce qu'on montre ce filtre que pour la liste?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/687#issuecomment-223945061>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGC4CA4vxXDcv2FcDsD7Tm-3z5VqsCWZks5qJBL9gaJpZM4IueHX>
> .
>


--
