### ISSUE TITLE
Problem editing studio

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#689]
When trying to edit a studio, when I click "Save Changes" I get this error:
![2016-06-07_13h53_41](https://cloud.githubusercontent.com/assets/1182452/15847333/a82107d6-2cb7-11e6-8c5f-aede48264717.png)

**Comment by foutoucour** [comment]
Hey @herronelou, thank you for the report. The bug has been reproduced and identified.

It is an error with our database system: http://gis.stackexchange.com/questions/97871/postgis-2-1-error-after-update

The package has been updated and the server should run better now.
Let me know if you can save the change you wanted to add.


Best,
Jordi

**Comment by herronelou** [comment]
Hey, I tried to do a round of editing today (especially the studios in Shanghai, their addresses are all formatted the wrong way, which causes the geolocators to be on the wrong spots). I'm still gettin this error on most studios I try to edit.

**Comment by M4rtine** [comment]
Thanks for helping is.
We are working to this type of issues. 
First geolocators will be improve and then some issues is caused by a bad user formatting.
Specially in India, China and Japan

**Comment by herronelou** [comment]
Yes, definitely bad user formatting here. But the issue I'm reporting is about not being able to edit them. Getting same error as original one on top.

**Comment by foutoucour** [comment]
I reopen the issue then.

**Comment by foutoucour** [comment]
@herronelou Could you let me know what you are trying to do?

* what studio did you try to update?
* what are the new data you put?

Thank you for you help, man!

**Comment by herronelou** [comment]
I got it with a few studios in Shanghai.
In all of them I was trying to format the address properly so that google maps would understand the exact location.
Our of memory it did in with MPC Shanghai (for sure) Pixomondo (I think) and Macklevision (not sure)

**Comment by herronelou** [comment]
Tried again today, I still can't edit some of these Chinese studios, with an "Oops" error message.

**Comment by M4rtine** [comment]
Montres nous un lien du studio sur lequel tu veux faire ça pour que je
puisse te dire ce qu'il ne va pas ;)
Merci


--

**Comment by herronelou** [comment]
http://cgstudiomap.org/directory/company/mpc-6037
J'essayais de formater l’adresse pour que Google maps place le marqueur au bon endroit.

**Comment by M4rtine** [comment]
Ok merci Erwan. Le problème était dû une cette fiche a été crée
anciennement avec un script de duplication qui gardait en mémoire l'Etat
d'un autre pays. J'ai corrigé le problème, actualisé l'adresse et rajouter
des liens sociaux.

Il devrait avoir de moins en moins d'erreur de ce genre.



--

**Comment by herronelou** [comment]
Tu dois les corriger 1 par 1 ou tu corriges en global?
Je eux te donner d'autres liens si c'est manuel.

*Erwan* LEROY
www.erwanleroy.com

2016-09-06 14:34 GMT+08:00 David Mazeau <notifications@github.com>:

**Comment by herronelou** [comment]
Les liens suivants ont une erreur de "State" en Chine:
http://cgstudiomap.org/directory/company/3dexcite-6241
http://cgstudiomap.org/directory/company/animated-storyboards-5867
http://cgstudiomap.org/directory/company/black-magic-design-5257
http://cgstudiomap.org/directory/company/fin-design-shanghai-2778
http://cgstudiomap.org/directory/company/glu-mobile-5925
http://cgstudiomap.org/directory/company/happy-finish-5778
http://cgstudiomap.org/directory/company/mackevision-5804
http://cgstudiomap.org/directory/company/mackevision-5803
http://cgstudiomap.org/directory/company/mokko-studio-china-5511
http://cgstudiomap.org/directory/company/original-force-6796
http://cgstudiomap.org/directory/company/pixomondo-6220
http://cgstudiomap.org/directory/company/pixomondo-6219
http://cgstudiomap.org/directory/company/xyz-6132
http://cgstudiomap.org/directory/company/smoke-and-mirrors-5834

*Erwan* LEROY
www.erwanleroy.com

2016-09-06 14:51 GMT+08:00 Erwan Leroy <herronelou@gmail.com>:

**Comment by M4rtine** [comment]
Merci encore 1 fois. Oui je suis obligé de le faire à la main mais aussi
parce que c'est une option que tu n'as plus accès.
Comme de toute manière ce sont des anciennes fiches c'est bien de les faire
1 par 1


--

**Comment by herronelou** [comment]
T'as pas moyen de convertir toutes les anciennes fiches en nouvelles d'un
coup, pour que ce soit editable par tout le monde? Ca te soulagerais
surement d'un poids.

*Erwan* LEROY
www.erwanleroy.com

2016-09-06 15:05 GMT+08:00 David Mazeau <notifications@github.com>:

**Comment by M4rtine** [comment]
Nan cest bon ça sert rien de créer une tâche automatisé pour une donnée que
l'on a plus maintenant

--

**Comment by herronelou** [comment]
Je vois.
Y'a moyen de corriger le bug qui fait que ce n'est pas editable par les
utilisateurs? (Oops, This is Embarrassing)

*Erwan* LEROY
www.erwanleroy.com

**Comment by M4rtine** [comment]
Ça devrait être bon pour le listing que tu m'a envoyé



--

**Comment by herronelou** [comment]
D'accord, mais j'ai seulement check les 30-40 studios en chine, rien
regardé d'autre.

*Erwan* LEROY
www.erwanleroy.com

**Comment by M4rtine** [comment]
Ça ne touchera que les studios dupliquer avant 2015 et qui ont donc
plusieurs studio dans le monde

Ca reste limité



--
