### ISSUE TITLE
Feature request: Flag Studio

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#690]
As I browse studio, I may notice some of them with incorrect information (wrong location on the map, error in the email address, etc..).
Although I could go through the trouble of finding the proper information and edit the page, I wish I had a quick way to flag an error, a little bit like Wikipedia does. 
I could flag an error and put a quick note of what error I noticed. People who have time to contribute more could consult the list of flagged studios and make sure the information is up to date.

**Comment by MangoJazz** [comment]
Merci Erwan pour ton idée :), c'est un très bon point.

On en a parlé il y a quelques mois avec l'équipe et oui c'est une feature qu'on souhaite offrir, mais elle n'est pas en developpement pour le moment.

Merci

**Comment by M4rtine** [comment]
@foutoucour c'est bon pour cette issue non ?

**Comment by foutoucour** [comment]
yup!

**Comment by herronelou** [comment]
J'ai vu le Flag, mais quand je clique dessus je ne peux pas cliquer "send", du coup on dirait qu'il ne se passe rien?
