### ISSUE TITLE
En tant que chargé de projet, je voudrais que les entrées de menu "Directory" et "Shop" soient plus parlant et actif pour l'utilisateur

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#691]
Il faudrait trouver des termes qui engagent plus l'utilisateur à interagir.

Ex pour directory: search, companies, map
Ex pour shop: support us

**Comment by M4rtine** [comment]
Ah mais search c'est bien et plus depuis la HomePage on fait apparaître la barre de recherche quand on clic sur search

**Comment by herronelou** [comment]
Personne ne m'a demande mon avis mais je le donne quand meme :)
Je pense que le shop devrait rester shop. Support us me fait penser a un "donate" paypal ou qqc comme ca, alors que shop est clair, ca renvoie vers des choses a acheter.
Pour Directory, je ne serais pas contre le remplacer par Map, mais pas search.
J'aurais plutot tendence a avoir une barre de recherche dans le header pour pouvoir chercher depuis n'importe quelle page.
J'ai fait quelaues changes vite fait avec photoshop pour quelques suggestions.
![cgsm](https://cloud.githubusercontent.com/assets/1182452/16253886/13b62a4c-386d-11e6-9b74-a9814a187b7a.png)
En mettant la barre de recherche dans le header ca libere presque une ligne quand tu regarde les maps, et avec tres peu de modifications il est facile de tout rentrer en une ligne: Plus d'espace pour les maps.
Bien que les icones pour changer entre MAP et Liste/directory ne soient pas mauvais, ils ne sont pas forcement intuitifs. Je pense qu'ajouter un peu de texte les rendrait plus instinctifs, ou alors les faire ressembler plus a des "radio buttons" ou un dropdown, pour que ce soit clair qu'on a le choix entre l'un ou l'autre. 
Add a studio j'aurais plutot mis un gros + qu'un symbole d'upload.
D'un coté tu a un gros bouton qui dit "Add Studio" et juste a coté un texte qui dit "2000 Companies". Au risque de sembler repetitif, je pense qu'il est important d'utiliser une nomenclature consistente partout. 
Et pour finir, les icones pour Twitter/Linkedin/Github ne sont pas facile a trouver, j'ai du chercher un moment pour retrouver le lien vers github.
Certains sujets sont peu-etre un peu hors sujet pour cette "issue" specifique mais j'espere que ca peut quand meme aider.

**Comment by M4rtine** [comment]
@herronelou
Merci pour cet avis. Il faut cependant essayer de ne parler que du sujet de l'intitulé de l'issue. Et du coup je ne vais répondre que sur ce sujet.
Pour le bouton map je comprends ton avis mais il faut voir aussi sur d'autres pages. L'idée du bouton search est mieux quand on se situe sur les autres pages. On pourrait ainsi lancer une recherche qui nous enverrai vers la page directory.
On gagne une action d'utilisateurs.

Pour le bouton shop/donate ce que tu décris est justement ce que l'on veut provoquer comme sensation pour l'utilisateur.

**Comment by MangoJazz** [comment]
Une phrase?

Find a (et on choisit le mot company, studio, business)

**Comment by foutoucour** [comment]
Comme dis dans #693, il vaudrait mieux aller vers `Search` pour eviter de donner l'impression de trouver tout le temps.

**Comment by MangoJazz** [comment]
et les quelques propositions que j'ai faite? As-tu vu?

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2016-06-23 8:42 GMT-04:00 Jordi Riera <notifications@github.com>:

**Comment by foutoucour** [comment]
:+1: Contribute
:+1: pour search a company

On peut essayer ca, voir les impactes. L'effort est pas enorme :)

**Comment by MangoJazz** [comment]
si tu utilises Search alors il faut ajouter 'for'

- Pour remplacer 'Directory': Search for a company ou alors Find a company
- Pour changer le mot 'shop' @foutoucour aime aussi 'contribute' 

@M4rtine @herronelou qu'en pensez-vous?

**Comment by M4rtine** [comment]
Ok pour contribute

**Comment by M4rtine** [comment]
Pour Search est ce que ça ira comme ceci pour la notion for ? @MangoJazz 

![searchfor](https://cloud.githubusercontent.com/assets/6338568/16329641/d7d0a5a2-39e3-11e6-9670-581333f78fdd.jpg)

**Comment by foutoucour** [comment]
:+1: Les deux sont bien.
@MangoJazz qu'est ce que tu en dis?

**Comment by MangoJazz** [comment]
@davidm Le second est bien search for...go

**Comment by MangoJazz** [comment]
@M4rtine est-ce que les noms seront changés dans le nouveau design?

**Comment by M4rtine** [comment]
Je ne peux rien faire comme modif je n'ai pas le serveur local fonctionnel

--

**Comment by M4rtine** [comment]
Traité ici #748

**Comment by foutoucour** [comment]
done in #755
