### ISSUE TITLE
Minor design issues/Refinement 

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#693]
Since #691 wasn't the ideal place to discuss these topics, I'm reposting in a separate issue.

I think there could be a few minor design adjustments that could happen to improve the experience overall.
See the following picture for reference (not for final design, only roughly positioned/sketched):
![cgsm](https://cloud.githubusercontent.com/assets/1182452/16255478/ae19fd16-387c-11e6-89d6-ed0fa5949e1b.png)

1 - Move search bar to header and have it available on the whole website.
2 - Once (1) is done, it allows to free some space on the map view.
3 - Wording: Are they studios or companies
4 - + icon for "Add studio" rather than upload icon
5 - Social icons hard to find
6 - make the map/list views slightly more intuitive. I like the icons, but it wasn't obvious to me at first what they would do if I clicked them.
7 - (not illustrated) From the list view, be able to click something to locate that studio on the map.

**Comment by M4rtine** [comment]
1 - Move search bar to header and have it available on the whole website.

Ce ne sera pas cette solution, le Bouton directory sera renomé et plus interactif et ça ne peut pas être 'MAP' parce que ce n'est pas seulement une Map

Il faut trouver 1 seule interaction qui va au même endroit. On ne peut pas avoir à la fos le bouton MAP qui va vers une page ou peut voir un listing et une barre de recherche qui va sur la map.

On va tout combiné.

**Comment by M4rtine** [comment]
_**2 - Once (1) is done, it allows to free some space on the map view.**_
Il va y avoir de nouvelles façon de filter les recherches et nous avons besoin de cette 2nde zone en dessous pour afficher les options de filtres de 2nd niveau.

**Comment by M4rtine** [comment]
**_3 - Wording: Are they studios or companies_**
Je ne suis pas contre A voir avec @MangoJazz

**Comment by herronelou** [comment]
1 - A voir comment vous combinez le tout. La pluspart des sites ces jours ci ont une barre de recherche toujours presente (Facebook, Linkedin, Github, Twitter, ...) qui permet un navigation rapide depuis partout. Avoir un autre bouton (peu importe le nom) pour ouvrir un map sans filtres reste necessaire.

**Comment by M4rtine** [comment]
**_4 - + icon for "Add studio" rather than upload icon_**
Je comprends l'idée je vais voir ce que je peux faire mais le "+" seul n'était pas visuellement intéressant. En effet l'icone upload n'est peut être pas pertinent mais l'idée était plus "Ajout d'une fiche".
Je vais y réfléchir.

**Comment by M4rtine** [comment]
**_5 - Social icons hard to find_**
Bien vu, je suis déjà dessus. Mais je vais combiner ce problème avec le fait que la MAP est trop décontrasté. Je vais changer légèrement le visuel de la MAP.

**Comment by herronelou** [comment]
5 - Vu qu'ils sont deja dans le footer de la page d'acceuil et dans "about", peut etre les avoir en petit dans un coin du header pourrait etre suffisant?

**Comment by M4rtine** [comment]
**_6 - make the map/list views slightly more intuitive. I like the icons, but it wasn't obvious to me at first what they would do if I clicked them._**
Entièrement d'accord. Je pensais mettre du texte en dessous des icônes et en mobile ne peut plus avoir les textes.

**Comment by M4rtine** [comment]
**_7 - (not illustrated) From the list view, be able to click something to locate that studio on the map._**
Très bonne idée.

**Comment by MangoJazz** [comment]
Salut vous deux :).

Alors au début je pensais aussi à mettre "compagnies" mais pourquoi CG
Studio Map?

Si on garde studios ça fonctionne bien avec notre nom mais ça ferme
l'arrivée des autres entreprises.

Ok j'y réfléchis et je vous reviens.

Merci Erwan pour ton aide et on se voit bientôt à ce que j'ai compris.

**Comment by MangoJazz** [comment]
Je propose une mini phrase:

Find a studio
Find a business
Find a company

On s'attend à chercher dans un annuaire tout simplement. Qu'en pensez vous
?

**Comment by foutoucour** [comment]
3. Passons a `Companies`. Ca va mettre en avant que `cgstudiomap` est la "marque", le concept plus que le scope du projet.
On a deja fait le premier pas dans un sens puisqu'on a une liste et pas juste une map.

1. `Search for a company`. `Find` inclue que l'user va trouver quelque chose je pense. Ce n'est pas quelque chose qu'on garanti.

**Comment by M4rtine** [comment]
Traité ici  #748

**Comment by foutoucour** [comment]
done in #755
