### ISSUE TITLE
En tant qu'utilisateur, je voudrais etre mis au courant que ma mise a jour peut prendre du temps a etre affiche.

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#694]
Revoir le texte de la page qui est affichee lorsqu'une fiche est mise a jour pour mettre en avant que le site peut mettre du temps a afficher l'update.

**Comment by foutoucour** [comment]
@MangoJazz on en parle pour que la situation soit bien clair. Ca permettra de faire un message clair pour l'user.

**Comment by MangoJazz** [comment]
ok perfect

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2016-06-23 8:35 GMT-04:00 Jordi Riera <notifications@github.com>:

**Comment by MangoJazz** [comment]
@foutoucour ça n'a plus lieu cette tache?

**Comment by foutoucour** [comment]
won't do
