### ISSUE TITLE
Geo-marqueurs ajoutés dans l'Ocean

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#702]
J'ai remarqué que l'un des studios que je venais d'ajouter (http://cgstudiomap.org/directory/company/oriental-dreamworks-6880) apparait au milieu de l'ocean sur la carte. J'ai checké sur Google Maps la meme adresse, et la position semble correcte.
![2016-09-07_11h39_08](https://cloud.githubusercontent.com/assets/1182452/18299046/2659146a-74f0-11e6-8d45-b923d827a8b4.png)
Quand je cherche avec le filter "China" il semble y avoir 2 studios dans l'eau a l'ouest de l'afrique. Sans filtre, il semble y en avoir 5.

**Comment by M4rtine** [comment]
Merci
Je connais ce genre de problème.
Je vais le corriger ;)

**Comment by M4rtine** [comment]
Ok c'est bon.

**Comment by herronelou** [comment]
Il en reste 3, le premier que je peux cliquer c'est
http://cgstudiomap.org/directory/company/mofac-alfred-6842

*Erwan* LEROY
www.erwanleroy.com

**Comment by M4rtine** [comment]
Pour celui la c'est un soucis d'adresse

**Comment by M4rtine** [comment]
Les adresses chinoises, koreene, indienne et thaïlandaise sont compliquées a interprété par google map. Et en plus souvent ce qui est écris ne correspond pas à la méthode internationale des adresses. 
Je cherche encore pour ce dernier studio

**Comment by M4rtine** [comment]
Alors pour Mofac le Zip code du site est faux et google ne n'en donne pas un.
Du coup j'ai cherché à la main
http://www.geopostcodes.com/Gangnam
et après il faut s'orienter et en mettant 06042 ça a debugé ce studio ;)

**Comment by foutoucour** [comment]
super travail @M4rtine ! :)
