### ISSUE TITLE
En tant que Web-designer, je voudrais équilibrer les contrastes et faire ressortir des détails vu à échelle humaine.

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#708]
- Réduire le contraste créer par le marqueur du studio.
- Différencier les routes de l'eau
- Accentuer les contrastes et couleurs des routes et détails de signalisation 
- Ajout des zones naturels

Ces 2 derniers points sont pour aider la localisation à échelle humaine et se rapprocher plus d'un design heureux que austère.

**Comment by M4rtine** [comment]
Done

**Comment by foutoucour** [comment]
done in #709
