### ISSUE TITLE
En tant que Web-Designer, je vais corriger un problème que j'avais déjà corrigé #227.

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#711]
En fait le problème est revenu à cause de ma méthode d'appel des logos qui a changé.

**Comment by foutoucour** [comment]
hey @M4rtine c'est fait non?

**Comment by M4rtine** [comment]
seulement si tu recompiles les SCSS

**Comment by M4rtine** [comment]
nan ce n'est pas bon je ne sais pas pourquoi :(
j'enquête

**Comment by M4rtine** [comment]
Done #731
