### ISSUE TITLE
Rédiger une entente de partenariat

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#721]
détailler sur papier ce qui a été établis par email avec Motion-Café

**Comment by MangoJazz** [comment]
en tente de review de @foutoucour et @M4rtine avant d'envoyer à Motion-Café.
A noter qu'il manque la date de livraison, voir avec @foutoucour.

**Comment by foutoucour** [comment]
C'est dans les mains de Motion-Cafe. On attend leur retour.
