### ISSUE TITLE
Error 404 en essayant de fermer un studio.

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#722]
J'essayais de fermer Psyop Vancouver qui a fermé fin Aout, mais error 404 quand je clique "close"

**Comment by M4rtine** [comment]
Oui je confirme le bug.
Mais cela ne se produit que quand on clic sur le quick bouton closed dans la fiche du studio.

Sinon en faisant Edit - Set as closed
ça marche.

**Comment by foutoucour** [comment]
Je pense que le probleme est que l'utilisateur n'est plus autorisé à voir le studio fermé ou un truc du genre.

Merci pour le retour @herronelou !

**Comment by foutoucour** [comment]
Ca a ete mis a en place. 

La route vers la page de cloture n'etait pas faite.
