### ISSUE TITLE
Ameliorer l'implementation de cgsm fonts

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#739]
Prendre une font plus propre, lisible et internationale
laisser seulement certaines zones avec la font cgsm

**Comment by M4rtine** [comment]
Je l'ai mis en place dans la #738 de manière temporaire.
il faudra cleaner

@foutoucour j'aurais besoin du compiler scss steuplé

**Comment by foutoucour** [comment]
@M4rtine tu peux verifier que ca donne bien ce que tu veux?

(faut vraiment que tu penses a mettre des screenshots, histoire que je puisse valider par moi meme :( )

**Comment by M4rtine** [comment]
??

**Comment by foutoucour** [comment]
ahh ca doit pas tres fait du tout ca :D

**Comment by M4rtine** [comment]
Je l'ai fais en partie sur le pull que tu as mis en ligne
Cette issue est la pour me rappeller qu'il faut que je le refasse mieux
avec la scss

Du coup celle cest pour moi et ce n'est pas fais

**Comment by M4rtine** [comment]
Ah mais tu l'a compilé c'est cool c'est bon sur l'ensemble du site.
Il me manquera plus qu'à désactiver la font CGSM a certains endroits et réglé les tailles.

**Comment by M4rtine** [comment]
Done
continue #749
