### ISSUE TITLE
Retravailler les termes utilises dans la catch phrase

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#742]
relie a #662 

De @M4rtine 
> Perso c'est le 2nd chapitre qui me dérange. C'est long et pas homogène.
> 
> "You probably heard about 3D animated feature film, visual effects (VFX) and video game but there are many more areas where CG may be found: print design, web design or interactive mediums such as digital signage. This is why CG Studio Map has decided to gather them all in one place!"
> 
> 3D animated feature film = computer-animated film
> si on parle de visual effects on ne met pas VFX ou alors on met le tag pour tous les autres
> video game = games
> 
> sur wikipedia ils mettent ça
> "animation, movies, advertising, video games, and graphic design"
> https://en.wikipedia.org/wiki/Computer_graphics
> 
> En fait plus c'est long le texte moins c'est lu et plus c'est dur de le rendre lisible.
> Je n'ai pas la solution du wording ou de la synthèse des phrases. Je vous partage mon avis.
> 
> Je design le texte tel qui l'a été écris quand même.

**Comment by M4rtine** [comment]
Si on va dans la logique d'expliquer le sujet du projet on ne comprend pas pourquoi cette question est posée : "What is Computer Graphics ?"
il faudrait mettre "What is CG ?" pour faire le rapprochement avec le nom du site et mettre l'explication.

**Comment by M4rtine** [comment]
" interactive mediums such as digital signage "
Je n'ai pas entendu parler de "digital signage". Est ce que c'est pour ce genre de projet ?
 websites, apps, UI/UX design, visual content creation, interactive data visualisations and installations.

**Comment by MangoJazz** [comment]
@M4rtine 

1) Ce design avec la phrase que tu as fait est bien, pourrais-tu la remonter au dessus du bloc de texte?
![uploads/c876bc76-a1ac-4299-8566-f192b27ec04a/Screen Shot 2016-11-28 at 7.17.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc876bc76-a1ac-4299-8566-f192b27ec04a%2FScreen+Shot+2016-11-28+at+7.17.20+PM.png)

2) Pourrais-tu aussi enlever tout le texte SVP? Il ne sert pas à grand chose finalement comme tu disais car les 4 blocs de textes dessous sont déjà très explicatifs.

3) L'idée des tags au dessous de la phrase afin de montrer au visiteurs quels genres de compagnies sont sur CG Studio Map, est-ce que ça te plairait?

**Comment by M4rtine** [comment]
Parfait c'est tout clair. Je ferais ça sur une nouvelle branche. L'idée des tags est géniale parce que ca fait des possibilités de liens supplémentaires

**Comment by M4rtine** [comment]
En attente de la nouvelle homepage

**Comment by foutoucour** [comment]
La page est partie... pouf, plus la... 
voir #780 #781 #788
