### ISSUE TITLE
Navbar enhancement

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#748]
Améliorer la vitesse et le visuel de la navigation.
issue #693 & #691

**Comment by M4rtine** [comment]
@foutoucour mince je n'ai toujours pas le compileur SCSS
tu peux me le mettre s'il te plait

**Comment by foutoucour** [comment]
Je te l'installe en ce moment meme

**Comment by foutoucour** [comment]
c'est en place:
```--- 03:49:26 pi@master ~/cgstudiomap  (748-navbar-enhancement)  
>>> sass --version
Sass 3.4.22 (Selective Steve)
```
doc de sass: http://sass-lang.com/documentation/file.SASS_REFERENCE.html

**Comment by M4rtine** [comment]
PARFAIT


____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*


2016-11-19 15:50 GMT+01:00 Jordi Riera <notifications@github.com>:

**Comment by M4rtine** [comment]
@foutoucour Yo j'ai push mes modifs. Je n'ai pas fini mais est ce que tu peux m'aider pour un truc que j'arrive pas à faire.

Il faudrait connecter pour de vrai  la nouvelle barre de recherche (frontend_base)
Et il faudrait aussi supprimer toute la ligne avec l'ancien formulaire de recherche et le bouton Add.
Quand je le fais j'ai des erreurs de syntaxe xml :(

Merci tiens moi au jus.

Grosse update ça va être sympa

**Comment by M4rtine** [comment]
branch  748-navbar-enhancement

**Comment by foutoucour** [comment]
ok nice :)

Tu peux me mettre une capture d'écran pour que je sache le résultat que tu attends?

**Comment by M4rtine** [comment]
@foutoucour nan g pas de screens avant ce soir (Heure fr) c'est juste de l'aide sur la syntaxe xml pour faire marcher la barre de recherche que j'ai mis dans la navbar. elle n'est pas connecté.
