### ISSUE TITLE
HEAD enhancement 

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#75]
Make the header better =
HTML > no script
HEAD > touchable viewport 
           > og meta facebook 
           > meta twitter 
           > meta webapps 
JSON > schema

**Comment by foutoucour** [comment]
Hey,

What are the benefits of these changes?

Are you sure we need them for 0.1?

**Comment by M4rtine** [comment]
best SEO
best experience sharing on social networks
and best touchable experience

it's allready done, i need just to know where i paste it ;)

**Comment by foutoucour** [comment]
Is that fixed in #76 ?

**Comment by M4rtine** [comment]
yes
