### ISSUE TITLE
Bug avec un studio ayant un caractere special, comme Faak&Paat, sur la carte mais pas sur la liste

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#762]
Le studio Faak&Paat se trouve dans la Map mais dans la liste on a aucun résultat. Weird hey!

![uploads/882d6e19-7591-4fdc-be0d-f1d2fb54b127/Screen Shot 2016-12-10 at 10.20.56 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F882d6e19-7591-4fdc-be0d-f1d2fb54b127%2FScreen+Shot+2016-12-10+at+10.20.56+AM.png)

![uploads/db153f67-d55c-435e-965d-a0e280606f65/Screen Shot 2016-12-10 at 10.20.45 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdb153f67-d55c-435e-965d-a0e280606f65%2FScreen+Shot+2016-12-10+at+10.20.45+AM.png)

**Comment by M4rtine** [comment]
À voir les caractères spéciaux c'est le second comme ça

**Comment by M4rtine** [comment]
En même temps leurs noms n'est pas clair ni identifié légalement 
Je vais enlever le caractère spécial

**Comment by MangoJazz** [comment]
Ok merci @M4rtine c'était bien du au caractère spécial.
