### ISSUE TITLE
La ville d'un studio ne veut pas etre acceptee

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#763]
3dMD

à chaque fois que je sauvegarde, la ville se met automatiquement à england. Ca ne veut pas accepter Brentford.

http://www.cgstudiomap.org/directory/company/3dmd-3339

**Comment by M4rtine** [comment]
Brentford n'est pas à Londres ??

**Comment by M4rtine** [comment]
Ah oui non pardon je viens de comprendre

**Comment by M4rtine** [comment]
Je confirme le bug mais y'a pas de solutions qui marche. Ca doit être un vieux duplicata du studio d'Atlanta.
On ira plus vite en repartant de 0 pour cette fiche

**Comment by M4rtine** [comment]
y'a le même problème avec 
Animaticmedia

**Comment by foutoucour** [comment]
C'était un problème de référence à google.

**Comment by foutoucour** [comment]
The fix marche. J'ai pu corriger les fiches ayant `England` comme villes

**Comment by M4rtine** [comment]
England était toujours là
Je l'ai corriger à la main.
