### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#78]
The scroll disappeared and make the usage of the front end hard on little screen.

Could you see why it is gone?

**Comment by M4rtine** [comment]
I update the custom.scss with my iphone ;)
Done

**Comment by foutoucour** [comment]
Fixed in #79 (f4c249be521ba1c58473c417cef058acc42c1af8)

**Comment by foutoucour** [comment]
Updated on the server directly in base.css to avoid to bring all the updates

![screen shot 2015-05-07 at 1 11 17 pm](https://cloud.githubusercontent.com/assets/547282/7521268/92912ad0-f4ba-11e4-85b5-b75dd8ad97a3.png)

**Comment by foutoucour** [comment]
tu pourrais me dire si les modification faites sur le head permettent de
fermer cette tache: https://github.com/cgstudiomap/cgstudiomap/issues/75

merci

On Thu, May 7, 2015 at 12:17 PM, David Mazeau <notifications@github.com>
wrote:

> I update the custom.scss with my iphone ;)
> Done
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/78#issuecomment-99925951>
> .
>



-- 
- Jordi Riera, Connecting Softwares and people.
+1 438 930 3718
www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>
