### ISSUE TITLE
En tant que Developeur, je dois corriger l'erreur du Nulos WebDesigner; mettre le menu Dashboard dans le menu déroulant des utilisateurs connectés.

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#786]
Est ce que le dashboard est visible pour tous les utlisateurs ou seulement les Admins ?

**Comment by foutoucour** [comment]
Uniquement aux personnes qui sont dans le groupe `group_archetype_direct_link_to_dashboard`

Le lien est créée dans le module frontend_link_to_dashboard. Probablement pour ca que tu l'as loupe :) Perso j'aime bien la ou il est :)

voir: https://github.com/cgstudiomap/cgstudiomap/blob/develop/main/local_modules/frontend_link_to_dashboard/template_body.xml

**Comment by M4rtine** [comment]
Merci mais en fait resize ta fenêtre et tu verras que ca petes tout le site
sur toutes les pages

**Comment by M4rtine** [comment]
J'avais désactivé l'option dans les paramètres Odoo de mon serveur local.
Mais comme j'ai du merdé dans le code.
J'ai pas vu ma connerie local

**Comment by M4rtine** [comment]
Done

**Comment by M4rtine** [comment]
![uploads/7186fdd4-5154-4d54-a013-7a49f5b17726/#786_bug_link_dashboard.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7186fdd4-5154-4d54-a013-7a49f5b17726%2F%23786_bug_link_dashboard.jpg)
