### ISSUE TITLE
Problème avec States en espagne

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#791]
Le studio http://cgstudiomap.org/directory/company/binalogue-7147 a son state a Comunidad Valenciana qui est a plus de 500km de là.

Je pense que le bug vient de #763 

il faudrait corriger ca.

**Comment by M4rtine** [comment]
Done ;)
Je l'ai corriger avec le bidouillage magique

**Comment by foutoucour** [comment]
Le problème était plus profond que ça au final.
Il y avait une confusion entre des states qui commencent pas les mêmes lettres.
J'ai amélioré l'algo

**Comment by M4rtine** [comment]
gg
