### ISSUE TITLE
IM Chat under the Map

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#80]
As the screenshot shows:
![imandmap](https://cloud.githubusercontent.com/assets/547282/7568343/3add2f0a-f7d0-11e4-94c2-2dd96da7c476.png)

The maps goes over the IM chat.

To solve the issue:
* increase the z-index of the the css classes of the chat (.oe_im and .oe_im_chatview)

We can't interact with the map as the z-index is hard coded into the code :( 
Need to post a patch for that

**Comment by M4rtine** [comment]
Fixed in #100
