### ISSUE TITLE
message d'erreur en grand et rouge

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#802]
@M4rtine je te fais un screen shot du message d'erreur qui apparait sur la page studio quand l'adresse est fausse:

![uploads/a48ed927-48cf-45ac-9252-63aeca3bf7a1/Screen Shot 2017-02-01 at 8.56.59 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa48ed927-48cf-45ac-9252-63aeca3bf7a1%2FScreen+Shot+2017-02-01+at+8.56.59+PM.png)

est-ce normal?

**Comment by M4rtine** [comment]
Ce n'est pas normal, mais c'est connu. Il y a déjà une issue pour ça
