### ISSUE TITLE
En tant que Developeur, je souhaiterai utiliser un accès HTTPS (sécurisé) et du certificat qui va avec pour profiter d'un meilleur Référencement google, de la géolocalisation simple et interactif des utilisateurs ordis/mobile.

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#809]
Ne pas prendre un certificat payant.
https://letsencrypt.org
Automatiser le renouvellement tous les mois.

PISTE :
https://www.nginx.com/blog/free-certificates-lets-encrypt-and-nginx/

**Comment by foutoucour** [comment]
related to #17

**Comment by foutoucour** [comment]
j'utilise https://www.digitalocean.com/community/tutorials/how-to-install-an-ssl-certificate-from-a-commercial-certificate-authority

documentation: https://github.com/cgstudiomap/cgstudiomap/wiki/configuration

**Comment by foutoucour** [comment]
Setup of the automatic renew
``` sh
sudo crontab -l
# Renew the SSL certification:
# https://github.com/cgstudiomap/cgstudiomap/issues/809
# https://hostpresto.com/community/tutorials/how-to-secure-your-apache-using-certbot-ssl/
# The above command will run the installer script to renew the certificate at 1 AM,
# every Monday. If the script finds any certificate which is to be renewed within 30 days,
# installer will automatically renew them. We have used --quiet argument so that installer 
# will work in background and will not produce any error or warning.
* 1 * * 1 /etc/certbot-auto renew --quiet 

```

**Comment by foutoucour** [comment]
Le site est sous HTTPS!

![2017-03-05-15 48 07_c](https://cloud.githubusercontent.com/assets/547282/23591252/6a6f61d8-01bb-11e7-993f-ac877259febf.png)
