### ISSUE TITLE
Text about the philosophy of the project 

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#85]
Write in the wiki the text about the new philosophy of the project:
* [ ] why open source
* [ ] why community based

**Comment by foutoucour** [comment]
Talks to be inspired from:
[Start With Why - Simon Sinek TED talk](https://www.youtube.com/watch?v=sioZd3AxmnE)

**Comment by foutoucour** [comment]
First page about the background of the project: https://github.com/cgstudiomap/cgstudiomap/wiki/Introduction WIP

**Comment by MangoJazz** [comment]
ping @foutoucour
