### ISSUE TITLE
Favorite companies

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#9]
Allows user to set a company as a favorite.

The selection of a favorite should appear to the user as a boolean but in the system is will be a function.
A function is required here as the company will be set as favorite to the user but not to everyone.

to be implemented:
* add a many2many field `favorite_ids` related to res.users
* add a boolean `favorite` that is a function:
    * The state of the boolean at the loading of the page depending if the current user is in `favorite_ids`
    * The state will be update at the write of the record depending if the boolean is selected or not.
* a new entry in the portal view called `favorites` that filter company by `('favorite' , '=', True)`

**Comment by foutoucour** [comment]
#10

**Comment by MangoJazz** [comment]
the comment section should go away and instead a sentence like:

Did you find this info useful?

**Comment by MangoJazz** [comment]
decision durant un skype, pas pour le moment.
